// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.location;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class SettingInjectorService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String ACTION_INJECTED_SETTING_CHANGED = "android.location.InjectedSettingChanged";
    public static final java.lang.String ACTION_SERVICE_INTENT = "android.location.SettingInjectorService";
    public static final java.lang.String ATTRIBUTES_NAME = "injected-location-setting";
    public static final java.lang.String ENABLED_KEY = "enabled";
    public static final java.lang.String MESSENGER_KEY = "messenger";
    public static final java.lang.String META_DATA_NAME = "android.location.SettingInjectorService";
    public static final java.lang.String SUMMARY_KEY = "summary";
    public SettingInjectorService(java.lang.String p0) { super(); }
    public static void refreshSettings(android.content.Context p0) {}
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    protected abstract boolean onGetEnabled();
    protected abstract java.lang.String onGetSummary();
    SettingInjectorService() { this((java.lang.String) null); }
}
