// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.content;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class AsyncQueryHandler extends android.os.Handler {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public AsyncQueryHandler(android.content.ContentResolver p0) { super(); }
    public void cancelOperation(int p0) {}
    protected android.os.Handler createHandler(android.os.Looper p0) { return null; }
    protected void onDeleteComplete(int p0, java.lang.Object p1, int p2) {}
    protected void onInsertComplete(int p0, java.lang.Object p1, android.net.Uri p2) {}
    protected void onQueryComplete(int p0, java.lang.Object p1, android.database.Cursor p2) {}
    protected void onUpdateComplete(int p0, java.lang.Object p1, int p2) {}
    public void startDelete(int p0, java.lang.Object p1, android.net.Uri p2, java.lang.String p3, java.lang.String[] p4) {}
    public void startInsert(int p0, java.lang.Object p1, android.net.Uri p2, android.content.ContentValues p3) {}
    public void startQuery(int p0, java.lang.Object p1, android.net.Uri p2, java.lang.String[] p3, java.lang.String p4, java.lang.String[] p5, java.lang.String p6) {}
    public void startUpdate(int p0, java.lang.Object p1, android.net.Uri p2, android.content.ContentValues p3, java.lang.String p4, java.lang.String[] p5) {}
    AsyncQueryHandler() { this((android.content.ContentResolver) null); }
    public static final class WorkerArgs {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public java.lang.Object cookie;
        public android.os.Handler handler;
        public java.lang.String orderBy;
        public java.lang.String[] projection;
        public java.lang.Object result;
        public java.lang.String selection;
        public java.lang.String[] selectionArgs;
        public android.net.Uri uri;
        public android.content.ContentValues values;
        protected WorkerArgs() {}
    }
    public static class WorkerHandler extends android.os.Handler {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public WorkerHandler(android.content.AsyncQueryHandler p0, android.os.Looper p1) { super(); }
        public void handleMessage(android.os.Message p0) {}
        WorkerHandler() { this((android.content.AsyncQueryHandler) null, (android.os.Looper) null); }
    }
}
