// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.tv.ad;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TvAdView extends android.view.ViewGroup {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String ERROR_KEY_ERROR_CODE = "error_code";
    public static final java.lang.String ERROR_KEY_METHOD_NAME = "method_name";
    public TvAdView(android.content.Context p0) { super(p0); }
    public TvAdView(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public TvAdView(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public void clearCallback() {}
    public void clearOnUnhandledInputEventListener() {}
    public boolean dispatchUnhandledInputEvent(android.view.InputEvent p0) { return false; }
    public android.media.tv.ad.TvAdManager.Session getAdSession() { return (android.media.tv.ad.TvAdManager.Session) huskProps.get("AdSession"); }
    public android.media.tv.ad.TvAdView.OnUnhandledInputEventListener getOnUnhandledInputEventListener() { return (android.media.tv.ad.TvAdView.OnUnhandledInputEventListener) huskProps.get("OnUnhandledInputEventListener"); }
    public void notifyError(java.lang.String p0, android.os.Bundle p1) {}
    public void notifyTvMessage(int p0, android.os.Bundle p1) {}
    public void onLayout(boolean p0, int p1, int p2, int p3, int p4) {}
    public boolean onUnhandledInputEvent(android.view.InputEvent p0) { return false; }
    public void prepareAdService(java.lang.String p0, java.lang.String p1) {}
    public void reset() {}
    public void resetAdService() {}
    public void sendCurrentChannelUri(android.net.Uri p0) {}
    public void sendCurrentTvInputId(java.lang.String p0) {}
    public void sendCurrentVideoBounds(android.graphics.Rect p0) {}
    public void sendSigningResult(java.lang.String p0, byte[] p1) {}
    public void sendTrackInfoList(java.util.List p0) {}
    public void setCallback(java.util.concurrent.Executor p0, android.media.tv.ad.TvAdView.TvAdCallback p1) {}
    public void setOnUnhandledInputEventListener(android.media.tv.ad.TvAdView.OnUnhandledInputEventListener p0) { huskProps.put("OnUnhandledInputEventListener", p0); }
    public boolean setTvView(android.media.tv.TvView p0) { return false; }
    public void setZOrderMediaOverlay(boolean p0) { huskProps.put("ZOrderMediaOverlay", Boolean.valueOf(p0)); }
    public void setZOrderOnTop(boolean p0) { huskProps.put("ZOrderOnTop", Boolean.valueOf(p0)); }
    public void startAdService() {}
    public void stopAdService() {}
    TvAdView() { this((android.content.Context) null); }
    public interface OnUnhandledInputEventListener {
        boolean onUnhandledInputEvent(android.view.InputEvent p0);
    }
    public static abstract class TvAdCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public TvAdCallback() {}
        public void onRequestCurrentChannelUri(java.lang.String p0) {}
        public void onRequestCurrentTvInputId(java.lang.String p0) {}
        public void onRequestCurrentVideoBounds(java.lang.String p0) {}
        public void onRequestSigning(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3, byte[] p4) {}
        public void onRequestTrackInfoList(java.lang.String p0) {}
        public void onStateChanged(java.lang.String p0, int p1, int p2) {}
    }
}
