package android.net;
/** The network as the app sees it: always connected, over Wi-Fi (Husk does not watch the iPhone's network). */
public class ConnectivityManager {
    public static final int TYPE_NONE = -1, TYPE_MOBILE = 0, TYPE_WIFI = 1, TYPE_ETHERNET = 9, TYPE_VPN = 17, RESTRICT_BACKGROUND_STATUS_DISABLED = 1;
    public static final String CONNECTIVITY_ACTION = "android.net.conn.CONNECTIVITY_CHANGE", EXTRA_NO_CONNECTIVITY = "noConnectivity", EXTRA_NETWORK_INFO = "networkInfo";
    public static class NetworkCallback {
        public NetworkCallback() {} public NetworkCallback(int flags) {}
        public void onAvailable(Network n) {} public void onLosing(Network n, int ms) {} public void onLost(Network n) {} public void onUnavailable() {}
        public void onCapabilitiesChanged(Network n, NetworkCapabilities c) {} public void onLinkPropertiesChanged(Network n, LinkProperties p) {} public void onBlockedStatusChanged(Network n, boolean b) {}
        // ---- generated by tools/compat/fillmembers.py (NetworkCallback): the platform's members this class does not write (signatures only)
        public static final int DECLARED_METHODS_ALL = -1;
        public static final int DECLARED_METHODS_NONE = 0;
        public static final int FLAG_INCLUDE_LOCATION_INFO = 1;
        public static final int FLAG_NONE = 0;
        public void onAvailable(android.net.Network p0, android.net.NetworkCapabilities p1, android.net.LinkProperties p2, boolean p3) {}
        public void onBlockedStatusChanged(android.net.Network p0, int p1) {}
        public void onNetworkResumed(android.net.Network p0) {}
        public void onNetworkSuspended(android.net.Network p0) {}
        public void onPreCheck(android.net.Network p0) {}
        public void onReserved(android.net.NetworkCapabilities p0) {}
        // ---- end of generated members (NetworkCallback)
    }
    public interface OnNetworkActiveListener { void onNetworkActive(); }
    private static final Network sNet = new Network();
    public NetworkInfo getActiveNetworkInfo() { return new NetworkInfo(); }
    public NetworkInfo getNetworkInfo(int type) { return type == TYPE_WIFI ? new NetworkInfo() : null; }
    public NetworkInfo getNetworkInfo(Network n) { return new NetworkInfo(); }
    public NetworkInfo[] getAllNetworkInfo() { return new NetworkInfo[] { new NetworkInfo() }; }
    public Network getActiveNetwork() { return sNet; }
    public Network[] getAllNetworks() { return new Network[] { sNet }; }
    public NetworkCapabilities getNetworkCapabilities(Network n) { return new NetworkCapabilities(); }
    public LinkProperties getLinkProperties(Network n) { return new LinkProperties(); }
    public boolean isActiveNetworkMetered() { return false; }
    public boolean isDefaultNetworkActive() { return true; }
    public int getRestrictBackgroundStatus() { return RESTRICT_BACKGROUND_STATUS_DISABLED; }
    public boolean bindProcessToNetwork(Network n) { return true; }
    public Network getBoundNetworkForProcess() { return null; }
    /* as Android: callbacks come on the connectivity thread unless the app gives a handler (the main thread may be busy for a
       long while at start-up, and WorkManager gives up on a constraint whose callback is a second late) */
    private static android.os.Handler sThread;
    private static synchronized android.os.Handler connectivityThread() {
        if (sThread == null) { android.os.HandlerThread t = new android.os.HandlerThread("ConnectivityThread"); t.start(); sThread = new android.os.Handler(t.getLooper()); }
        return sThread;
    }
    private void announce(NetworkRequest r, NetworkCallback cb, android.os.Handler h) {
        if (r != null && !r.canBeSatisfiedBy(new NetworkCapabilities())) { (h != null ? h : connectivityThread()).post(cb::onUnavailable); return; }
        (h != null ? h : connectivityThread()).post(() -> { cb.onAvailable(sNet); cb.onCapabilitiesChanged(sNet, new NetworkCapabilities()); cb.onLinkPropertiesChanged(sNet, new LinkProperties()); cb.onBlockedStatusChanged(sNet, false); });
    }
    private void announce(NetworkCallback cb) { announce(null, cb, null); }
    public void registerNetworkCallback(NetworkRequest r, NetworkCallback cb) { announce(r, cb, null); }
    public void registerNetworkCallback(NetworkRequest r, NetworkCallback cb, android.os.Handler h) { announce(r, cb, h); }
    public void registerDefaultNetworkCallback(NetworkCallback cb) { announce(null, cb, null); }
    public void registerDefaultNetworkCallback(NetworkCallback cb, android.os.Handler h) { announce(null, cb, h); }
    public void requestNetwork(NetworkRequest r, NetworkCallback cb) { announce(r, cb, null); }
    public void requestNetwork(NetworkRequest r, NetworkCallback cb, int timeout) { announce(r, cb, null); }
    public void unregisterNetworkCallback(NetworkCallback cb) {}
    public void addDefaultNetworkActiveListener(OnNetworkActiveListener l) {}
    public void removeDefaultNetworkActiveListener(OnNetworkActiveListener l) {}
    public static boolean isNetworkTypeValid(int t) { return t >= 0; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public ConnectivityManager() {}
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final java.lang.String ACTION_BACKGROUND_DATA_SETTING_CHANGED = "android.net.conn.BACKGROUND_DATA_SETTING_CHANGED";
    public static final java.lang.String ACTION_CAPTIVE_PORTAL_SIGN_IN = "android.net.conn.CAPTIVE_PORTAL";
    public static final java.lang.String ACTION_CAPTIVE_PORTAL_TEST_COMPLETED = "android.net.conn.CAPTIVE_PORTAL_TEST_COMPLETED";
    public static final java.lang.String ACTION_CLEAR_DNS_CACHE = "android.net.action.CLEAR_DNS_CACHE";
    public static final java.lang.String ACTION_DATA_ACTIVITY_CHANGE = "android.net.conn.DATA_ACTIVITY_CHANGE";
    public static final java.lang.String ACTION_PROMPT_LOST_VALIDATION = "android.net.action.PROMPT_LOST_VALIDATION";
    public static final java.lang.String ACTION_PROMPT_PARTIAL_CONNECTIVITY = "android.net.action.PROMPT_PARTIAL_CONNECTIVITY";
    public static final java.lang.String ACTION_PROMPT_UNVALIDATED = "android.net.action.PROMPT_UNVALIDATED";
    public static final java.lang.String ACTION_RESTRICT_BACKGROUND_CHANGED = "android.net.conn.RESTRICT_BACKGROUND_CHANGED";
    public static final java.lang.String ACTION_TETHER_STATE_CHANGED = "android.net.conn.TETHER_STATE_CHANGED";
    public static final int BLOCKED_METERED_REASON_ADMIN_DISABLED = 262144;
    public static final int BLOCKED_METERED_REASON_DATA_SAVER = 65536;
    public static final int BLOCKED_METERED_REASON_MASK = -65536;
    public static final int BLOCKED_METERED_REASON_USER_RESTRICTED = 131072;
    public static final int BLOCKED_REASON_APP_BACKGROUND = 64;
    public static final int BLOCKED_REASON_APP_STANDBY = 4;
    public static final int BLOCKED_REASON_BATTERY_SAVER = 1;
    public static final int BLOCKED_REASON_DOZE = 2;
    public static final int BLOCKED_REASON_LOCKDOWN_VPN = 16;
    public static final int BLOCKED_REASON_LOW_POWER_STANDBY = 32;
    public static final int BLOCKED_REASON_NETWORK_RESTRICTED = 256;
    public static final int BLOCKED_REASON_NONE = 0;
    public static final int BLOCKED_REASON_OEM_DENY = 128;
    public static final int BLOCKED_REASON_RESTRICTED_MODE = 8;
    public static final int CALLBACK_AVAILABLE = 2;
    public static final int CALLBACK_BLK_CHANGED = 11;
    public static final int CALLBACK_CAP_CHANGED = 6;
    public static final int CALLBACK_IP_CHANGED = 7;
    public static final int CALLBACK_LOCAL_NETWORK_INFO_CHANGED = 12;
    public static final int CALLBACK_LOSING = 3;
    public static final int CALLBACK_LOST = 4;
    public static final int CALLBACK_PRECHECK = 1;
    public static final int CALLBACK_RESERVED = 13;
    public static final int CALLBACK_RESUMED = 10;
    public static final int CALLBACK_SUSPENDED = 9;
    public static final int CALLBACK_UNAVAIL = 5;
    public static final int DEFAULT_NETWORK_PREFERENCE = 1;
    public static final java.lang.String EXTRA_ACTIVE_LOCAL_ONLY = "android.net.extra.ACTIVE_LOCAL_ONLY";
    public static final java.lang.String EXTRA_ACTIVE_TETHER = "tetherArray";
    public static final java.lang.String EXTRA_ADD_TETHER_TYPE = "extraAddTetherType";
    public static final java.lang.String EXTRA_AVAILABLE_TETHER = "availableArray";
    public static final java.lang.String EXTRA_CAPTIVE_PORTAL = "android.net.extra.CAPTIVE_PORTAL";
    public static final java.lang.String EXTRA_CAPTIVE_PORTAL_PROBE_SPEC = "android.net.extra.CAPTIVE_PORTAL_PROBE_SPEC";
    public static final java.lang.String EXTRA_CAPTIVE_PORTAL_URL = "android.net.extra.CAPTIVE_PORTAL_URL";
    public static final java.lang.String EXTRA_CAPTIVE_PORTAL_USER_AGENT = "android.net.extra.CAPTIVE_PORTAL_USER_AGENT";
    public static final java.lang.String EXTRA_DEVICE_TYPE = "deviceType";
    public static final java.lang.String EXTRA_ERRORED_TETHER = "erroredArray";
    public static final java.lang.String EXTRA_EXTRA_INFO = "extraInfo";
    public static final java.lang.String EXTRA_INET_CONDITION = "inetCondition";
    public static final java.lang.String EXTRA_IS_ACTIVE = "isActive";
    public static final java.lang.String EXTRA_IS_CAPTIVE_PORTAL = "captivePortal";
    public static final java.lang.String EXTRA_IS_FAILOVER = "isFailover";
    public static final java.lang.String EXTRA_NETWORK = "android.net.extra.NETWORK";
    public static final java.lang.String EXTRA_NETWORK_REQUEST = "android.net.extra.NETWORK_REQUEST";
    public static final java.lang.String EXTRA_NETWORK_TYPE = "networkType";
    public static final java.lang.String EXTRA_OTHER_NETWORK_INFO = "otherNetwork";
    public static final java.lang.String EXTRA_PROVISION_CALLBACK = "extraProvisionCallback";
    public static final java.lang.String EXTRA_REALTIME_NS = "tsNanos";
    public static final java.lang.String EXTRA_REASON = "reason";
    public static final java.lang.String EXTRA_REM_TETHER_TYPE = "extraRemTetherType";
    public static final java.lang.String EXTRA_RUN_PROVISION = "extraRunProvision";
    public static final java.lang.String EXTRA_SET_ALARM = "extraSetAlarm";
    public static final long FEATURE_QUEUE_NETWORK_AGENT_EVENTS_IN_SYSTEM_SERVER = 2L;
    public static final long FEATURE_USE_DECLARED_METHODS_FOR_CALLBACKS = 1L;
    public static final int FIREWALL_CHAIN_BACKGROUND = 6;
    public static final int FIREWALL_CHAIN_DOZABLE = 1;
    public static final int FIREWALL_CHAIN_LOW_POWER_STANDBY = 5;
    public static final int FIREWALL_CHAIN_METERED_ALLOW = 10;
    public static final int FIREWALL_CHAIN_METERED_DENY_ADMIN = 12;
    public static final int FIREWALL_CHAIN_METERED_DENY_USER = 11;
    public static final int FIREWALL_CHAIN_OEM_DENY_1 = 7;
    public static final int FIREWALL_CHAIN_OEM_DENY_2 = 8;
    public static final int FIREWALL_CHAIN_OEM_DENY_3 = 9;
    public static final int FIREWALL_CHAIN_POWERSAVE = 3;
    public static final int FIREWALL_CHAIN_RESTRICTED = 4;
    public static final int FIREWALL_CHAIN_STANDBY = 2;
    public static final int FIREWALL_RULE_ALLOW = 1;
    public static final int FIREWALL_RULE_DEFAULT = 0;
    public static final int FIREWALL_RULE_DENY = 2;
    public static final java.lang.String INET_CONDITION_ACTION = "android.net.conn.INET_CONDITION_ACTION";
    public static final int MAX_NETWORK_TYPE = 18;
    public static final int MAX_RADIO_TYPE = 18;
    public static final int MULTIPATH_PREFERENCE_HANDOVER = 1;
    public static final int MULTIPATH_PREFERENCE_PERFORMANCE = 4;
    public static final int MULTIPATH_PREFERENCE_RELIABILITY = 2;
    public static final int MULTIPATH_PREFERENCE_UNMETERED = 7;
    public static final int NETID_UNSET = 0;
    public static final int PROFILE_NETWORK_PREFERENCE_DEFAULT = 0;
    public static final int PROFILE_NETWORK_PREFERENCE_ENTERPRISE = 1;
    public static final int PROFILE_NETWORK_PREFERENCE_ENTERPRISE_BLOCKING = 3;
    public static final int PROFILE_NETWORK_PREFERENCE_ENTERPRISE_NO_FALLBACK = 2;
    public static final int REQUEST_ID_UNSET = 0;
    public static final int RESTRICT_BACKGROUND_STATUS_ENABLED = 3;
    public static final int RESTRICT_BACKGROUND_STATUS_WHITELISTED = 2;
    public static final int TETHERING_BLUETOOTH = 2;
    public static final int TETHERING_INVALID = -1;
    public static final int TETHERING_USB = 1;
    public static final int TETHERING_WIFI = 0;
    public static final int TETHERING_WIFI_P2P = 3;
    public static final int TETHER_ERROR_DHCPSERVER_ERROR = 12;
    public static final int TETHER_ERROR_DISABLE_NAT_ERROR = 9;
    public static final int TETHER_ERROR_ENABLE_NAT_ERROR = 8;
    public static final int TETHER_ERROR_ENTITLEMENT_UNKONWN = 13;
    public static final int TETHER_ERROR_IFACE_CFG_ERROR = 10;
    public static final int TETHER_ERROR_MASTER_ERROR = 5;
    public static final int TETHER_ERROR_NO_ERROR = 0;
    public static final int TETHER_ERROR_PROVISION_FAILED = 11;
    public static final int TETHER_ERROR_SERVICE_UNAVAIL = 2;
    public static final int TETHER_ERROR_TETHER_IFACE_ERROR = 6;
    public static final int TETHER_ERROR_UNAVAIL_IFACE = 4;
    public static final int TETHER_ERROR_UNKNOWN_IFACE = 1;
    public static final int TETHER_ERROR_UNSUPPORTED = 3;
    public static final int TETHER_ERROR_UNTETHER_IFACE_ERROR = 7;
    public static final int TYPE_BLUETOOTH = 7;
    public static final int TYPE_DUMMY = 8;
    public static final int TYPE_MOBILE_CBS = 12;
    public static final int TYPE_MOBILE_DUN = 4;
    public static final int TYPE_MOBILE_EMERGENCY = 15;
    public static final int TYPE_MOBILE_FOTA = 10;
    public static final int TYPE_MOBILE_HIPRI = 5;
    public static final int TYPE_MOBILE_IA = 14;
    public static final int TYPE_MOBILE_IMS = 11;
    public static final int TYPE_MOBILE_MMS = 2;
    public static final int TYPE_MOBILE_SUPL = 3;
    public static final int TYPE_PROXY = 16;
    public static final int TYPE_TEST = 18;
    public static final int TYPE_WIFI_P2P = 13;
    public static final int TYPE_WIMAX = 6;
    public ConnectivityManager(android.content.Context p0, android.net.IConnectivityManager p1) { this(); }
    public static android.net.ConnectivityManager from(android.content.Context p0) { return null; }
    public static java.lang.String getCallbackName(int p0) { return null; }
    public static android.util.Range getIpSecNetIdRange() { return null; }
    public static java.lang.String getNetworkTypeName(int p0) { return null; }
    public static android.net.Network getProcessDefaultNetwork() { return null; }
    public static boolean isNetworkTypeMobile(int p0) { return false; }
    public static boolean isNetworkTypeWifi(int p0) { return false; }
    public static android.net.NetworkCapabilities networkCapabilitiesForType(int p0) { return null; }
    public static boolean setProcessDefaultNetwork(android.net.Network p0) { return false; }
    public static boolean setProcessDefaultNetworkForHostResolution(android.net.Network p0) { return false; }
    public void addUidToMeteredNetworkAllowList(int p0) {}
    public void addUidToMeteredNetworkDenyList(int p0) {}
    public android.net.ConnectivityDiagnosticsManager createDiagnosticsManager() { return null; }
    public android.net.SocketKeepalive createNattKeepalive(android.net.Network p0, android.os.ParcelFileDescriptor p1, java.net.InetAddress p2, java.net.InetAddress p3, java.util.concurrent.Executor p4, android.net.SocketKeepalive.Callback p5) { return null; }
    public android.net.SocketKeepalive createSocketKeepalive(android.net.Network p0, android.net.IpSecManager.UdpEncapsulationSocket p1, java.net.InetAddress p2, java.net.InetAddress p3, java.util.concurrent.Executor p4, android.net.SocketKeepalive.Callback p5) { return null; }
    public android.net.SocketKeepalive createSocketKeepalive(android.net.Network p0, java.net.Socket p1, java.util.concurrent.Executor p2, android.net.SocketKeepalive.Callback p3) { return null; }
    public void declareNetworkRequestUnfulfillable(android.net.NetworkRequest p0) {}
    public void factoryReset() {}
    public android.net.LinkProperties getActiveLinkProperties() { return null; }
    public android.net.Network getActiveNetworkForUid(int p0) { return null; }
    public android.net.Network getActiveNetworkForUid(int p0, boolean p1) { return null; }
    public android.net.NetworkInfo getActiveNetworkInfoForUid(int p0) { return null; }
    public android.net.NetworkInfo getActiveNetworkInfoForUid(int p0, boolean p1) { return null; }
    public java.util.List getAllNetworkStateSnapshots() { return new java.util.ArrayList(); }
    public boolean getBackgroundDataSetting() { return (huskFill.get("BackgroundDataSetting") instanceof Boolean ? (Boolean) huskFill.get("BackgroundDataSetting") : false); }
    public java.lang.String getCaptivePortalServerUrl() { return null; }
    public android.os.IBinder getCompanionDeviceManagerProxyService() { return null; }
    public int getConnectionOwnerUid(int p0, java.net.InetSocketAddress p1, java.net.InetSocketAddress p2) { return 0; }
    public android.net.NetworkCapabilities[] getDefaultNetworkCapabilitiesForUser(int p0) { return null; }
    public android.net.ProxyInfo getDefaultProxy() { return null; }
    public android.net.NetworkRequest getDefaultRequest() { return null; }
    public boolean getFirewallChainEnabled(int p0) { return false; }
    public android.net.ProxyInfo getGlobalProxy() { return (android.net.ProxyInfo) huskFill.get("GlobalProxy"); }
    public int getLastTetherError(java.lang.String p0) { return 0; }
    public void getLatestTetheringEntitlementResult(int p0, boolean p1, java.util.concurrent.Executor p2, android.net.ConnectivityManager.OnTetheringEntitlementResultListener p3) {}
    public android.net.LinkProperties getLinkProperties(int p0) { return null; }
    public boolean getMobileDataEnabled() { return false; }
    public int getMultipathPreference(android.net.Network p0) { return 0; }
    public android.net.Network getNetworkForType(int p0) { return null; }
    public android.net.NetworkInfo getNetworkInfoForUid(android.net.Network p0, int p1, boolean p2) { return null; }
    public int getNetworkPreference() { return (huskFill.get("NetworkPreference") instanceof Integer ? (Integer) huskFill.get("NetworkPreference") : 0); }
    public byte[] getNetworkWatchlistConfigHash() { return null; }
    public android.net.ProxyInfo getProxyForNetwork(android.net.Network p0) { return null; }
    public android.net.LinkProperties getRedactedLinkPropertiesForPackage(android.net.LinkProperties p0, int p1, java.lang.String p2) { return null; }
    public android.net.NetworkCapabilities getRedactedNetworkCapabilitiesForPackage(android.net.NetworkCapabilities p0, int p1, java.lang.String p2) { return null; }
    public android.os.IBinder getRoutingCoordinatorService() { return null; }
    public int[] getSupportedKeepalives() { return null; }
    public java.lang.String[] getTetherableBluetoothRegexs() { return null; }
    public java.lang.String[] getTetherableIfaces() { return null; }
    public java.lang.String[] getTetherableUsbRegexs() { return null; }
    public java.lang.String[] getTetherableWifiRegexs() { return null; }
    public java.lang.String[] getTetheredDhcpRanges() { return null; }
    public java.lang.String[] getTetheredIfaces() { return null; }
    public java.lang.String[] getTetheringErroredIfaces() { return null; }
    public int getUidFirewallRule(int p0, int p1) { return 0; }
    public boolean isConnectivityServiceFeatureEnabledForTesting(java.lang.String p0) { return false; }
    public boolean isFeatureEnabled(long p0) { return false; }
    public boolean isNetworkSupported(int p0) { return false; }
    public boolean isTetheringSupported() { return false; }
    public boolean isUidNetworkingBlocked(int p0, boolean p1) { return false; }
    public void registerBestMatchingNetworkCallback(android.net.NetworkRequest p0, android.net.ConnectivityManager.NetworkCallback p1, android.os.Handler p2) {}
    public void registerDefaultNetworkCallbackForUid(int p0, android.net.ConnectivityManager.NetworkCallback p1, android.os.Handler p2) { announce(null, p1, p2); }
    public void registerNetworkCallback(android.net.NetworkRequest p0, android.app.PendingIntent p1) {}
    public void registerQuicConnectionClosePayload(android.os.ParcelFileDescriptor p0, byte[] p1) {}
    public void registerSystemDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback p0, android.os.Handler p1) {}
    public void registerTetheringEventCallback(java.util.concurrent.Executor p0, android.net.ConnectivityManager.OnTetheringEventCallback p1) {}
    public void releaseNetworkRequest(android.app.PendingIntent p0) {}
    public void removeUidFromMeteredNetworkAllowList(int p0) {}
    public void removeUidFromMeteredNetworkDenyList(int p0) {}
    public void replaceFirewallChain(int p0, int[] p1) {}
    public void reportBadNetwork(android.net.Network p0) {}
    public void reportInetCondition(int p0, int p1) {}
    public void reportNetworkConnectivity(android.net.Network p0, boolean p1) {}
    public void requestBackgroundNetwork(android.net.NetworkRequest p0, android.net.ConnectivityManager.NetworkCallback p1, android.os.Handler p2) {}
    public boolean requestBandwidthUpdate(android.net.Network p0) { return false; }
    public void requestNetwork(android.net.NetworkRequest p0, int p1, int p2, android.os.Handler p3, android.net.ConnectivityManager.NetworkCallback p4) { announce(p0, p4, p3); }
    public void requestNetwork(android.net.NetworkRequest p0, android.app.PendingIntent p1) {}
    public void requestNetwork(android.net.NetworkRequest p0, android.net.ConnectivityManager.NetworkCallback p1, android.os.Handler p2) { announce(p0, p1, p2); }
    public void requestNetwork(android.net.NetworkRequest p0, android.net.ConnectivityManager.NetworkCallback p1, android.os.Handler p2, int p3) { announce(p0, p1, p2); }
    public boolean requestRouteToHost(int p0, int p1) { return false; }
    public boolean requestRouteToHostAddress(int p0, java.net.InetAddress p1) { return false; }
    public void reserveNetwork(android.net.NetworkRequest p0, android.os.Handler p1, android.net.ConnectivityManager.NetworkCallback p2) {}
    public void setAcceptPartialConnectivity(android.net.Network p0, boolean p1, boolean p2) {}
    public void setAcceptUnvalidated(android.net.Network p0, boolean p1, boolean p2) {}
    public void setAirplaneMode(boolean p0) {}
    public void setAvoidUnvalidated(android.net.Network p0) {}
    public void setBackgroundDataSetting(boolean p0) { huskFill.put("BackgroundDataSetting", Boolean.valueOf(p0)); }
    public void setDataSaverEnabled(boolean p0) {}
    public void setFirewallChainEnabled(int p0, boolean p1) {}
    public void setGlobalProxy(android.net.ProxyInfo p0) { huskFill.put("GlobalProxy", p0); }
    public void setLegacyLockdownVpnEnabled(boolean p0) {}
    public void setNetworkPreference(int p0) { huskFill.put("NetworkPreference", Integer.valueOf(p0)); }
    public void setProfileNetworkPreference(android.os.UserHandle p0, int p1, java.util.concurrent.Executor p2, java.lang.Runnable p3) {}
    public void setProfileNetworkPreferences(android.os.UserHandle p0, java.util.List p1, java.util.concurrent.Executor p2, java.lang.Runnable p3) {}
    public void setProvisioningNotificationVisible(boolean p0, int p1, java.lang.String p2) {}
    public void setRequireVpnForUids(boolean p0, java.util.Collection p1) {}
    public void setTestAllowBadWifiUntil(long p0) {}
    public void setTestLowTcpPollingTimerForKeepalive(long p0) {}
    public void setUidFirewallRule(int p0, int p1, int p2) {}
    public int setUsbTethering(boolean p0) { return 0; }
    public void setVpnDefaultForUids(java.lang.String p0, java.util.Collection p1) {}
    public boolean shouldAvoidBadWifi() { return false; }
    public void simulateDataStall(int p0, long p1, android.net.Network p2, android.os.PersistableBundle p3) {}
    public void startCaptivePortalApp(android.net.Network p0) {}
    public void startCaptivePortalApp(android.net.Network p0, android.os.Bundle p1) {}
    public android.net.ConnectivityManager.PacketKeepalive startNattKeepalive(android.net.Network p0, int p1, android.net.ConnectivityManager.PacketKeepaliveCallback p2, java.net.InetAddress p3, int p4, java.net.InetAddress p5) { return null; }
    public void startTethering(int p0, boolean p1, android.net.ConnectivityManager.OnStartTetheringCallback p2) {}
    public void startTethering(int p0, boolean p1, android.net.ConnectivityManager.OnStartTetheringCallback p2, android.os.Handler p3) {}
    public int startUsingNetworkFeature(int p0, java.lang.String p1) { return 0; }
    public void stopTethering(int p0) {}
    public int stopUsingNetworkFeature(int p0, java.lang.String p1) { return 0; }
    public void systemReady() {}
    public int tether(java.lang.String p0) { return 0; }
    public void unregisterNetworkCallback(android.app.PendingIntent p0) {}
    public void unregisterQuicConnectionClosePayload(android.os.ParcelFileDescriptor p0) {}
    public void unregisterTetheringEventCallback(android.net.ConnectivityManager.OnTetheringEventCallback p0) {}
    public int untether(java.lang.String p0) { return 0; }
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public interface Errors {
        int TOO_MANY_REQUESTS = 1;
    }
    public static class MockHelpers {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public MockHelpers() {}
        public static android.net.connectivity.android.net.NetworkAndAgentRegistryParcelable registerNetworkAgentResult(android.net.Network p0, android.net.INetworkAgentRegistry p1) { return null; }
    }
    public static class NetworkCallbackMethod {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public int mCallbacksCallingThisMethod;
        public java.lang.String mName;
        public java.lang.Class[] mParameterTypes;
        public NetworkCallbackMethod(java.lang.String p0, java.lang.Class[] p1, int p2) {}
        NetworkCallbackMethod() { this((java.lang.String) null, (java.lang.Class[]) null, (int) 0); }
    }
    public static class NetworkCallbackMethodsHolder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.net.ConnectivityManager.NetworkCallbackMethod[] NETWORK_CB_METHODS;
        public NetworkCallbackMethodsHolder() {}
    }
    public static abstract class OnStartTetheringCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public OnStartTetheringCallback() {}
        public void onTetheringFailed() {}
        public void onTetheringStarted() {}
    }
    public interface OnTetheringEntitlementResultListener {
        void onTetheringEntitlementResult(int p0);
    }
    public static abstract class OnTetheringEventCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public OnTetheringEventCallback() {}
        public void onUpstreamChanged(android.net.Network p0) {}
    }
    public static class PacketKeepalive {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int BINDER_DIED = -10;
        public static final int ERROR_HARDWARE_ERROR = -31;
        public static final int ERROR_HARDWARE_UNSUPPORTED = -30;
        public static final int ERROR_INVALID_INTERVAL = -24;
        public static final int ERROR_INVALID_IP_ADDRESS = -21;
        public static final int ERROR_INVALID_LENGTH = -23;
        public static final int ERROR_INVALID_NETWORK = -20;
        public static final int ERROR_INVALID_PORT = -22;
        public static final int MIN_INTERVAL = 10;
        public static final int NATT_PORT = 4500;
        public static final int NO_KEEPALIVE = -1;
        public static final int SUCCESS = 0;
        public void stop() {}
        protected PacketKeepalive() {}
    }
    public static class PacketKeepaliveCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public PacketKeepaliveCallback() {}
        public void onError(int p0) {}
        public void onPaused() {}
        public void onResumed() {}
        public void onStarted() {}
        public void onStopped() {}
    }
    public static class TooManyRequestsException extends java.lang.RuntimeException {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public TooManyRequestsException() { super(); }
    }
    // ---- end of generated nested classes
}
