package android.net;
public final class NetworkCapabilities implements android.os.Parcelable {
    public static final int NET_CAPABILITY_MMS = 0, NET_CAPABILITY_SUPL = 1, NET_CAPABILITY_INTERNET = 12, NET_CAPABILITY_NOT_METERED = 11, NET_CAPABILITY_NOT_RESTRICTED = 13,
        NET_CAPABILITY_TRUSTED = 14, NET_CAPABILITY_NOT_VPN = 15, NET_CAPABILITY_VALIDATED = 16, NET_CAPABILITY_CAPTIVE_PORTAL = 17, NET_CAPABILITY_NOT_ROAMING = 18,
        NET_CAPABILITY_FOREGROUND = 19, NET_CAPABILITY_NOT_CONGESTED = 20, NET_CAPABILITY_NOT_SUSPENDED = 21, NET_CAPABILITY_TEMPORARILY_NOT_METERED = 25;
    public static final int TRANSPORT_CELLULAR = 0, TRANSPORT_WIFI = 1, TRANSPORT_BLUETOOTH = 2, TRANSPORT_ETHERNET = 3, TRANSPORT_VPN = 4, TRANSPORT_WIFI_AWARE = 5, TRANSPORT_LOWPAN = 6, TRANSPORT_USB = 8;
    public boolean hasCapability(int c) { return c == NET_CAPABILITY_INTERNET || c == NET_CAPABILITY_VALIDATED || c == NET_CAPABILITY_NOT_METERED || c == NET_CAPABILITY_NOT_RESTRICTED || c == NET_CAPABILITY_TRUSTED || c == NET_CAPABILITY_NOT_VPN || c == NET_CAPABILITY_NOT_ROAMING || c == NET_CAPABILITY_FOREGROUND || c == NET_CAPABILITY_NOT_CONGESTED || c == NET_CAPABILITY_NOT_SUSPENDED; }
    public boolean hasTransport(int t) { return t == TRANSPORT_WIFI; }
    public int[] getCapabilities() { return new int[] { NET_CAPABILITY_INTERNET, NET_CAPABILITY_VALIDATED, NET_CAPABILITY_NOT_METERED }; }
    public int getLinkDownstreamBandwidthKbps() { return 100000; } public int getLinkUpstreamBandwidthKbps() { return 50000; } public int getSignalStrength() { return -50; }
    public android.net.TransportInfo getTransportInfo() { return null; }
    public int describeContents() { return 0; }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public NetworkCapabilities() {}
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final long CONNECTIVITY_MANAGED_CAPABILITIES = 17498112L;
    public static android.os.Parcelable.Creator CREATOR;
    public static final int LINK_BANDWIDTH_UNSPECIFIED = 0;
    public static final int MAX_TRANSPORT = 10;
    public static final int MIN_TRANSPORT = 0;
    public static final int NET_CAPABILITY_BIP = 31;
    public static final int NET_CAPABILITY_CBS = 5;
    public static final int NET_CAPABILITY_DUN = 2;
    public static final int NET_CAPABILITY_EIMS = 10;
    public static final int NET_CAPABILITY_ENTERPRISE = 29;
    public static final int NET_CAPABILITY_FOTA = 3;
    public static final int NET_CAPABILITY_HEAD_UNIT = 32;
    public static final int NET_CAPABILITY_IA = 7;
    public static final int NET_CAPABILITY_IMS = 4;
    public static final int NET_CAPABILITY_LOCAL_NETWORK = 36;
    public static final int NET_CAPABILITY_MCX = 23;
    public static final int NET_CAPABILITY_MMTEL = 33;
    public static final int NET_CAPABILITY_NOT_BANDWIDTH_CONSTRAINED = 37;
    public static final int NET_CAPABILITY_NOT_VCN_MANAGED = 28;
    public static final int NET_CAPABILITY_OEM_PAID = 22;
    public static final int NET_CAPABILITY_OEM_PRIVATE = 26;
    public static final int NET_CAPABILITY_PARTIAL_CONNECTIVITY = 24;
    public static final int NET_CAPABILITY_PRIORITIZE_BANDWIDTH = 35;
    public static final int NET_CAPABILITY_PRIORITIZE_LATENCY = 34;
    public static final int NET_CAPABILITY_RCS = 8;
    public static final int NET_CAPABILITY_VEHICLE_INTERNAL = 27;
    public static final int NET_CAPABILITY_VSIM = 30;
    public static final int NET_CAPABILITY_WIFI_P2P = 6;
    public static final int NET_CAPABILITY_XCAP = 9;
    public static final int NET_ENTERPRISE_ID_1 = 1;
    public static final int NET_ENTERPRISE_ID_2 = 2;
    public static final int NET_ENTERPRISE_ID_3 = 3;
    public static final int NET_ENTERPRISE_ID_4 = 4;
    public static final int NET_ENTERPRISE_ID_5 = 5;
    public static final long REDACT_ALL = -1L;
    public static final long REDACT_FOR_ACCESS_FINE_LOCATION = 1L;
    public static final long REDACT_FOR_LOCAL_MAC_ADDRESS = 2L;
    public static final long REDACT_FOR_NETWORK_SETTINGS = 4L;
    public static final long REDACT_FOR_THREAD_NETWORK_PRIVILEGED = 8L;
    public static final long REDACT_NONE = 0L;
    public static final int RES_ID_MATCH_ALL_RESERVATIONS = -1;
    public static final int RES_ID_UNSET = 0;
    public static final int SIGNAL_STRENGTH_UNSPECIFIED = -2147483648;
    public static final int TRANSPORT_SATELLITE = 10;
    public static final int TRANSPORT_TEST = 7;
    public static final int TRANSPORT_THREAD = 9;
    public NetworkCapabilities(android.net.NetworkCapabilities p0) { this(); }
    public NetworkCapabilities(android.net.NetworkCapabilities p0, long p1) { this(); }
    public static java.lang.String capabilityNameOf(int p0) { return null; }
    public static java.lang.String capabilityNamesOf(int[] p0) { return null; }
    public static java.lang.String getCapabilityCarrierName(int p0) { return null; }
    public static boolean isValidTransport(int p0) { return false; }
    public static int maxBandwidth(int p0, int p1) { return 0; }
    public static int minBandwidth(int p0, int p1) { return 0; }
    public static java.lang.String transportNameOf(int p0) { return null; }
    public static java.lang.String transportNamesOf(int[] p0) { return null; }
    public boolean appliesToUid(int p0) { return false; }
    public void clearAll() {}
    public java.lang.String describeCapsDifferencesFrom(android.net.NetworkCapabilities p0) { return null; }
    public java.lang.String describeFirstNonRequestableCapability() { return null; }
    public java.lang.String describeImmutableDifferences(android.net.NetworkCapabilities p0) { return null; }
    public boolean equalRequestableCapabilities(android.net.NetworkCapabilities p0) { return false; }
    public boolean equalsAdministratorUids(android.net.NetworkCapabilities p0) { return false; }
    public boolean equalsNetCapabilities(android.net.NetworkCapabilities p0) { return false; }
    public boolean equalsSSID(android.net.NetworkCapabilities p0) { return false; }
    public boolean equalsTransportTypes(android.net.NetworkCapabilities p0) { return false; }
    public boolean equalsUids(android.net.NetworkCapabilities p0) { return false; }
    public int[] getAdministratorUids() { return null; }
    public java.util.Set getAllowedUids() { return new java.util.HashSet(); }
    public android.util.ArraySet getAllowedUidsNoCopy() { return null; }
    public long getApplicableRedactions() { return 0L; }
    public long getCapabilitiesInternal() { return 0L; }
    public int[] getEnterpriseIds() { return null; }
    public int getEnterpriseIdsInternal() { return 0; }
    public int[] getForbiddenCapabilities() { return null; }
    public boolean getMatchNonThreadLocalNetworks() { return (huskFill.get("MatchNonThreadLocalNetworks") instanceof Boolean ? (Boolean) huskFill.get("MatchNonThreadLocalNetworks") : false); }
    public android.net.NetworkSpecifier getNetworkSpecifier() { return null; }
    public int getOwnerUid() { return 0; }
    public java.lang.String getRequestorPackageName() { return null; }
    public int getRequestorUid() { return 0; }
    public int getReservationId() { return (huskFill.get("ReservationId") instanceof Integer ? (Integer) huskFill.get("ReservationId") : 0); }
    public java.lang.String getSsid() { return null; }
    public java.util.Set getSubscriptionIds() { return new java.util.HashSet(); }
    public int[] getTransportTypes() { return (int[]) huskFill.get("TransportTypes"); }
    public long getTransportTypesInternal() { return 0L; }
    public java.util.Set getUidRanges() { return new java.util.HashSet(); }
    public java.util.Set getUids() { return new java.util.HashSet(); }
    public java.util.List getUnderlyingNetworks() { return new java.util.ArrayList(); }
    public boolean hasAllowedUids() { return false; }
    public boolean hasConnectivityManagedCapability() { return false; }
    public boolean hasEnterpriseId(int p0) { return false; }
    public boolean hasForbiddenCapability(int p0) { return false; }
    public boolean hasSignalStrength() { return false; }
    public boolean hasSingleTransport(int p0) { return false; }
    public boolean hasSingleTransportBesidesTest(int p0) { return false; }
    public boolean isMetered() { return false; }
    public boolean isPrivateDnsBroken() { return (huskFill.get("PrivateDnsBroken") instanceof Boolean ? (Boolean) huskFill.get("PrivateDnsBroken") : false); }
    public boolean isUidWithAccess(int p0) { return false; }
    public void maybeMarkCapabilitiesRestricted() {}
    public android.net.NetworkCapabilities removeAllForbiddenCapabilities() { return this; }
    public void restrictCapabilitesForTestNetwork(int p0) {}
    public void restrictCapabilitiesForTestNetwork(int p0) {}
    public boolean satisfiedByImmutableNetworkCapabilities(android.net.NetworkCapabilities p0) { return true; }
    public boolean satisfiedByNetworkCapabilities(android.net.NetworkCapabilities p0) { return true; }
    public boolean satisfiedBySSID(android.net.NetworkCapabilities p0) { return true; }
    public boolean satisfiedByUids(android.net.NetworkCapabilities p0) { return true; }
    public void set(android.net.NetworkCapabilities p0) {}
    public void setCapabilities(int[] p0) {}
    public void setCapabilities(int[] p0, int[] p1) {}
    public android.net.NetworkCapabilities setCapability(int p0, boolean p1) { return this; }
    public void setMatchNonThreadLocalNetworks(boolean p0) { huskFill.put("MatchNonThreadLocalNetworks", Boolean.valueOf(p0)); }
    public void setPrivateDnsBroken(boolean p0) { huskFill.put("PrivateDnsBroken", Boolean.valueOf(p0)); }
    public android.net.NetworkCapabilities setRequestorUidAndPackageName(int p0, java.lang.String p1) { return this; }
    public void setReservationId(int p0) { huskFill.put("ReservationId", Integer.valueOf(p0)); }
    public android.net.NetworkCapabilities setSSID(java.lang.String p0) { return this; }
    public android.net.NetworkCapabilities setSingleUid(int p0) { return this; }
    public android.net.NetworkCapabilities setTransportType(int p0, boolean p1) { return this; }
    public void setTransportTypes(int[] p0) { huskFill.put("TransportTypes", p0); }
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public static final class Builder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Builder() {}
        public Builder(android.net.NetworkCapabilities p0) {}
        public static android.net.NetworkCapabilities.Builder withoutDefaultCapabilities() { return new Builder(); }
        public android.net.NetworkCapabilities.Builder addCapability(int p0) { return this; }
        public android.net.NetworkCapabilities.Builder addEnterpriseId(int p0) { return this; }
        public android.net.NetworkCapabilities.Builder addForbiddenCapability(int p0) { return this; }
        public android.net.NetworkCapabilities.Builder addTransportType(int p0) { return this; }
        public android.net.NetworkCapabilities build() { return null; }
        public android.net.NetworkCapabilities.Builder removeCapability(int p0) { return this; }
        public android.net.NetworkCapabilities.Builder removeEnterpriseId(int p0) { return this; }
        public android.net.NetworkCapabilities.Builder removeForbiddenCapability(int p0) { return this; }
        public android.net.NetworkCapabilities.Builder removeTransportType(int p0) { return this; }
        public android.net.NetworkCapabilities.Builder setAdministratorUids(int[] p0) { huskProps.put("AdministratorUids", p0); return this; }
        public android.net.NetworkCapabilities.Builder setAllowedUids(java.util.Set p0) { huskProps.put("AllowedUids", p0); return this; }
        public android.net.NetworkCapabilities.Builder setLinkDownstreamBandwidthKbps(int p0) { huskProps.put("LinkDownstreamBandwidthKbps", Integer.valueOf(p0)); return this; }
        public android.net.NetworkCapabilities.Builder setLinkUpstreamBandwidthKbps(int p0) { huskProps.put("LinkUpstreamBandwidthKbps", Integer.valueOf(p0)); return this; }
        public android.net.NetworkCapabilities.Builder setNetworkSpecifier(android.net.NetworkSpecifier p0) { huskProps.put("NetworkSpecifier", p0); return this; }
        public android.net.NetworkCapabilities.Builder setOwnerUid(int p0) { huskProps.put("OwnerUid", Integer.valueOf(p0)); return this; }
        public android.net.NetworkCapabilities.Builder setRequestorPackageName(java.lang.String p0) { huskProps.put("RequestorPackageName", p0); return this; }
        public android.net.NetworkCapabilities.Builder setRequestorUid(int p0) { huskProps.put("RequestorUid", Integer.valueOf(p0)); return this; }
        public android.net.NetworkCapabilities.Builder setSignalStrength(int p0) { huskProps.put("SignalStrength", Integer.valueOf(p0)); return this; }
        public android.net.NetworkCapabilities.Builder setSsid(java.lang.String p0) { huskProps.put("Ssid", p0); return this; }
        public android.net.NetworkCapabilities.Builder setSubscriptionIds(java.util.Set p0) { huskProps.put("SubscriptionIds", p0); return this; }
        public android.net.NetworkCapabilities.Builder setTransportInfo(android.net.TransportInfo p0) { huskProps.put("TransportInfo", p0); return this; }
        public android.net.NetworkCapabilities.Builder setUids(java.util.Set p0) { huskProps.put("Uids", p0); return this; }
        public android.net.NetworkCapabilities.Builder setUnderlyingNetworks(java.util.List p0) { huskProps.put("UnderlyingNetworks", p0); return this; }
    }
    public static final class RedactionHelper {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static long getSpecifierApplicableRedactions(android.net.NetworkSpecifier p0) { return 0L; }
        public static android.net.NetworkSpecifier getSpecifierRedactResult(android.net.NetworkSpecifier p0, long p1) { return null; }
        protected RedactionHelper() {}
    }
    // ---- end of generated nested classes
}
