package android.net;
public class NetworkRequest implements android.os.Parcelable {
    public int describeContents() { return 0; }
    /* what the request asks for; a network satisfies it when it has every capability, none forbidden, and one of the transports */
    final java.util.TreeSet<Integer> mCaps = new java.util.TreeSet<>(), mForbidden = new java.util.TreeSet<>(), mTransports = new java.util.TreeSet<>();
    public boolean hasCapability(int c) { return mCaps.contains(c); } public boolean hasTransport(int t) { return mTransports.contains(t); }
    public boolean hasForbiddenCapability(int c) { return mForbidden.contains(c); }
    private static int[] arr(java.util.Set<Integer> s) { int[] r = new int[s.size()]; int i = 0; for (int v : s) r[i++] = v; return r; }
    public int[] getCapabilities() { return arr(mCaps); }
    public int[] getForbiddenCapabilities() { return arr(mForbidden); }
    public int[] getTransportTypes() { return arr(mTransports); }
    public boolean canBeSatisfiedBy(NetworkCapabilities nc) {
        if (nc == null) return false;
        for (int c : mCaps) if (!nc.hasCapability(c)) return false;
        for (int c : mForbidden) if (nc.hasCapability(c)) return false;
        if (mTransports.isEmpty()) return true;
        for (int t : mTransports) if (nc.hasTransport(t)) return true;
        return false;
    }
    @Override public String toString() { return "NetworkRequest [ caps " + mCaps + " transports " + mTransports + " ]"; }
    public static class Builder {
        private final NetworkRequest r = new NetworkRequest();
        public Builder() { r.mCaps.add(NetworkCapabilities.NET_CAPABILITY_INTERNET); r.mCaps.add(NetworkCapabilities.NET_CAPABILITY_NOT_RESTRICTED); r.mCaps.add(NetworkCapabilities.NET_CAPABILITY_TRUSTED); r.mCaps.add(NetworkCapabilities.NET_CAPABILITY_NOT_VPN); }
        public Builder(NetworkRequest o) { r.mCaps.addAll(o.mCaps); r.mForbidden.addAll(o.mForbidden); r.mTransports.addAll(o.mTransports); }
        public Builder addCapability(int c) { r.mCaps.add(c); r.mForbidden.remove(c); return this; }
        public Builder removeCapability(int c) { r.mCaps.remove(c); return this; }
        public Builder addForbiddenCapability(int c) { r.mForbidden.add(c); r.mCaps.remove(c); return this; }
        public Builder removeForbiddenCapability(int c) { r.mForbidden.remove(c); return this; }
        public Builder addTransportType(int t) { r.mTransports.add(t); return this; }
        public Builder removeTransportType(int t) { r.mTransports.remove(t); return this; }
        public Builder clearCapabilities() { r.mCaps.clear(); r.mForbidden.clear(); r.mTransports.clear(); return this; }
        public NetworkRequest build() { NetworkRequest n = new NetworkRequest(); n.mCaps.addAll(r.mCaps); n.mForbidden.addAll(r.mForbidden); n.mTransports.addAll(r.mTransports); return n; }
        // ---- generated by tools/compat/fillmembers.py (Builder): the platform's members this class does not write (signatures only)
        public android.net.NetworkRequest.Builder setCapabilities(android.net.NetworkCapabilities p0) { return this; }
        public android.net.NetworkRequest.Builder setIncludeOtherUidNetworks(boolean p0) { return this; }
        public android.net.NetworkRequest.Builder setLinkDownstreamBandwidthKbps(int p0) { return this; }
        public android.net.NetworkRequest.Builder setLinkUpstreamBandwidthKbps(int p0) { return this; }
        public android.net.NetworkRequest.Builder setNetworkSpecifier(android.net.NetworkSpecifier p0) { return this; }
        public android.net.NetworkRequest.Builder setNetworkSpecifier(java.lang.String p0) { return this; }
        public android.net.NetworkRequest.Builder setSignalStrength(int p0) { return this; }
        public android.net.NetworkRequest.Builder setSubscriptionIds(java.util.Set p0) { return this; }
        public android.net.NetworkRequest.Builder setUids(java.util.Set p0) { return this; }
        // ---- end of generated members (Builder)
    }
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    public NetworkRequest() {}
    public static android.os.Parcelable.Creator CREATOR;
    public static final int FIRST_REQUEST_ID = 1;
    public static final int REQUEST_ID_NONE = -1;
    public int legacyType;
    public android.net.NetworkCapabilities networkCapabilities;
    public int requestId;
    public android.net.NetworkRequest.Type type;
    public NetworkRequest(android.net.NetworkCapabilities p0, int p1, int p2, android.net.NetworkRequest.Type p3) { this(); }
    public NetworkRequest(android.net.NetworkRequest p0) { this(); mCaps.addAll(p0.mCaps); mForbidden.addAll(p0.mForbidden); mTransports.addAll(p0.mTransports); }
    public int[] getEnterpriseIds() { return null; }
    public android.net.NetworkSpecifier getNetworkSpecifier() { return null; }
    public java.lang.String getRequestorPackageName() { return null; }
    public int getRequestorUid() { return 0; }
    public java.util.Set getSubscriptionIds() { return new java.util.HashSet(); }
    public boolean hasEnterpriseId(int p0) { return false; }
    public boolean isBackgroundRequest() { return false; }
    public boolean isListen() { return false; }
    public boolean isListenForBest() { return false; }
    public boolean isRequest() { return false; }
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public enum Type {
        BACKGROUND_REQUEST, LISTEN, LISTEN_FOR_BEST, NONE, REQUEST, RESERVATION, TRACK_DEFAULT, TRACK_SYSTEM_DEFAULT;
    }
    // ---- end of generated nested classes
}
