// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.autofill;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class AutofillService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String EXTRA_ERROR = "error";
    public static final java.lang.String EXTRA_FILL_RESPONSE = "android.service.autofill.extra.FILL_RESPONSE";
    public static final java.lang.String EXTRA_RESULT = "result";
    public static final java.lang.String SERVICE_INTERFACE = "android.service.autofill.AutofillService";
    public static final java.lang.String SERVICE_META_DATA = "android.autofill";
    public static final java.lang.String WEBVIEW_REQUESTED_CREDENTIAL_KEY = "webview_requested_credential";
    public AutofillService() { super(); }
    public android.service.autofill.FillEventHistory getFillEventHistory() { return (android.service.autofill.FillEventHistory) huskProps.get("FillEventHistory"); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onConnected() {}
    public void onConvertCredentialRequest(android.service.autofill.ConvertCredentialRequest p0, android.service.autofill.ConvertCredentialCallback p1) {}
    public void onDisconnected() {}
    public void onFillCredentialRequest(android.service.autofill.FillRequest p0, android.os.CancellationSignal p1, android.service.autofill.FillCallback p2, android.os.IBinder p3) {}
    public abstract void onFillRequest(android.service.autofill.FillRequest p0, android.os.CancellationSignal p1, android.service.autofill.FillCallback p2);
    public abstract void onSaveRequest(android.service.autofill.SaveRequest p0, android.service.autofill.SaveCallback p1);
    public void onSavedDatasetsInfoRequest(android.service.autofill.SavedDatasetsInfoCallback p0) {}
    public void onSessionDestroyed(android.service.autofill.FillEventHistory p0) {}
}
