// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.credentials;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class CredentialProviderService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String EXTRA_AUTOFILL_ID = "android.service.credentials.extra.AUTOFILL_ID";
    public static final java.lang.String EXTRA_BEGIN_GET_CREDENTIAL_REQUEST = "android.service.credentials.extra.BEGIN_GET_CREDENTIAL_REQUEST";
    public static final java.lang.String EXTRA_BEGIN_GET_CREDENTIAL_RESPONSE = "android.service.credentials.extra.BEGIN_GET_CREDENTIAL_RESPONSE";
    public static final java.lang.String EXTRA_CREATE_CREDENTIAL_EXCEPTION = "android.service.credentials.extra.CREATE_CREDENTIAL_EXCEPTION";
    public static final java.lang.String EXTRA_CREATE_CREDENTIAL_REQUEST = "android.service.credentials.extra.CREATE_CREDENTIAL_REQUEST";
    public static final java.lang.String EXTRA_CREATE_CREDENTIAL_RESPONSE = "android.service.credentials.extra.CREATE_CREDENTIAL_RESPONSE";
    public static final java.lang.String EXTRA_GET_CREDENTIAL_EXCEPTION = "android.service.credentials.extra.GET_CREDENTIAL_EXCEPTION";
    public static final java.lang.String EXTRA_GET_CREDENTIAL_REQUEST = "android.service.credentials.extra.GET_CREDENTIAL_REQUEST";
    public static final java.lang.String EXTRA_GET_CREDENTIAL_RESPONSE = "android.service.credentials.extra.GET_CREDENTIAL_RESPONSE";
    public static final java.lang.String SERVICE_INTERFACE = "android.service.credentials.CredentialProviderService";
    public static final java.lang.String SERVICE_META_DATA = "android.credentials.provider";
    public static final java.lang.String SYSTEM_SERVICE_INTERFACE = "android.service.credentials.system.CredentialProviderService";
    public static final java.lang.String TEST_SYSTEM_PROVIDER_META_DATA_KEY = "android.credentials.testsystemprovider";
    public CredentialProviderService() { super(); }
    public abstract void onBeginCreateCredential(android.service.credentials.BeginCreateCredentialRequest p0, android.os.CancellationSignal p1, android.os.OutcomeReceiver p2);
    public abstract void onBeginGetCredential(android.service.credentials.BeginGetCredentialRequest p0, android.os.CancellationSignal p1, android.os.OutcomeReceiver p2);
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract void onClearCredentialState(android.service.credentials.ClearCredentialStateRequest p0, android.os.CancellationSignal p1, android.os.OutcomeReceiver p2);
}
