// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.appwidget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class AppWidgetHostView extends android.widget.FrameLayout implements android.appwidget.AppWidgetHost.AppWidgetHostListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public AppWidgetHostView(android.content.Context p0) { super(p0); }
    public AppWidgetHostView(android.content.Context p0, int p1, int p2) { super((android.content.Context) null); }
    public AppWidgetHostView(android.content.Context p0, android.widget.RemoteViews.InteractionHandler p1) { super((android.content.Context) null); }
    public static android.graphics.Rect getDefaultPaddingForWidget(android.content.Context p0, android.content.ComponentName p1, android.graphics.Rect p2) { return null; }
    protected void applyRemoteViews(android.widget.RemoteViews p0, boolean p1) {}
    public android.appwidget.AppWidgetEvent collectWidgetEvent() { return null; }
    public android.app.ActivityOptions createSharedElementActivityOptions(int[] p0, java.lang.String[] p1, android.content.Intent p2) { return null; }
    public void dispatchDraw(android.graphics.Canvas p0) {}
    public void dispatchRestoreInstanceState(android.util.SparseArray p0) {}
    public void dispatchSaveInstanceState(android.util.SparseArray p0) {}
    public android.widget.FrameLayout.LayoutParams generateLayoutParams(android.content.Context p0, android.util.AttributeSet p1) { return null; }
    public int getAppWidgetId() { return (huskProps.get("AppWidgetId") instanceof Integer ? (Integer) huskProps.get("AppWidgetId") : 0); }
    public android.appwidget.AppWidgetProviderInfo getAppWidgetInfo() { return (android.appwidget.AppWidgetProviderInfo) huskProps.get("AppWidgetInfo"); }
    protected android.view.View getDefaultView() { return (android.view.View) huskProps.get("DefaultView"); }
    protected android.view.View getErrorView() { return (android.view.View) huskProps.get("ErrorView"); }
    public android.appwidget.AppWidgetHostView.InteractionLogger getInteractionLogger() { return (android.appwidget.AppWidgetHostView.InteractionLogger) huskProps.get("InteractionLogger"); }
    protected boolean isVisibilityTrackingPermitted() { return (huskProps.get("VisibilityTrackingPermitted") instanceof Boolean ? (Boolean) huskProps.get("VisibilityTrackingPermitted") : false); }
    protected void onDefaultViewClicked(android.view.View p0) {}
    public void onInitializeAccessibilityNodeInfoInternal(android.view.accessibility.AccessibilityNodeInfo p0) {}
    public void onUpdateProviderInfo(android.appwidget.AppWidgetProviderInfo p0) {}
    public void onViewDataChanged(int p0) {}
    public void onVisibilityAggregated(boolean p0) {}
    public void onWindowFocusChanged(boolean p0) {}
    protected void prepareView(android.view.View p0) {}
    public void resetColorResources() {}
    public void setAppWidget(int p0, android.appwidget.AppWidgetProviderInfo p1) {}
    public void setColorResources(android.util.SparseIntArray p0) { huskProps.put("ColorResources", p0); }
    public void setColorResources(android.widget.RemoteViews.ColorResources p0) { huskProps.put("ColorResources", p0); }
    public void setColorResourcesNoReapply(android.widget.RemoteViews.ColorResources p0) { huskProps.put("ColorResourcesNoReapply", p0); }
    public void setExecutor(java.util.concurrent.Executor p0) { huskProps.put("Executor", p0); }
    public void setInteractionHandler(android.widget.RemoteViews.InteractionHandler p0) { huskProps.put("InteractionHandler", p0); }
    public void setOnLightBackground(boolean p0) { huskProps.put("OnLightBackground", Boolean.valueOf(p0)); }
    public void startVisibilityTracking() {}
    public void stopVisibilityTracking() {}
    public void updateAppWidget(android.widget.RemoteViews p0) {}
    public void updateAppWidgetOptions(android.os.Bundle p0) {}
    public void updateAppWidgetSize(android.os.Bundle p0, int p1, int p2, int p3, int p4) {}
    public void updateAppWidgetSize(android.os.Bundle p0, int p1, int p2, int p3, int p4, boolean p5) {}
    public void updateAppWidgetSize(android.os.Bundle p0, java.util.List p1) {}
    AppWidgetHostView() { this((android.content.Context) null); }
    public static class AdapterChildHostView extends android.appwidget.AppWidgetHostView {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public AdapterChildHostView(android.content.Context p0) { super(p0); }
        public boolean isVisibilityTrackingPermitted() { return (huskProps.get("VisibilityTrackingPermitted") instanceof Boolean ? (Boolean) huskProps.get("VisibilityTrackingPermitted") : false); }
        AdapterChildHostView() { this((android.content.Context) null); }
    }
    public static class InteractionLogger implements android.widget.RemoteViews.InteractionHandler {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public android.appwidget.AppWidgetEvent getEvent() { return (android.appwidget.AppWidgetEvent) huskProps.get("Event"); }
        public boolean onInteraction(android.view.View p0, android.app.PendingIntent p1, android.widget.RemoteViews.RemoteResponse p2) { return false; }
        public void onScroll(android.widget.AbsListView p0) {}
        protected InteractionLogger() {}
    }
}
