// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.notification;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class NotificationListenerService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String ACTION_SETTINGS_HOME = "android.service.notification.action.SETTINGS_HOME";
    public static final int FLAG_FILTER_TYPE_ALERTING = 2;
    public static final int FLAG_FILTER_TYPE_CONVERSATIONS = 1;
    public static final int FLAG_FILTER_TYPE_ONGOING = 8;
    public static final int FLAG_FILTER_TYPE_SILENT = 4;
    public static final int HINT_HOST_DISABLE_CALL_EFFECTS = 4;
    public static final int HINT_HOST_DISABLE_EFFECTS = 1;
    public static final int HINT_HOST_DISABLE_NOTIFICATION_EFFECTS = 2;
    public static final int INTERRUPTION_FILTER_ALARMS = 4;
    public static final int INTERRUPTION_FILTER_ALL = 1;
    public static final int INTERRUPTION_FILTER_NONE = 3;
    public static final int INTERRUPTION_FILTER_PRIORITY = 2;
    public static final int INTERRUPTION_FILTER_UNKNOWN = 0;
    public static final java.lang.String META_DATA_DEFAULT_AUTOBIND = "android.service.notification.default_autobind_listenerservice";
    public static final java.lang.String META_DATA_DEFAULT_FILTER_TYPES = "android.service.notification.default_filter_types";
    public static final java.lang.String META_DATA_DISABLED_FILTER_TYPES = "android.service.notification.disabled_filter_types";
    public static final int NOTIFICATION_CHANNEL_OR_GROUP_ADDED = 1;
    public static final int NOTIFICATION_CHANNEL_OR_GROUP_DELETED = 3;
    public static final int NOTIFICATION_CHANNEL_OR_GROUP_UPDATED = 2;
    public static final int REASON_APP_CANCEL = 8;
    public static final int REASON_APP_CANCEL_ALL = 9;
    public static final int REASON_ASSISTANT_CANCEL = 22;
    public static final int REASON_BUNDLE_DISMISSED = 24;
    public static final int REASON_CANCEL = 2;
    public static final int REASON_CANCEL_ALL = 3;
    public static final int REASON_CHANNEL_BANNED = 17;
    public static final int REASON_CHANNEL_REMOVED = 20;
    public static final int REASON_CLEAR_DATA = 21;
    public static final int REASON_CLICK = 1;
    public static final int REASON_ERROR = 4;
    public static final int REASON_GROUP_OPTIMIZATION = 13;
    public static final int REASON_GROUP_SUMMARY_CANCELED = 12;
    public static final int REASON_LISTENER_CANCEL = 10;
    public static final int REASON_LISTENER_CANCEL_ALL = 11;
    public static final int REASON_LOCKDOWN = 23;
    public static final int REASON_PACKAGE_BANNED = 7;
    public static final int REASON_PACKAGE_CHANGED = 5;
    public static final int REASON_PACKAGE_SUSPENDED = 14;
    public static final int REASON_PROFILE_TURNED_OFF = 15;
    public static final int REASON_SNOOZED = 18;
    public static final int REASON_TIMEOUT = 19;
    public static final int REASON_UNAUTOBUNDLED = 16;
    public static final int REASON_USER_STOPPED = 6;
    public static final java.lang.String SERVICE_INTERFACE = "android.service.notification.NotificationListenerService";
    public static final int SUPPRESSED_EFFECT_SCREEN_OFF = 1;
    public static final int SUPPRESSED_EFFECT_SCREEN_ON = 2;
    public static final int TRIM_FULL = 0;
    public static final int TRIM_LIGHT = 1;
    protected int mCurrentUser;
    protected android.app.INotificationManager mNoMan;
    protected android.content.Context mSystemContext;
    protected android.service.notification.NotificationListenerService.NotificationListenerWrapper mWrapper;
    public NotificationListenerService() { super(); }
    public static void requestRebind(android.content.ComponentName p0) {}
    public static void requestUnbind(android.content.ComponentName p0) {}
    public void applyUpdateLocked(android.service.notification.NotificationRankingUpdate p0) {}
    public void cancelAllNotifications() {}
    public void cancelNotification(java.lang.String p0) {}
    public void cancelNotification(java.lang.String p0, java.lang.String p1, int p2) {}
    public void cancelNotifications(java.lang.String[] p0) {}
    public void clearRequestedListenerHints() {}
    public android.app.NotificationChannel createConversationNotificationChannelForPackage(java.lang.String p0, android.os.UserHandle p1, java.lang.String p2, java.lang.String p3) { return null; }
    public void createLegacyIconExtras(android.app.Notification p0) {}
    public android.service.notification.StatusBarNotification[] getActiveNotifications() { return (android.service.notification.StatusBarNotification[]) huskProps.get("ActiveNotifications"); }
    public android.service.notification.StatusBarNotification[] getActiveNotifications(int p0) { return null; }
    public android.service.notification.StatusBarNotification[] getActiveNotifications(java.lang.String[] p0) { return null; }
    public android.service.notification.StatusBarNotification[] getActiveNotifications(java.lang.String[] p0, int p1) { return null; }
    protected android.content.Context getContext() { return (android.content.Context) huskProps.get("Context"); }
    public int getCurrentInterruptionFilter() { return (huskProps.get("CurrentInterruptionFilter") instanceof Integer ? (Integer) huskProps.get("CurrentInterruptionFilter") : 0); }
    public int getCurrentListenerHints() { return (huskProps.get("CurrentListenerHints") instanceof Integer ? (Integer) huskProps.get("CurrentListenerHints") : 0); }
    public android.service.notification.NotificationListenerService.RankingMap getCurrentRanking() { return (android.service.notification.NotificationListenerService.RankingMap) huskProps.get("CurrentRanking"); }
    public android.os.Handler getHandler() { return (android.os.Handler) huskProps.get("Handler"); }
    public java.util.List getNotificationChannelGroups(java.lang.String p0, android.os.UserHandle p1) { return new java.util.ArrayList(); }
    public java.util.List getNotificationChannels(java.lang.String p0, android.os.UserHandle p1) { return new java.util.ArrayList(); }
    protected android.app.INotificationManager getNotificationInterface() { return (android.app.INotificationManager) huskProps.get("NotificationInterface"); }
    public android.service.notification.StatusBarNotification[] getSnoozedNotifications() { return (android.service.notification.StatusBarNotification[]) huskProps.get("SnoozedNotifications"); }
    protected boolean isBound() { return (huskProps.get("Bound") instanceof Boolean ? (Boolean) huskProps.get("Bound") : false); }
    public void migrateNotificationFilter(int p0, java.util.List p1) {}
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onInterruptionFilterChanged(int p0) {}
    public void onListenerConnected() {}
    public void onListenerDisconnected() {}
    public void onListenerHintsChanged(int p0) {}
    public void onNotificationChannelGroupModified(java.lang.String p0, android.os.UserHandle p1, android.app.NotificationChannelGroup p2, int p3) {}
    public void onNotificationChannelModified(java.lang.String p0, android.os.UserHandle p1, android.app.NotificationChannel p2, int p3) {}
    public void onNotificationPosted(android.service.notification.StatusBarNotification p0) {}
    public void onNotificationPosted(android.service.notification.StatusBarNotification p0, android.service.notification.NotificationListenerService.RankingMap p1) {}
    public void onNotificationRankingUpdate(android.service.notification.NotificationListenerService.RankingMap p0) {}
    public void onNotificationRemoved(android.service.notification.StatusBarNotification p0) {}
    public void onNotificationRemoved(android.service.notification.StatusBarNotification p0, android.service.notification.NotificationListenerService.RankingMap p1) {}
    public void onNotificationRemoved(android.service.notification.StatusBarNotification p0, android.service.notification.NotificationListenerService.RankingMap p1, int p2) {}
    public void onNotificationRemoved(android.service.notification.StatusBarNotification p0, android.service.notification.NotificationListenerService.RankingMap p1, android.service.notification.NotificationStats p2, int p3) {}
    public void onSilentStatusBarIconsVisibilityChanged(boolean p0) {}
    public void registerAsSystemService(android.content.Context p0, android.content.ComponentName p1, int p2) {}
    public void requestInterruptionFilter(int p0) {}
    public void requestListenerHints(int p0) {}
    public void requestUnbind() {}
    public void setNotificationsShown(java.lang.String[] p0) { huskProps.put("NotificationsShown", p0); }
    public void setOnNotificationPostedTrim(int p0) { huskProps.put("OnNotificationPostedTrim", Integer.valueOf(p0)); }
    public void snoozeNotification(java.lang.String p0, long p1) {}
    public void snoozeNotification(java.lang.String p0, java.lang.String p1) {}
    public void unregisterAsSystemService() {}
    public void updateNotificationChannel(java.lang.String p0, android.os.UserHandle p1, android.app.NotificationChannel p2) {}
    public static abstract class NotificationListenerWrapper extends android.service.notification.INotificationListener.Stub {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        protected NotificationListenerWrapper(android.service.notification.NotificationListenerService p0) { super(); }
        public void onActionClicked(java.lang.String p0, android.app.Notification.Action p1, int p2) {}
        public void onAllowedAdjustmentsChanged() {}
        public void onInterruptionFilterChanged(int p0, long p1) {}
        public void onListenerConnected(android.service.notification.NotificationRankingUpdate p0, android.service.notification.IDispatchCompletionListener p1, long p2) {}
        public void onListenerHintsChanged(int p0, long p1) {}
        public void onNotificationChannelGroupModification(java.lang.String p0, android.os.UserHandle p1, android.app.NotificationChannelGroup p2, int p3, long p4) {}
        public void onNotificationChannelModification(java.lang.String p0, android.os.UserHandle p1, android.app.NotificationChannel p2, int p3, long p4) {}
        public void onNotificationClicked(java.lang.String p0) {}
        public void onNotificationDirectReply(java.lang.String p0) {}
        public void onNotificationEnqueuedWithChannel(android.service.notification.IStatusBarNotificationHolder p0, android.app.NotificationChannel p1, android.service.notification.NotificationRankingUpdate p2) {}
        public void onNotificationEnqueuedWithChannelFull(android.service.notification.StatusBarNotification p0, android.app.NotificationChannel p1, android.service.notification.NotificationRankingUpdate p2) {}
        public void onNotificationExpansionChanged(java.lang.String p0, boolean p1, boolean p2) {}
        public void onNotificationFeedbackReceived(java.lang.String p0, android.service.notification.NotificationRankingUpdate p1, android.os.Bundle p2) {}
        public void onNotificationPosted(android.service.notification.IStatusBarNotificationHolder p0, android.service.notification.NotificationRankingUpdate p1, long p2) {}
        public void onNotificationPostedFull(android.service.notification.StatusBarNotification p0, android.service.notification.NotificationRankingUpdate p1, long p2) {}
        public void onNotificationRankingUpdate(android.service.notification.NotificationRankingUpdate p0, long p1) {}
        public void onNotificationRemoved(android.service.notification.IStatusBarNotificationHolder p0, android.service.notification.NotificationRankingUpdate p1, android.service.notification.NotificationStats p2, int p3, long p4) {}
        public void onNotificationRemovedFull(android.service.notification.StatusBarNotification p0, android.service.notification.NotificationRankingUpdate p1, android.service.notification.NotificationStats p2, int p3, long p4) {}
        public void onNotificationSnoozedUntilContext(android.service.notification.IStatusBarNotificationHolder p0, java.lang.String p1) {}
        public void onNotificationSnoozedUntilContextFull(android.service.notification.StatusBarNotification p0, java.lang.String p1) {}
        public void onNotificationVisibilityChanged(java.lang.String p0, boolean p1) {}
        public void onNotificationsSeen(java.util.List p0) {}
        public void onPanelHidden() {}
        public void onPanelRevealed(int p0) {}
        public void onStatusBarIconsBehaviorChanged(boolean p0, long p1) {}
        public void onSuggestedReplySent(java.lang.String p0, java.lang.CharSequence p1, int p2) {}
        NotificationListenerWrapper() { this((android.service.notification.NotificationListenerService) null); }
    }
    public static class Ranking {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int RANKING_DEMOTED = -1;
        public static final int RANKING_PROMOTED = 1;
        public static final int RANKING_UNCHANGED = 0;
        public static final int USER_SENTIMENT_NEGATIVE = -1;
        public static final int USER_SENTIMENT_NEUTRAL = 0;
        public static final int USER_SENTIMENT_POSITIVE = 1;
        public static final int VISIBILITY_NO_OVERRIDE = -1000;
        public Ranking() {}
        public Ranking(android.os.Parcel p0) {}
        public static java.lang.String importanceToString(int p0) { return null; }
        public boolean canBubble() { return false; }
        public boolean canShowBadge() { return false; }
        public java.util.List getAdditionalPeople() { return (huskProps.get("AdditionalPeople") != null ? (java.util.List) huskProps.get("AdditionalPeople") : new java.util.ArrayList()); }
        public android.app.NotificationChannel getChannel() { return (android.app.NotificationChannel) huskProps.get("Channel"); }
        public android.content.pm.ShortcutInfo getConversationShortcutInfo() { return (android.content.pm.ShortcutInfo) huskProps.get("ConversationShortcutInfo"); }
        public int getImportance() { return (huskProps.get("Importance") instanceof Integer ? (Integer) huskProps.get("Importance") : 0); }
        public java.lang.CharSequence getImportanceExplanation() { return (java.lang.CharSequence) huskProps.get("ImportanceExplanation"); }
        public java.lang.String getKey() { return (java.lang.String) huskProps.get("Key"); }
        public long getLastAudiblyAlertedMillis() { return (huskProps.get("LastAudiblyAlertedMillis") instanceof Long ? (Long) huskProps.get("LastAudiblyAlertedMillis") : 0L); }
        public int getLockscreenVisibilityOverride() { return (huskProps.get("LockscreenVisibilityOverride") instanceof Integer ? (Integer) huskProps.get("LockscreenVisibilityOverride") : 0); }
        public java.lang.String getOverrideGroupKey() { return (java.lang.String) huskProps.get("OverrideGroupKey"); }
        public int getProposedImportance() { return (huskProps.get("ProposedImportance") instanceof Integer ? (Integer) huskProps.get("ProposedImportance") : 0); }
        public int getRank() { return (huskProps.get("Rank") instanceof Integer ? (Integer) huskProps.get("Rank") : 0); }
        public int getRankingAdjustment() { return (huskProps.get("RankingAdjustment") instanceof Integer ? (Integer) huskProps.get("RankingAdjustment") : 0); }
        public float getRankingScore() { return (huskProps.get("RankingScore") instanceof Float ? (Float) huskProps.get("RankingScore") : 0f); }
        public java.util.List getSmartActions() { return (huskProps.get("SmartActions") != null ? (java.util.List) huskProps.get("SmartActions") : new java.util.ArrayList()); }
        public java.util.List getSmartReplies() { return (huskProps.get("SmartReplies") != null ? (java.util.List) huskProps.get("SmartReplies") : new java.util.ArrayList()); }
        public java.util.List getSnoozeCriteria() { return (huskProps.get("SnoozeCriteria") != null ? (java.util.List) huskProps.get("SnoozeCriteria") : new java.util.ArrayList()); }
        public java.lang.String getSummarization() { return (java.lang.String) huskProps.get("Summarization"); }
        public int getSuppressedVisualEffects() { return (huskProps.get("SuppressedVisualEffects") instanceof Integer ? (Integer) huskProps.get("SuppressedVisualEffects") : 0); }
        public int getUserSentiment() { return (huskProps.get("UserSentiment") instanceof Integer ? (Integer) huskProps.get("UserSentiment") : 0); }
        public boolean hasSensitiveContent() { return false; }
        public boolean isAmbient() { return (huskProps.get("Ambient") instanceof Boolean ? (Boolean) huskProps.get("Ambient") : false); }
        public boolean isBubble() { return (huskProps.get("Bubble") instanceof Boolean ? (Boolean) huskProps.get("Bubble") : false); }
        public boolean isConversation() { return (huskProps.get("Conversation") instanceof Boolean ? (Boolean) huskProps.get("Conversation") : false); }
        public boolean isNoisy() { return (huskProps.get("Noisy") instanceof Boolean ? (Boolean) huskProps.get("Noisy") : false); }
        public boolean isSuspended() { return (huskProps.get("Suspended") instanceof Boolean ? (Boolean) huskProps.get("Suspended") : false); }
        public boolean isTextChanged() { return (huskProps.get("TextChanged") instanceof Boolean ? (Boolean) huskProps.get("TextChanged") : false); }
        public boolean matchesInterruptionFilter() { return false; }
        public void populate(android.service.notification.NotificationListenerService.Ranking p0) {}
        public void populate(java.lang.String p0, int p1, boolean p2, int p3, int p4, int p5, java.lang.CharSequence p6, java.lang.String p7, android.app.NotificationChannel p8, java.util.ArrayList p9, java.util.ArrayList p10, boolean p11, int p12, boolean p13, long p14, boolean p15, java.util.ArrayList p16, java.util.ArrayList p17, boolean p18, boolean p19, boolean p20, android.content.pm.ShortcutInfo p21, int p22, boolean p23, int p24, boolean p25, java.lang.String p26) {}
        public void setSmartActions(java.util.ArrayList p0) { huskProps.put("SmartActions", p0); }
        public android.service.notification.NotificationListenerService.Ranking withAudiblyAlertedInfo(android.service.notification.NotificationListenerService.Ranking p0) { return this; }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
    }
    public static class RankingMap implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public RankingMap(android.service.notification.NotificationListenerService.Ranking[] p0) {}
        public int describeContents() { return 0; }
        public java.lang.String[] getOrderedKeys() { return (java.lang.String[]) huskProps.get("OrderedKeys"); }
        public boolean getRanking(java.lang.String p0, android.service.notification.NotificationListenerService.Ranking p1) { return false; }
        public android.service.notification.NotificationListenerService.Ranking getRawRankingObject(java.lang.String p0) { return null; }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        RankingMap() { this((android.service.notification.NotificationListenerService.Ranking[]) null); }
    }
}
