// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.speech.tts;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class TextToSpeechService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public TextToSpeechService() { super(); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public java.lang.String onGetDefaultVoiceNameFor(java.lang.String p0, java.lang.String p1, java.lang.String p2) { return null; }
    protected java.util.Set onGetFeaturesForLanguage(java.lang.String p0, java.lang.String p1, java.lang.String p2) { return new java.util.HashSet(); }
    protected abstract java.lang.String[] onGetLanguage();
    public java.util.List onGetVoices() { return new java.util.ArrayList(); }
    protected abstract int onIsLanguageAvailable(java.lang.String p0, java.lang.String p1, java.lang.String p2);
    public int onIsValidVoiceName(java.lang.String p0) { return 0; }
    protected abstract int onLoadLanguage(java.lang.String p0, java.lang.String p1, java.lang.String p2);
    public int onLoadVoice(java.lang.String p0) { return 0; }
    protected abstract void onStop();
    protected abstract void onSynthesizeText(android.speech.tts.SynthesisRequest p0, android.speech.tts.SynthesisCallback p1);
}
