// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.dreams;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DreamService extends android.app.Service implements android.view.Window.Callback {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String BUNDLE_KEY_ATTACH_ERROR = "android.service.dream.DreamService.attach_error";
    public static final boolean DEFAULT_SHOW_COMPLICATIONS = false;
    public static final int DREAM_CATEGORY_DEFAULT = 0;
    public static final int DREAM_CATEGORY_HOME_PANEL = 2;
    public static final int DREAM_CATEGORY_LOW_LIGHT = 1;
    public static final java.lang.String DREAM_META_DATA = "android.service.dream";
    public static final java.lang.String DREAM_SERVICE = "dreams";
    public static final java.lang.String SERVICE_INTERFACE = "android.service.dreams.DreamService";
    public DreamService() { super(); }
    public DreamService(android.service.dreams.DreamService.Injector p0) { super(); }
    public static android.service.dreams.DreamService.DreamMetadata getDreamMetadata(android.content.Context p0, android.content.pm.ServiceInfo p1) { return null; }
    public static android.service.dreams.DreamService.DreamMetadata getDreamMetadata(android.content.pm.PackageManager p0, android.content.pm.ServiceInfo p1) { return null; }
    public static void setDreamOverlayComponent(android.content.Intent p0, android.content.ComponentName p1) {}
    public void addContentView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public boolean canDoze() { return false; }
    public boolean dispatchGenericMotionEvent(android.view.MotionEvent p0) { return false; }
    public boolean dispatchKeyEvent(android.view.KeyEvent p0) { return false; }
    public boolean dispatchKeyShortcutEvent(android.view.KeyEvent p0) { return false; }
    public boolean dispatchPopulateAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0) { return false; }
    public boolean dispatchTouchEvent(android.view.MotionEvent p0) { return false; }
    public boolean dispatchTrackballEvent(android.view.MotionEvent p0) { return false; }
    protected void dumpOnHandler(java.io.FileDescriptor p0, java.io.PrintWriter p1, java.lang.String[] p2) {}
    public android.view.View findViewById(int p0) { return null; }
    public void finish() {}
    public android.app.Activity getActivity() { return (android.app.Activity) huskProps.get("Activity"); }
    public float getDozeScreenBrightness() { return (huskProps.get("DozeScreenBrightness") instanceof Float ? (Float) huskProps.get("DozeScreenBrightness") : 0f); }
    public int getDozeScreenState() { return (huskProps.get("DozeScreenState") instanceof Integer ? (Integer) huskProps.get("DozeScreenState") : 0); }
    public boolean getRedirectWake() { return (huskProps.get("RedirectWake") instanceof Boolean ? (Boolean) huskProps.get("RedirectWake") : false); }
    public boolean getUseNormalBrightnessForDoze() { return (huskProps.get("UseNormalBrightnessForDoze") instanceof Boolean ? (Boolean) huskProps.get("UseNormalBrightnessForDoze") : false); }
    public android.view.Window getWindow() { return (android.view.Window) huskProps.get("Window"); }
    public android.view.WindowManager getWindowManager() { return (android.view.WindowManager) huskProps.get("WindowManager"); }
    public boolean isDozing() { return (huskProps.get("Dozing") instanceof Boolean ? (Boolean) huskProps.get("Dozing") : false); }
    public boolean isFullscreen() { return (huskProps.get("Fullscreen") instanceof Boolean ? (Boolean) huskProps.get("Fullscreen") : false); }
    public boolean isInteractive() { return (huskProps.get("Interactive") instanceof Boolean ? (Boolean) huskProps.get("Interactive") : false); }
    public boolean isScreenBright() { return (huskProps.get("ScreenBright") instanceof Boolean ? (Boolean) huskProps.get("ScreenBright") : false); }
    public boolean isWindowless() { return (huskProps.get("Windowless") instanceof Boolean ? (Boolean) huskProps.get("Windowless") : false); }
    public void onActionModeFinished(android.view.ActionMode p0) {}
    public void onActionModeStarted(android.view.ActionMode p0) {}
    public void onAttachedToWindow() {}
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onContentChanged() {}
    public boolean onCreatePanelMenu(int p0, android.view.Menu p1) { return false; }
    public android.view.View onCreatePanelView(int p0) { return null; }
    public void onDetachedFromWindow() {}
    public void onDreamingStarted() {}
    public void onDreamingStopped() {}
    public boolean onMenuItemSelected(int p0, android.view.MenuItem p1) { return false; }
    public boolean onMenuOpened(int p0, android.view.Menu p1) { return false; }
    public void onPanelClosed(int p0, android.view.Menu p1) {}
    public boolean onPreparePanel(int p0, android.view.View p1, android.view.Menu p2) { return false; }
    public boolean onSearchRequested() { return false; }
    public boolean onSearchRequested(android.view.SearchEvent p0) { return false; }
    public void onWakeUp() {}
    public void onWindowAttributesChanged(android.view.WindowManager.LayoutParams p0) {}
    public void onWindowFocusChanged(boolean p0) {}
    public android.view.ActionMode onWindowStartingActionMode(android.view.ActionMode.Callback p0) { return null; }
    public android.view.ActionMode onWindowStartingActionMode(android.view.ActionMode.Callback p0, int p1) { return null; }
    public android.view.View requireViewById(int p0) { return null; }
    public void setContentView(int p0) { huskProps.put("ContentView", Integer.valueOf(p0)); }
    public void setContentView(android.view.View p0) { huskProps.put("ContentView", p0); }
    public void setContentView(android.view.View p0, android.view.ViewGroup.LayoutParams p1) {}
    public void setDebug(boolean p0) { huskProps.put("Debug", Boolean.valueOf(p0)); }
    public void setDozeScreenBrightness(float p0) { huskProps.put("DozeScreenBrightness", Float.valueOf(p0)); }
    public void setDozeScreenState(int p0) { huskProps.put("DozeScreenState", Integer.valueOf(p0)); }
    public void setDozeScreenState(int p0, int p1, boolean p2) {}
    public void setFullscreen(boolean p0) { huskProps.put("Fullscreen", Boolean.valueOf(p0)); }
    public void setInteractive(boolean p0) { huskProps.put("Interactive", Boolean.valueOf(p0)); }
    public void setScreenBright(boolean p0) { huskProps.put("ScreenBright", Boolean.valueOf(p0)); }
    public void setScreenBrightness(float p0) { huskProps.put("ScreenBrightness", Float.valueOf(p0)); }
    public void setWindowless(boolean p0) { huskProps.put("Windowless", Boolean.valueOf(p0)); }
    public void startDozing() {}
    public void stopDozing() {}
    public void wakeUp() {}
    public static final class DreamActivityCallbacks extends android.os.Binder {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public DreamActivityCallbacks(android.os.IBinder p0, java.lang.ref.WeakReference p1) { super(); }
        public void onActivityCreated(android.service.dreams.DreamActivity p0) {}
        public void onActivityDestroyed() {}
        DreamActivityCallbacks() { this((android.os.IBinder) null, (java.lang.ref.WeakReference) null); }
    }
    public static final class DreamMetadata {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public int dreamCategory;
        public android.graphics.drawable.Drawable previewImage;
        public android.content.ComponentName settingsActivity;
        public boolean showComplications;
        public DreamMetadata(android.content.ComponentName p0, android.graphics.drawable.Drawable p1, boolean p2, int p3) {}
        DreamMetadata() { this((android.content.ComponentName) null, (android.graphics.drawable.Drawable) null, (boolean) false, (int) 0); }
    }
    public interface Injector {
        android.service.dreams.DreamOverlayConnectionHandler createOverlayConnection(android.content.ComponentName p0, java.lang.Runnable p1);
        android.content.ComponentName getDreamActivityComponent();
        android.content.ComponentName getDreamComponent();
        android.service.dreams.IDreamManager getDreamManager();
        java.lang.String getDreamPackageName();
        android.os.Handler getHandler();
        android.content.pm.PackageManager getPackageManager();
        android.content.res.Resources getResources();
        android.content.pm.ServiceInfo getServiceInfo();
        void init(android.content.Context p0);
    }
}
