// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.controls;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class ControlsProviderService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String ACTION_ADD_CONTROL = "android.service.controls.action.ADD_CONTROL";
    public static final java.lang.String CALLBACK_BUNDLE = "CALLBACK_BUNDLE";
    public static final java.lang.String CALLBACK_TOKEN = "CALLBACK_TOKEN";
    public static final int CONTROLS_SURFACE_ACTIVITY_PANEL = 0;
    public static final int CONTROLS_SURFACE_DREAM = 1;
    public static final java.lang.String EXTRA_CONTROL = "android.service.controls.extra.CONTROL";
    public static final java.lang.String EXTRA_CONTROLS_SURFACE = "android.service.controls.extra.CONTROLS_SURFACE";
    public static final java.lang.String EXTRA_LOCKSCREEN_ALLOW_TRIVIAL_CONTROLS = "android.service.controls.extra.LOCKSCREEN_ALLOW_TRIVIAL_CONTROLS";
    public static final java.lang.String META_DATA_PANEL_ACTIVITY = "android.service.controls.META_DATA_PANEL_ACTIVITY";
    public static final java.lang.String SERVICE_CONTROLS = "android.service.controls.ControlsProviderService";
    public static final java.lang.String TAG = "ControlsProviderService";
    public ControlsProviderService() { super(); }
    public static void requestAddControl(android.content.Context p0, android.content.ComponentName p1, android.service.controls.Control p2) {}
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract void performControlAction(java.lang.String p0, android.service.controls.actions.ControlAction p1, java.util.function.Consumer p2);
}
