package android.view;

import android.graphics.Canvas;
import android.graphics.Rect;

/** A drawing surface. Software surfaces belong to a SurfaceView (lockCanvas draws into its buffer); GL ones to the render thread. */
public class Surface implements android.os.Parcelable {
    public static final int ROTATION_0 = 0, ROTATION_90 = 1, ROTATION_180 = 2, ROTATION_270 = 3;
    public static class OutOfResourcesException extends RuntimeException { public OutOfResourcesException() {} public OutOfResourcesException(String s) { super(s); } }
    interface Producer { Canvas lock(Rect dirty); void post(Canvas c); boolean valid(); }
    Producer mProducer;
    /** The SurfaceView this surface belongs to (EGL draws where it is). */
    public SurfaceView huskView;
    private boolean mReleased;
    public Surface() {}
    /** The SurfaceTexture this surface feeds, when made on one. */
    public android.graphics.SurfaceTexture huskTexture;
    public Surface(android.graphics.SurfaceTexture t) {
        huskTexture = t;
        if (t != null) mProducer = new Producer() {
            public Canvas lock(Rect d) { return t.huskLock(d); }
            public void post(Canvas c) { t.huskPost(c); }
            public boolean valid() { return t.huskValid(); }
        };
    }
    public Surface(SurfaceControl c) {}
    public boolean isValid() { return !mReleased && (mProducer == null || mProducer.valid()); }
    public void release() { mReleased = true; }
    public Canvas lockCanvas(Rect dirty) throws OutOfResourcesException, IllegalArgumentException { if (mProducer == null) throw new IllegalStateException("Surface has no buffer to draw into"); return mProducer.lock(dirty); }
    public Canvas lockHardwareCanvas() { return lockCanvas(null); }
    public void unlockCanvasAndPost(Canvas c) { if (mProducer != null) mProducer.post(c); }
    @Deprecated public void unlockCanvas(Canvas c) { unlockCanvasAndPost(c); }
    public void setFrameRate(float r, int c) {} public void setFrameRate(float r, int c, int s) {} public void clearFrameRate() {}
    public int describeContents() { return 0; }
    public void writeToParcel(android.os.Parcel p, int f) {}
    public void readFromParcel(android.os.Parcel p) {}
    public static final Creator<Surface> CREATOR = new Creator<Surface>() { public Surface createFromParcel(android.os.Parcel p) { return new Surface(); } public Surface[] newArray(int n) { return new Surface[n]; } };
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final int CHANGE_FRAME_RATE_ALWAYS = 1;
    public static final int CHANGE_FRAME_RATE_ONLY_IF_SEAMLESS = 0;
    public static final int FRAME_RATE_CATEGORY_DEFAULT = 0;
    public static final int FRAME_RATE_CATEGORY_HIGH = 5;
    public static final int FRAME_RATE_CATEGORY_HIGH_HINT = 4;
    public static final int FRAME_RATE_CATEGORY_LOW = 2;
    public static final int FRAME_RATE_CATEGORY_NORMAL = 3;
    public static final int FRAME_RATE_CATEGORY_NO_PREFERENCE = 1;
    public static final int FRAME_RATE_COMPATIBILITY_AT_LEAST = 2;
    public static final int FRAME_RATE_COMPATIBILITY_DEFAULT = 0;
    public static final int FRAME_RATE_COMPATIBILITY_EXACT = 100;
    public static final int FRAME_RATE_COMPATIBILITY_FIXED_SOURCE = 1;
    public static final int FRAME_RATE_COMPATIBILITY_MIN = 102;
    public static final int FRAME_RATE_COMPATIBILITY_NO_VOTE = 101;
    public static final int SCALING_MODE_FREEZE = 0;
    public static final int SCALING_MODE_NO_SCALE_CROP = 3;
    public static final int SCALING_MODE_SCALE_CROP = 2;
    public static final int SCALING_MODE_SCALE_TO_WINDOW = 1;
    public static java.lang.String rotationToString(int p0) { return null; }
    public void allocateBuffers() {}
    public void attachAndQueueBufferWithColorSpace(android.hardware.HardwareBuffer p0, android.graphics.ColorSpace p1) {}
    public void copyFrom(android.graphics.BLASTBufferQueue p0) {}
    public void copyFrom(android.view.SurfaceControl p0) {}
    public void createFrom(android.view.SurfaceControl p0) {}
    public void destroy() {}
    public android.graphics.Point getDefaultSize() { return null; }
    public int getGenerationId() { return 0; }
    public long getNextFrameNumber() { return 0L; }
    public void hwuiDestroy() {}
    public boolean isAutoRefreshEnabled() { return (huskFill.get("AutoRefreshEnabled") instanceof Boolean ? (Boolean) huskFill.get("AutoRefreshEnabled") : false); }
    public boolean isConsumerRunningBehind() { return false; }
    public boolean isSharedBufferModeEnabled() { return (huskFill.get("SharedBufferModeEnabled") instanceof Boolean ? (Boolean) huskFill.get("SharedBufferModeEnabled") : false); }
    public boolean isSingleBuffered() { return false; }
    public android.graphics.Canvas lockHardwareWideColorGamutCanvas() { return null; }
    public void setAutoRefreshEnabled(boolean p0) { huskFill.put("AutoRefreshEnabled", Boolean.valueOf(p0)); }
    public void setFrameRate(android.view.Surface.FrameRateParams p0) {}
    public void setScalingMode(int p0) {}
    public void setSharedBufferModeEnabled(boolean p0) { huskFill.put("SharedBufferModeEnabled", Boolean.valueOf(p0)); }
    public void transferFrom(android.view.Surface p0) {}
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public static class FrameRateParams {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.view.Surface.FrameRateParams IGNORE;
        public int getChangeFrameRateStrategy() { return (huskProps.get("ChangeFrameRateStrategy") instanceof Integer ? (Integer) huskProps.get("ChangeFrameRateStrategy") : 0); }
        public float getDesiredMaxRate() { return (huskProps.get("DesiredMaxRate") instanceof Float ? (Float) huskProps.get("DesiredMaxRate") : 0f); }
        public float getDesiredMinRate() { return (huskProps.get("DesiredMinRate") instanceof Float ? (Float) huskProps.get("DesiredMinRate") : 0f); }
        public float getFixedSourceRate() { return (huskProps.get("FixedSourceRate") instanceof Float ? (Float) huskProps.get("FixedSourceRate") : 0f); }
        protected FrameRateParams() {}
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder() {}
            public android.view.Surface.FrameRateParams build() { android.view.Surface.FrameRateParams x = new android.view.Surface.FrameRateParams(); x.huskProps.putAll(huskProps); return x; }
            public android.view.Surface.FrameRateParams.Builder setChangeFrameRateStrategy(int p0) { huskProps.put("ChangeFrameRateStrategy", Integer.valueOf(p0)); return this; }
            public android.view.Surface.FrameRateParams.Builder setDesiredRateRange(float p0, float p1) { return this; }
            public android.view.Surface.FrameRateParams.Builder setFixedSourceRate(float p0) { huskProps.put("FixedSourceRate", Float.valueOf(p0)); return this; }
        }
    }
    // ---- end of generated nested classes
}
