package android.media;

/** Recording: no microphone is connected through Husk, so a record produces silence at the pace a microphone would. */
public class AudioRecord implements AudioRouting {
    public static final int STATE_UNINITIALIZED = 0, STATE_INITIALIZED = 1, RECORDSTATE_STOPPED = 1, RECORDSTATE_RECORDING = 3;
    public static final int SUCCESS = 0, ERROR = -1, ERROR_BAD_VALUE = -2, ERROR_INVALID_OPERATION = -3, ERROR_DEAD_OBJECT = -6, READ_BLOCKING = 0, READ_NON_BLOCKING = 1;
    public interface OnRecordPositionUpdateListener { void onMarkerReached(AudioRecord r); void onPeriodicNotification(AudioRecord r); }
    private final int mRate, mChannels, mEncoding, mMask, mFrames, mSource;
    private int mState = STATE_INITIALIZED, mRecording = RECORDSTATE_STOPPED;
    private long mStart;
    public AudioRecord(int source, int sampleRate, int channelConfig, int audioFormat, int bufferSizeInBytes) {
        mRate = sampleRate > 0 ? sampleRate : 44100; mChannels = channelConfig == AudioFormat.CHANNEL_IN_STEREO ? 2 : 1;
        mEncoding = audioFormat == AudioFormat.ENCODING_DEFAULT ? AudioFormat.ENCODING_PCM_16BIT : audioFormat;
        mMask = mChannels == 2 ? AudioFormat.CHANNEL_IN_STEREO : AudioFormat.CHANNEL_IN_MONO; mSource = source;
        int bps = mEncoding == AudioFormat.ENCODING_PCM_FLOAT ? 4 : mEncoding == AudioFormat.ENCODING_PCM_8BIT ? 1 : 2;
        int bytes = bufferSizeInBytes > 0 ? bufferSizeInBytes : getMinBufferSize(mRate, mMask, mEncoding);
        mFrames = Math.max(1, bytes / (bps * mChannels));
    }
    public int getBufferSizeInFrames() { return mFrames; }
    public int getChannelConfiguration() { return mMask; }
    public AudioFormat getFormat() { return new AudioFormat.Builder().setEncoding(mEncoding).setSampleRate(mRate).setChannelMask(mMask).build(); }
    public AudioAttributes getAudioAttributes() { return new AudioAttributes.Builder().build(); }
    public int getTimestamp(AudioTimestamp t, int base) {
        if (mRecording != RECORDSTATE_RECORDING || t == null) return ERROR_INVALID_OPERATION;
        long now = System.nanoTime(); t.nanoTime = now; t.framePosition = (now - mStart) * mRate / 1000000000L; return SUCCESS;
    }
    public static class Builder {
        private AudioFormat f = new AudioFormat.Builder().setChannelMask(AudioFormat.CHANNEL_IN_MONO).build(); private int size = 4096;
        public Builder setAudioSource(int s) { src = s; return this; }
        public Builder setAudioFormat(AudioFormat x) { f = x; return this; }
        public Builder setBufferSizeInBytes(int x) { size = x; return this; }
        public Builder setContext(android.content.Context c) { return this; }
        private int src = 1;
        public AudioRecord build() { return new AudioRecord(src, f.getSampleRate() > 0 ? f.getSampleRate() : 44100, f.getChannelMask(), f.getEncoding(), size); }
        // ---- generated by tools/compat/fillmembers.py (Builder): the platform's members this class does not write (signatures only)
        public android.media.AudioRecord.Builder setAudioAttributes(android.media.AudioAttributes p0) { return this; }
        public android.media.AudioRecord.Builder setAudioPlaybackCaptureConfig(android.media.AudioPlaybackCaptureConfiguration p0) { return this; }
        public android.media.AudioRecord.Builder setCallRedirectionMode(int p0) { return this; }
        public android.media.AudioRecord.Builder setMaxSharedAudioHistoryMillis(long p0) { return this; }
        public android.media.AudioRecord.Builder setPrivacySensitive(boolean p0) { return this; }
        public android.media.AudioRecord.Builder setRequestHotwordLookbackStream(boolean p0) { return this; }
        public android.media.AudioRecord.Builder setRequestHotwordStream(boolean p0) { return this; }
        public android.media.AudioRecord.Builder setSessionId(int p0) { return this; }
        public android.media.AudioRecord.Builder setSharedAudioEvent(android.media.MediaSyncEvent p0) { return this; }
        // ---- end of generated members (Builder)
    }
    public static int getMinBufferSize(int sampleRate, int channelConfig, int audioFormat) { return Math.max(1024, sampleRate / 10) * (channelConfig == AudioFormat.CHANNEL_IN_STEREO ? 2 : 1) * 2; }
    public int getSampleRate() { return mRate; }
    public int getAudioFormat() { return mEncoding; }
    public int getChannelCount() { return mChannels; }
    public int getState() { return mState; }
    public int getRecordingState() { return mRecording; }
    public int getAudioSessionId() { return 0; }
    public int getAudioSource() { return mSource; }
    public void startRecording() { mRecording = RECORDSTATE_RECORDING; mStart = System.nanoTime(); }
    public void stop() { mRecording = RECORDSTATE_STOPPED; }
    public void release() { stop(); mState = STATE_UNINITIALIZED; }
    private void pace(int frames) { try { Thread.sleep(Math.max(1, frames * 1000L / mRate)); } catch (InterruptedException e) { Thread.currentThread().interrupt(); } }
    public int read(byte[] b, int off, int n) { return read(b, off, n, READ_BLOCKING); }
    public int read(byte[] b, int off, int n, int mode) { if (mRecording != RECORDSTATE_RECORDING) return ERROR_INVALID_OPERATION; java.util.Arrays.fill(b, off, off + n, (byte) 0); if (mode == READ_BLOCKING) pace(n / 2 / mChannels); return n; }
    public int read(short[] b, int off, int n) { return read(b, off, n, READ_BLOCKING); }
    public int read(short[] b, int off, int n, int mode) { if (mRecording != RECORDSTATE_RECORDING) return ERROR_INVALID_OPERATION; java.util.Arrays.fill(b, off, off + n, (short) 0); if (mode == READ_BLOCKING) pace(n / mChannels); return n; }
    public int read(float[] b, int off, int n, int mode) { if (mRecording != RECORDSTATE_RECORDING) return ERROR_INVALID_OPERATION; java.util.Arrays.fill(b, off, off + n, 0f); if (mode == READ_BLOCKING) pace(n / mChannels); return n; }
    public int read(java.nio.ByteBuffer b, int n) { return read(b, n, READ_BLOCKING); }
    public int read(java.nio.ByteBuffer b, int n, int mode) { if (mRecording != RECORDSTATE_RECORDING) return ERROR_INVALID_OPERATION; for (int i = 0; i < n; i++) b.put(b.position() + i, (byte) 0); if (mode == READ_BLOCKING) pace(n / 2 / mChannels); return n; }
    public void setRecordPositionUpdateListener(OnRecordPositionUpdateListener l) {}
    public void setRecordPositionUpdateListener(OnRecordPositionUpdateListener l, android.os.Handler h) {}
    public int setNotificationMarkerPosition(int m) { return SUCCESS; }
    public int setPositionNotificationPeriod(int p) { return SUCCESS; }
    public AudioDeviceInfo getRoutedDevice() { return null; }
    public boolean setPreferredDevice(AudioDeviceInfo d) { return true; }
    public AudioDeviceInfo getPreferredDevice() { return null; }
    public void addOnRoutingChangedListener(AudioRouting.OnRoutingChangedListener l, android.os.Handler h) {}
    public void removeOnRoutingChangedListener(AudioRouting.OnRoutingChangedListener l) {}
    // ---- generated by tools/compat/fillmembers.py: the platform's members this class does not write (signatures only)
    private final java.util.HashMap<String, Object> huskFill = new java.util.HashMap<>();
    public static final java.lang.String SUBMIX_FIXED_VOLUME = "fixedVolume";
    public static long getMaxSharedAudioHistoryMillis() { return 0L; }
    public java.util.List getActiveMicrophones() { return new java.util.ArrayList(); }
    public android.media.AudioRecordingConfiguration getActiveRecordingConfiguration() { return null; }
    public android.media.metrics.LogSessionId getLogSessionId() { Object v = huskFill.get("LogSessionId"); return v != null ? (android.media.metrics.LogSessionId) v : android.media.metrics.LogSessionId.LOG_SESSION_ID_NONE; }
    public android.os.PersistableBundle getMetrics() { return null; }
    public int getNotificationMarkerPosition() { return 0; }
    public int getPortId() { return 0; }
    public int getPositionNotificationPeriod() { return 0; }
    public java.util.List getRoutedDevices() { return new java.util.ArrayList(); }
    public boolean isHotwordLookbackStream() { return false; }
    public boolean isHotwordStream() { return false; }
    public boolean isPrivacySensitive() { return false; }
    public void native_release() {}
    public void registerAudioRecordingCallback(java.util.concurrent.Executor p0, android.media.AudioManager.AudioRecordingCallback p1) {}
    public void setLogSessionId(android.media.metrics.LogSessionId p0) { huskFill.put("LogSessionId", p0); }
    public boolean setPreferredMicrophoneDirection(int p0) { return false; }
    public boolean setPreferredMicrophoneFieldDimension(float p0) { return false; }
    public android.media.MediaSyncEvent shareAudioHistory(java.lang.String p0, long p1) { return null; }
    public void startRecording(android.media.MediaSyncEvent p0) {}
    public void unregisterAudioRecordingCallback(android.media.AudioManager.AudioRecordingCallback p0) {}
    // ---- end of generated members
    // ---- generated by tools/compat/genstubs.py: the platform's nested classes this class does not write
    public static final class MetricsConstants {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final java.lang.String ATTRIBUTES = "android.media.audiorecord.attributes";
        public static final java.lang.String CHANNELS = "android.media.audiorecord.channels";
        public static final java.lang.String CHANNEL_MASK = "android.media.audiorecord.channelMask";
        public static final java.lang.String DURATION_MS = "android.media.audiorecord.durationMs";
        public static final java.lang.String ENCODING = "android.media.audiorecord.encoding";
        public static final java.lang.String FRAME_COUNT = "android.media.audiorecord.frameCount";
        public static final java.lang.String LATENCY = "android.media.audiorecord.latency";
        public static final java.lang.String PORT_ID = "android.media.audiorecord.portId";
        public static final java.lang.String SAMPLERATE = "android.media.audiorecord.samplerate";
        public static final java.lang.String SOURCE = "android.media.audiorecord.source";
        public static final java.lang.String START_COUNT = "android.media.audiorecord.startCount";
        protected MetricsConstants() {}
    }
    public interface OnRoutingChangedListener extends android.media.AudioRouting.OnRoutingChangedListener {
        void onRoutingChanged(android.media.AudioRecord p0);
        default void onRoutingChanged(android.media.AudioRouting p0) {}
    }
    // ---- end of generated nested classes
}
