// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.tv.interactive;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TvInteractiveAppView extends android.view.ViewGroup {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String BI_INTERACTIVE_APP_KEY_ALIAS = "alias";
    public static final java.lang.String BI_INTERACTIVE_APP_KEY_CERTIFICATE = "certificate";
    public static final java.lang.String BI_INTERACTIVE_APP_KEY_HTTP_ADDITIONAL_HEADERS = "http_additional_headers";
    public static final java.lang.String BI_INTERACTIVE_APP_KEY_HTTP_USER_AGENT = "http_user_agent";
    public static final java.lang.String BI_INTERACTIVE_APP_KEY_PRIVATE_KEY = "private_key";
    public static final java.lang.String ERROR_KEY_METHOD_NAME = "method_name";
    public TvInteractiveAppView(android.content.Context p0) { super(p0); }
    public TvInteractiveAppView(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public TvInteractiveAppView(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public void clearCallback() {}
    public void clearOnUnhandledInputEventListener() {}
    public void createBiInteractiveApp(android.net.Uri p0, android.os.Bundle p1) {}
    public void destroyBiInteractiveApp(java.lang.String p0) {}
    public boolean dispatchUnhandledInputEvent(android.view.InputEvent p0) { return false; }
    public android.media.tv.interactive.TvInteractiveAppManager.Session getInteractiveAppSession() { return (android.media.tv.interactive.TvInteractiveAppManager.Session) huskProps.get("InteractiveAppSession"); }
    public android.media.tv.interactive.TvInteractiveAppView.OnUnhandledInputEventListener getOnUnhandledInputEventListener() { return (android.media.tv.interactive.TvInteractiveAppView.OnUnhandledInputEventListener) huskProps.get("OnUnhandledInputEventListener"); }
    public void notifyError(java.lang.String p0, android.os.Bundle p1) {}
    public void notifyRecordingConnectionFailed(java.lang.String p0, java.lang.String p1) {}
    public void notifyRecordingDisconnected(java.lang.String p0, java.lang.String p1) {}
    public void notifyRecordingError(java.lang.String p0, int p1) {}
    public void notifyRecordingScheduled(java.lang.String p0, java.lang.String p1) {}
    public void notifyRecordingStarted(java.lang.String p0, java.lang.String p1) {}
    public void notifyRecordingStopped(java.lang.String p0) {}
    public void notifyRecordingTuned(java.lang.String p0, android.net.Uri p1) {}
    public void notifyTimeShiftCurrentPositionChanged(java.lang.String p0, long p1) {}
    public void notifyTimeShiftPlaybackParams(android.media.PlaybackParams p0) {}
    public void notifyTimeShiftStartPositionChanged(java.lang.String p0, long p1) {}
    public void notifyTimeShiftStatusChanged(java.lang.String p0, int p1) {}
    public void notifyTvMessage(int p0, android.os.Bundle p1) {}
    public void notifyVideoFreezeUpdated(boolean p0) {}
    public void onLayout(boolean p0, int p1, int p2, int p3, int p4) {}
    public boolean onUnhandledInputEvent(android.view.InputEvent p0) { return false; }
    public void prepareInteractiveApp(java.lang.String p0, int p1) {}
    public void reset() {}
    public void resetInteractiveApp() {}
    public void sendAvailableSpeeds(float[] p0) {}
    public void sendCertificate(java.lang.String p0, int p1, android.net.http.SslCertificate p2) {}
    public void sendCurrentChannelLcn(int p0) {}
    public void sendCurrentChannelUri(android.net.Uri p0) {}
    public void sendCurrentTvInputId(java.lang.String p0) {}
    public void sendCurrentVideoBounds(android.graphics.Rect p0) {}
    public void sendSelectedTrackInfo(java.util.List p0) {}
    public void sendSigningResult(java.lang.String p0, byte[] p1) {}
    public void sendStreamVolume(float p0) {}
    public void sendTimeShiftMode(int p0) {}
    public void sendTrackInfoList(java.util.List p0) {}
    public void sendTvRecordingInfo(android.media.tv.TvRecordingInfo p0) {}
    public void sendTvRecordingInfoList(java.util.List p0) {}
    public void setCallback(java.util.concurrent.Executor p0, android.media.tv.interactive.TvInteractiveAppView.TvInteractiveAppCallback p1) {}
    public void setOnUnhandledInputEventListener(java.util.concurrent.Executor p0, android.media.tv.interactive.TvInteractiveAppView.OnUnhandledInputEventListener p1) {}
    public void setTeletextAppEnabled(boolean p0) { huskProps.put("TeletextAppEnabled", Boolean.valueOf(p0)); }
    public int setTvView(android.media.tv.TvView p0) { return 0; }
    public void setZOrderMediaOverlay(boolean p0) { huskProps.put("ZOrderMediaOverlay", Boolean.valueOf(p0)); }
    public void setZOrderOnTop(boolean p0) { huskProps.put("ZOrderOnTop", Boolean.valueOf(p0)); }
    public void startInteractiveApp() {}
    public void stopInteractiveApp() {}
    TvInteractiveAppView() { this((android.content.Context) null); }
    public interface OnUnhandledInputEventListener {
        boolean onUnhandledInputEvent(android.view.InputEvent p0);
    }
    public static abstract class TvInteractiveAppCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public TvInteractiveAppCallback() {}
        public void onBiInteractiveAppCreated(java.lang.String p0, android.net.Uri p1, java.lang.String p2) {}
        public void onPlaybackCommandRequest(java.lang.String p0, java.lang.String p1, android.os.Bundle p2) {}
        public void onRequestAvailableSpeeds(java.lang.String p0) {}
        public void onRequestCertificate(java.lang.String p0, java.lang.String p1, int p2) {}
        public void onRequestCurrentChannelLcn(java.lang.String p0) {}
        public void onRequestCurrentChannelUri(java.lang.String p0) {}
        public void onRequestCurrentTvInputId(java.lang.String p0) {}
        public void onRequestCurrentVideoBounds(java.lang.String p0) {}
        public void onRequestScheduleRecording(java.lang.String p0, java.lang.String p1, java.lang.String p2, android.net.Uri p3, long p4, long p5, int p6, android.os.Bundle p7) {}
        public void onRequestScheduleRecording(java.lang.String p0, java.lang.String p1, java.lang.String p2, android.net.Uri p3, android.net.Uri p4, android.os.Bundle p5) {}
        public void onRequestSelectedTrackInfo(java.lang.String p0) {}
        public void onRequestSigning(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3, int p4, byte[] p5) {}
        public void onRequestSigning(java.lang.String p0, java.lang.String p1, java.lang.String p2, java.lang.String p3, byte[] p4) {}
        public void onRequestStartRecording(java.lang.String p0, java.lang.String p1, android.net.Uri p2) {}
        public void onRequestStopRecording(java.lang.String p0, java.lang.String p1) {}
        public void onRequestStreamVolume(java.lang.String p0) {}
        public void onRequestTimeShiftMode(java.lang.String p0) {}
        public void onRequestTrackInfoList(java.lang.String p0) {}
        public void onRequestTvRecordingInfo(java.lang.String p0, java.lang.String p1) {}
        public void onRequestTvRecordingInfoList(java.lang.String p0, int p1) {}
        public void onSetTvRecordingInfo(java.lang.String p0, java.lang.String p1, android.media.tv.TvRecordingInfo p2) {}
        public void onSetVideoBounds(java.lang.String p0, android.graphics.Rect p1) {}
        public void onStateChanged(java.lang.String p0, int p1, int p2) {}
        public void onTeletextAppStateChanged(java.lang.String p0, int p1) {}
        public void onTimeShiftCommandRequest(java.lang.String p0, java.lang.String p1, android.os.Bundle p2) {}
    }
}
