// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.inputmethodservice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class AbstractInputMethodService extends android.window.WindowProviderService implements android.view.KeyEvent.Callback {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public AbstractInputMethodService() { super(); }
    public int getInitialDisplayId() { return (huskProps.get("InitialDisplayId") instanceof Integer ? (Integer) huskProps.get("InitialDisplayId") : 0); }
    public android.view.inputmethod.InputMethod getInputMethodInternal() { return (android.view.inputmethod.InputMethod) huskProps.get("InputMethodInternal"); }
    public android.view.KeyEvent.DispatcherState getKeyDispatcherState() { return (android.view.KeyEvent.DispatcherState) huskProps.get("KeyDispatcherState"); }
    public android.os.Bundle getWindowContextOptions() { return (android.os.Bundle) huskProps.get("WindowContextOptions"); }
    public int getWindowType() { return (huskProps.get("WindowType") instanceof Integer ? (Integer) huskProps.get("WindowType") : 0); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract android.inputmethodservice.AbstractInputMethodService.AbstractInputMethodImpl onCreateInputMethodInterface();
    public abstract android.inputmethodservice.AbstractInputMethodService.AbstractInputMethodSessionImpl onCreateInputMethodSessionInterface();
    public boolean onGenericMotionEvent(android.view.MotionEvent p0) { return false; }
    public boolean onShouldVerifyKeyEvent(android.view.KeyEvent p0) { return false; }
    public boolean onTrackballEvent(android.view.MotionEvent p0) { return false; }
    public static abstract class AbstractInputMethodImpl implements android.view.inputmethod.InputMethod {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public AbstractInputMethodImpl(android.inputmethodservice.AbstractInputMethodService p0) {}
        public void createSession(android.view.inputmethod.InputMethod.SessionCallback p0) {}
        public void revokeSession(android.view.inputmethod.InputMethodSession p0) {}
        public void setSessionEnabled(android.view.inputmethod.InputMethodSession p0, boolean p1) {}
        AbstractInputMethodImpl() { this((android.inputmethodservice.AbstractInputMethodService) null); }
    }
    public static abstract class AbstractInputMethodSessionImpl implements android.view.inputmethod.InputMethodSession {
        protected AbstractInputMethodSessionImpl() {}
    }
}
