// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.inputmethodservice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ExtractEditText extends android.widget.EditText {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public ExtractEditText(android.content.Context p0) { super(p0); }
    public ExtractEditText(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public ExtractEditText(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public ExtractEditText(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    protected void deleteText_internal(int p0, int p1) {}
    public void finishInternalChanges() {}
    public boolean hasFocus() { return false; }
    public boolean hasVerticalScrollBar() { return false; }
    public boolean hasWindowFocus() { return false; }
    public boolean isFocused() { return (huskProps.get("Focused") instanceof Boolean ? (Boolean) huskProps.get("Focused") : false); }
    public boolean isInExtractedMode() { return (huskProps.get("InExtractedMode") instanceof Boolean ? (Boolean) huskProps.get("InExtractedMode") : false); }
    protected void replaceText_internal(int p0, int p1, java.lang.CharSequence p2) {}
    protected void setCursorPosition_internal(int p0, int p1) {}
    protected void setSpan_internal(java.lang.Object p0, int p1, int p2, int p3) {}
    public void startInternalChanges() {}
    protected void viewClicked(android.view.inputmethod.InputMethodManager p0) {}
    ExtractEditText() { this((android.content.Context) null); }
}
