// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.graphics.drawable;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class AdaptiveIconDrawable extends android.graphics.drawable.Drawable implements android.graphics.drawable.Drawable.Callback {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final float MASK_SIZE = 100.0f;
    public AdaptiveIconDrawable(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1) { super(); }
    public AdaptiveIconDrawable(android.graphics.drawable.Drawable p0, android.graphics.drawable.Drawable p1, android.graphics.drawable.Drawable p2) { super(); }
    public static float getExtraInsetFraction() { return 0f; }
    public static float getExtraInsetPercentage() { return 0f; }
    public void clearMutated() {}
    public void draw(android.graphics.Canvas p0) {}
    public android.graphics.drawable.Drawable getBackground() { return (android.graphics.drawable.Drawable) huskProps.get("Background"); }
    public android.graphics.drawable.Drawable getForeground() { return (android.graphics.drawable.Drawable) huskProps.get("Foreground"); }
    public android.graphics.Path getIconMask() { return (android.graphics.Path) huskProps.get("IconMask"); }
    public android.graphics.drawable.Drawable getMonochrome() { return (android.graphics.drawable.Drawable) huskProps.get("Monochrome"); }
    public android.graphics.Region getSafeZone() { return (android.graphics.Region) huskProps.get("SafeZone"); }
    public int getSourceDrawableResId() { return (huskProps.get("SourceDrawableResId") instanceof Integer ? (Integer) huskProps.get("SourceDrawableResId") : 0); }
    public void invalidateDrawable(android.graphics.drawable.Drawable p0) {}
    public boolean isProjected() { return (huskProps.get("Projected") instanceof Boolean ? (Boolean) huskProps.get("Projected") : false); }
    public void scheduleDrawable(android.graphics.drawable.Drawable p0, java.lang.Runnable p1, long p2) {}
    public void setOpacity(int p0) { huskProps.put("Opacity", Integer.valueOf(p0)); }
    public void unscheduleDrawable(android.graphics.drawable.Drawable p0, java.lang.Runnable p1) {}
    AdaptiveIconDrawable() { this((android.graphics.drawable.Drawable) null, (android.graphics.drawable.Drawable) null); }
}
