// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.graphics.drawable;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class AnimatedImageDrawable extends android.graphics.drawable.Drawable implements android.graphics.drawable.Animatable2 {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int LOOP_INFINITE = -1;
    public static final int REPEAT_INFINITE = -1;
    public AnimatedImageDrawable() { super(); }
    public AnimatedImageDrawable(long p0, android.graphics.ImageDecoder p1, int p2, int p3, long p4, boolean p5, int p6, int p7, android.graphics.Rect p8, java.io.InputStream p9, android.content.res.AssetFileDescriptor p10) { super(); }
    public void clearAnimationCallbacks() {}
    public void draw(android.graphics.Canvas p0) {}
    public int getLoopCount(int p0) { return 0; }
    public int getRepeatCount() { return (huskProps.get("RepeatCount") instanceof Integer ? (Integer) huskProps.get("RepeatCount") : 0); }
    public boolean isRunning() { return (huskProps.get("Running") instanceof Boolean ? (Boolean) huskProps.get("Running") : false); }
    public void registerAnimationCallback(android.graphics.drawable.Animatable2.AnimationCallback p0) {}
    public void setLoopCount(int p0) { huskProps.put("LoopCount", Integer.valueOf(p0)); }
    public void setRepeatCount(int p0) { huskProps.put("RepeatCount", Integer.valueOf(p0)); }
    public void start() {}
    public void stop() {}
    public boolean unregisterAnimationCallback(android.graphics.drawable.Animatable2.AnimationCallback p0) { return false; }
}
