// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telecom;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class CallRedirectionService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String SERVICE_INTERFACE = "android.telecom.CallRedirectionService";
    public CallRedirectionService() { super(); }
    public void cancelCall() {}
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onPlaceCall(android.net.Uri p0, android.net.Uri p1, android.telecom.PhoneAccountHandle p2, boolean p3) {}
    public abstract void onPlaceCall(android.net.Uri p0, android.telecom.PhoneAccountHandle p1, boolean p2);
    public void onRedirectionTimeout() {}
    public void placeCallUnmodified() {}
    public void redirectCall(android.net.Uri p0, android.telecom.PhoneAccountHandle p1, boolean p2) {}
}
