// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telecom;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class CallScreeningService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String SERVICE_INTERFACE = "android.telecom.CallScreeningService";
    public CallScreeningService() { super(); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract void onScreenCall(android.telecom.Call.Details p0);
    public void respondToCall(android.telecom.Call.Details p0, android.telecom.CallScreeningService.CallResponse p1) {}
    public static abstract class CallResponse {
        protected CallResponse() {}
    }
    public static class ParcelableCallResponse implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        protected ParcelableCallResponse(android.os.Parcel p0) {}
        public int describeContents() { return 0; }
        public int getCallComposerAttachmentsToShow() { return (huskProps.get("CallComposerAttachmentsToShow") instanceof Integer ? (Integer) huskProps.get("CallComposerAttachmentsToShow") : 0); }
        public boolean shouldDisallowCall() { return false; }
        public boolean shouldRejectCall() { return false; }
        public boolean shouldScreenCallViaAudioProcessing() { return false; }
        public boolean shouldSilenceCall() { return false; }
        public boolean shouldSkipCallLog() { return false; }
        public boolean shouldSkipNotification() { return false; }
        public android.telecom.CallScreeningService.CallResponse toCallResponse() { return null; }
        public void writeToParcel(android.os.Parcel p0, int p1) {}
        ParcelableCallResponse() { this((android.os.Parcel) null); }
    }
}
