// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telecom;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class ConnectionService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String EXTRA_IS_HANDOVER = "android.telecom.extra.IS_HANDOVER";
    public static final java.lang.String SERVICE_INTERFACE = "android.telecom.ConnectionService";
    public ConnectionService() { super(); }
    public void addConference(android.telecom.Conference p0) {}
    public void addConferenceFromConnection(android.telecom.Conference p0, android.telecom.Connection p1) {}
    public void addExistingConnection(android.telecom.PhoneAccountHandle p0, android.telecom.Connection p1) {}
    public void addExistingConnection(android.telecom.PhoneAccountHandle p0, android.telecom.Connection p1, android.telecom.Conference p2) {}
    public void conferenceRemoteConnections(android.telecom.RemoteConnection p0, android.telecom.RemoteConnection p1) {}
    public void connectionServiceFocusReleased() {}
    public boolean containsConference(android.telecom.Conference p0) { return false; }
    public android.telecom.RemoteConference createRemoteIncomingConference(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public android.telecom.RemoteConnection createRemoteIncomingConnection(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public android.telecom.RemoteConference createRemoteOutgoingConference(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public android.telecom.RemoteConnection createRemoteOutgoingConnection(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public java.util.Collection getAllConferences() { return (huskProps.get("AllConferences") != null ? (java.util.Collection) huskProps.get("AllConferences") : new java.util.ArrayList()); }
    public java.util.Collection getAllConnections() { return (huskProps.get("AllConnections") != null ? (java.util.Collection) huskProps.get("AllConnections") : new java.util.ArrayList()); }
    public android.os.Handler getHandler() { return (android.os.Handler) huskProps.get("Handler"); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onBindClient(android.content.Intent p0) {}
    public void onConference(android.telecom.Connection p0, android.telecom.Connection p1) {}
    public void onConferenceAdded(android.telecom.Conference p0) {}
    public void onConferenceRemoved(android.telecom.Conference p0) {}
    public void onConnectionAdded(android.telecom.Connection p0) {}
    public void onConnectionRemoved(android.telecom.Connection p0) {}
    public void onConnectionServiceFocusGained() {}
    public void onConnectionServiceFocusLost() {}
    public void onCreateConferenceComplete(android.telecom.Conference p0) {}
    public void onCreateConnectionComplete(android.telecom.Connection p0) {}
    public android.telecom.Conference onCreateIncomingConference(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public void onCreateIncomingConferenceFailed(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) {}
    public android.telecom.Connection onCreateIncomingConnection(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public void onCreateIncomingConnectionFailed(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) {}
    public android.telecom.Connection onCreateIncomingHandoverConnection(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public android.telecom.Conference onCreateOutgoingConference(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public void onCreateOutgoingConferenceFailed(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) {}
    public android.telecom.Connection onCreateOutgoingConnection(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public void onCreateOutgoingConnectionFailed(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) {}
    public android.telecom.Connection onCreateOutgoingHandoverConnection(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public android.telecom.Connection onCreateUnknownConnection(android.telecom.PhoneAccountHandle p0, android.telecom.ConnectionRequest p1) { return null; }
    public void onHandoverFailed(android.telecom.ConnectionRequest p0, int p1) {}
    public void onRemoteConferenceAdded(android.telecom.RemoteConference p0) {}
    public void onRemoteExistingConnectionAdded(android.telecom.RemoteConnection p0) {}
    protected void removeConnection(android.telecom.Connection p0) {}
    public void setReadyForTest() {}
    public void triggerConferenceRecalculate() {}
}
