// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.telecom;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class InCallService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String SERVICE_INTERFACE = "android.telecom.InCallService";
    public InCallService() { super(); }
    public boolean canAddCall() { return false; }
    public android.telecom.AudioState getAudioState() { return (android.telecom.AudioState) huskProps.get("AudioState"); }
    public android.telecom.CallAudioState getCallAudioState() { return (android.telecom.CallAudioState) huskProps.get("CallAudioState"); }
    public java.util.List getCalls() { return (huskProps.get("Calls") != null ? (java.util.List) huskProps.get("Calls") : new java.util.ArrayList()); }
    public android.telecom.CallEndpoint getCurrentCallEndpoint() { return (android.telecom.CallEndpoint) huskProps.get("CurrentCallEndpoint"); }
    public android.telecom.Phone getPhone() { return (android.telecom.Phone) huskProps.get("Phone"); }
    public void onAudioStateChanged(android.telecom.AudioState p0) {}
    public void onAvailableCallEndpointsChanged(java.util.List p0) {}
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onBringToForeground(boolean p0) {}
    public void onCallAdded(android.telecom.Call p0) {}
    public void onCallAudioStateChanged(android.telecom.CallAudioState p0) {}
    public void onCallEndpointChanged(android.telecom.CallEndpoint p0) {}
    public void onCallRemoved(android.telecom.Call p0) {}
    public void onCanAddCallChanged(boolean p0) {}
    public void onConnectionEvent(android.telecom.Call p0, java.lang.String p1, android.os.Bundle p2) {}
    public void onMuteStateChanged(boolean p0) {}
    public void onPhoneCreated(android.telecom.Phone p0) {}
    public void onPhoneDestroyed(android.telecom.Phone p0) {}
    public void onSilenceRinger() {}
    public void requestBluetoothAudio(android.bluetooth.BluetoothDevice p0) {}
    public void requestCallEndpointChange(android.telecom.CallEndpoint p0, java.util.concurrent.Executor p1, android.os.OutcomeReceiver p2) {}
    public void setAudioRoute(int p0) { huskProps.put("AudioRoute", Integer.valueOf(p0)); }
    public void setMuted(boolean p0) { huskProps.put("Muted", Boolean.valueOf(p0)); }
    public static abstract class VideoCall {
        protected VideoCall() {}
    }
}
