// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app.slice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class SliceProvider extends android.content.ContentProvider {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String EXTRA_BIND_URI = "slice_uri";
    public static final java.lang.String EXTRA_INTENT = "slice_intent";
    public static final java.lang.String EXTRA_PKG = "pkg";
    public static final java.lang.String EXTRA_RESULT = "result";
    public static final java.lang.String EXTRA_SLICE = "slice";
    public static final java.lang.String EXTRA_SLICE_DESCENDANTS = "slice_descendants";
    public static final java.lang.String EXTRA_SUPPORTED_SPECS = "supported_specs";
    public static final java.lang.String METHOD_GET_DESCENDANTS = "get_descendants";
    public static final java.lang.String METHOD_GET_PERMISSIONS = "get_permissions";
    public static final java.lang.String METHOD_MAP_INTENT = "map_slice";
    public static final java.lang.String METHOD_MAP_ONLY_INTENT = "map_only";
    public static final java.lang.String METHOD_PIN = "pin";
    public static final java.lang.String METHOD_SLICE = "bind_slice";
    public static final java.lang.String METHOD_UNPIN = "unpin";
    public static final java.lang.String SLICE_TYPE = "vnd.android.slice";
    public SliceProvider() { super(); }
    public SliceProvider(java.lang.String[] p0) { super(); }
    public static android.content.Intent createPermissionIntent(android.content.Context p0, android.net.Uri p1, java.lang.String p2) { return null; }
    public static android.app.PendingIntent createPermissionPendingIntent(android.content.Context p0, android.net.Uri p1, java.lang.String p2) { return null; }
    public static java.lang.CharSequence getPermissionString(android.content.Context p0, java.lang.String p1) { return null; }
    public android.app.slice.Slice createPermissionSlice(android.content.Context p0, android.net.Uri p1, java.lang.String p2) { return null; }
    public int delete(android.net.Uri p0, java.lang.String p1, java.lang.String[] p2) { return 0; }
    public java.lang.String getType(android.net.Uri p0) { return null; }
    public android.net.Uri insert(android.net.Uri p0, android.content.ContentValues p1) { return null; }
    public android.app.slice.Slice onBindSlice(android.net.Uri p0, java.util.Set p1) { return null; }
    public android.app.PendingIntent onCreatePermissionRequest(android.net.Uri p0) { return null; }
    public java.util.Collection onGetSliceDescendants(android.net.Uri p0) { return new java.util.ArrayList(); }
    public android.net.Uri onMapIntentToUri(android.content.Intent p0) { return null; }
    public void onSlicePinned(android.net.Uri p0) {}
    public void onSliceUnpinned(android.net.Uri p0) {}
    public android.database.Cursor query(android.net.Uri p0, java.lang.String[] p1, java.lang.String p2, java.lang.String[] p3, java.lang.String p4) { return null; }
    public int update(android.net.Uri p0, android.content.ContentValues p1, java.lang.String p2, java.lang.String[] p3) { return 0; }
}
