// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.printservice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class PrintService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String EXTRA_CAN_SELECT_PRINTER = "android.printservice.extra.CAN_SELECT_PRINTER";
    public static final java.lang.String EXTRA_PRINTER_INFO = "android.intent.extra.print.EXTRA_PRINTER_INFO";
    public static final java.lang.String EXTRA_PRINT_DOCUMENT_INFO = "android.printservice.extra.PRINT_DOCUMENT_INFO";
    public static final java.lang.String EXTRA_PRINT_JOB_INFO = "android.intent.extra.print.PRINT_JOB_INFO";
    public static final java.lang.String EXTRA_SELECT_PRINTER = "android.printservice.extra.SELECT_PRINTER";
    public static final java.lang.String SERVICE_INTERFACE = "android.printservice.PrintService";
    public static final java.lang.String SERVICE_META_DATA = "android.printservice";
    public PrintService() { super(); }
    public android.print.PrinterId generatePrinterId(java.lang.String p0) { return null; }
    public java.util.List getActivePrintJobs() { return (huskProps.get("ActivePrintJobs") != null ? (java.util.List) huskProps.get("ActivePrintJobs") : new java.util.ArrayList()); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    protected void onConnected() {}
    protected abstract android.printservice.PrinterDiscoverySession onCreatePrinterDiscoverySession();
    protected void onDisconnected() {}
    protected abstract void onPrintJobQueued(android.printservice.PrintJob p0);
    protected abstract void onRequestCancelPrintJob(android.printservice.PrintJob p0);
}
