// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.preference;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class PreferenceActivity extends android.app.ListActivity implements android.preference.PreferenceManager.OnPreferenceTreeClickListener, android.preference.PreferenceFragment.OnPreferenceStartFragmentCallback {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String EXTRA_NO_HEADERS = ":android:no_headers";
    public static final java.lang.String EXTRA_SHOW_FRAGMENT = ":android:show_fragment";
    public static final java.lang.String EXTRA_SHOW_FRAGMENT_ARGUMENTS = ":android:show_fragment_args";
    public static final java.lang.String EXTRA_SHOW_FRAGMENT_SHORT_TITLE = ":android:show_fragment_short_title";
    public static final java.lang.String EXTRA_SHOW_FRAGMENT_TITLE = ":android:show_fragment_title";
    public static final long HEADER_ID_UNDEFINED = -1L;
    public PreferenceActivity() { super(); }
    public void addPreferencesFromIntent(android.content.Intent p0) {}
    public void addPreferencesFromResource(int p0) {}
    public android.preference.Preference findPreference(java.lang.CharSequence p0) { return null; }
    public void finishPreferencePanel(android.app.Fragment p0, int p1, android.content.Intent p2) {}
    public java.util.List getHeaders() { return (huskProps.get("Headers") != null ? (java.util.List) huskProps.get("Headers") : new java.util.ArrayList()); }
    protected android.widget.Button getNextButton() { return (android.widget.Button) huskProps.get("NextButton"); }
    public android.preference.PreferenceManager getPreferenceManager() { return (android.preference.PreferenceManager) huskProps.get("PreferenceManager"); }
    public android.preference.PreferenceScreen getPreferenceScreen() { return (android.preference.PreferenceScreen) huskProps.get("PreferenceScreen"); }
    public boolean hasHeaders() { return false; }
    protected boolean hasNextButton() { return false; }
    public void invalidateHeaders() {}
    public boolean isMultiPane() { return (huskProps.get("MultiPane") instanceof Boolean ? (Boolean) huskProps.get("MultiPane") : false); }
    protected boolean isValidFragment(java.lang.String p0) { return false; }
    public void loadHeadersFromResource(int p0, java.util.List p1) {}
    public void onBuildHeaders(java.util.List p0) {}
    public android.content.Intent onBuildStartFragmentIntent(java.lang.String p0, android.os.Bundle p1, int p2, int p3) { return null; }
    public android.preference.PreferenceActivity.Header onGetInitialHeader() { return null; }
    public android.preference.PreferenceActivity.Header onGetNewHeader() { return null; }
    public void onHeaderClick(android.preference.PreferenceActivity.Header p0, int p1) {}
    public boolean onIsHidingHeaders() { return false; }
    public boolean onIsMultiPane() { return false; }
    public void onListItemClick(android.widget.ListView p0, android.view.View p1, int p2, long p3) {}
    public boolean onPreferenceStartFragment(android.preference.PreferenceFragment p0, android.preference.Preference p1) { return false; }
    public boolean onPreferenceTreeClick(android.preference.PreferenceScreen p0, android.preference.Preference p1) { return false; }
    public void setListFooter(android.view.View p0) { huskProps.put("ListFooter", p0); }
    public void setParentTitle(java.lang.CharSequence p0, java.lang.CharSequence p1, android.view.View.OnClickListener p2) {}
    public void setPreferenceScreen(android.preference.PreferenceScreen p0) { huskProps.put("PreferenceScreen", p0); }
    public void showBreadCrumbs(java.lang.CharSequence p0, java.lang.CharSequence p1) {}
    public void startPreferenceFragment(android.app.Fragment p0, boolean p1) {}
    public void startPreferencePanel(java.lang.String p0, android.os.Bundle p1, int p2, java.lang.CharSequence p3, android.app.Fragment p4, int p5) {}
    public void startWithFragment(java.lang.String p0, android.os.Bundle p1, android.app.Fragment p2, int p3) {}
    public void startWithFragment(java.lang.String p0, android.os.Bundle p1, android.app.Fragment p2, int p3, int p4, int p5) {}
    public void switchToHeader(android.preference.PreferenceActivity.Header p0) {}
    public void switchToHeader(java.lang.String p0, android.os.Bundle p1) {}
    public static final class Header implements android.os.Parcelable {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static android.os.Parcelable.Creator CREATOR;
        public java.lang.CharSequence breadCrumbShortTitle;
        public int breadCrumbShortTitleRes;
        public java.lang.CharSequence breadCrumbTitle;
        public int breadCrumbTitleRes;
        public android.os.Bundle extras;
        public java.lang.String fragment;
        public android.os.Bundle fragmentArguments;
        public int iconRes;
        public long id;
        public android.content.Intent intent;
        public java.lang.CharSequence summary;
        public int summaryRes;
        public java.lang.CharSequence title;
        public int titleRes;
        public Header() {}
        public int describeContents() { return 0; }
        public java.lang.CharSequence getBreadCrumbShortTitle(android.content.res.Resources p0) { return null; }
        public java.lang.CharSequence getBreadCrumbTitle(android.content.res.Resources p0) { return null; }
        public java.lang.CharSequence getSummary(android.content.res.Resources p0) { return null; }
        public java.lang.CharSequence getTitle(android.content.res.Resources p0) { return null; }
        public void readFromParcel(android.os.Parcel p0) {}
        public void writeToParcel(android.os.Parcel p0, int p1) {}
    }
}
