// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.preference;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class PreferenceFragment extends android.app.Fragment implements android.preference.PreferenceManager.OnPreferenceTreeClickListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public PreferenceFragment() { super(); }
    public void addPreferencesFromIntent(android.content.Intent p0) {}
    public void addPreferencesFromResource(int p0) {}
    public android.preference.Preference findPreference(java.lang.CharSequence p0) { return null; }
    public android.widget.ListView getListView() { return (android.widget.ListView) huskProps.get("ListView"); }
    public android.preference.PreferenceManager getPreferenceManager() { return (android.preference.PreferenceManager) huskProps.get("PreferenceManager"); }
    public android.preference.PreferenceScreen getPreferenceScreen() { return (android.preference.PreferenceScreen) huskProps.get("PreferenceScreen"); }
    public boolean hasListView() { return false; }
    protected void onBindPreferences() {}
    public boolean onPreferenceTreeClick(android.preference.PreferenceScreen p0, android.preference.Preference p1) { return false; }
    protected void onUnbindPreferences() {}
    public void setPreferenceScreen(android.preference.PreferenceScreen p0) { huskProps.put("PreferenceScreen", p0); }
    public interface OnPreferenceStartFragmentCallback {
        boolean onPreferenceStartFragment(android.preference.PreferenceFragment p0, android.preference.Preference p1);
    }
}
