// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.midi;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class MidiUmpDeviceService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String SERVICE_INTERFACE = "android.media.midi.MidiUmpDeviceService";
    public MidiUmpDeviceService() { super(); }
    public android.media.midi.MidiDeviceInfo getDeviceInfo() { return (android.media.midi.MidiDeviceInfo) huskProps.get("DeviceInfo"); }
    public java.util.List getOutputPortReceivers() { return (huskProps.get("OutputPortReceivers") != null ? (java.util.List) huskProps.get("OutputPortReceivers") : new java.util.ArrayList()); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onClose() {}
    public void onDeviceStatusChanged(android.media.midi.MidiDeviceStatus p0) {}
    public abstract java.util.List onGetInputPortReceivers();
}
