// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.adservices.ondevicepersonalization;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class IsolatedService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public IsolatedService() { super(); }
    public android.adservices.ondevicepersonalization.EventUrlProvider getEventUrlProvider(android.adservices.ondevicepersonalization.RequestToken p0) { return null; }
    public android.adservices.ondevicepersonalization.FederatedComputeScheduler getFederatedComputeScheduler(android.adservices.ondevicepersonalization.RequestToken p0) { return null; }
    public android.adservices.ondevicepersonalization.MutableKeyValueStore getLocalData(android.adservices.ondevicepersonalization.RequestToken p0) { return null; }
    public android.adservices.ondevicepersonalization.LogReader getLogReader(android.adservices.ondevicepersonalization.RequestToken p0) { return null; }
    public android.adservices.ondevicepersonalization.ModelManager getModelManager(android.adservices.ondevicepersonalization.RequestToken p0) { return null; }
    public android.adservices.ondevicepersonalization.KeyValueStore getRemoteData(android.adservices.ondevicepersonalization.RequestToken p0) { return null; }
    public android.adservices.ondevicepersonalization.UserData getUserData(android.adservices.ondevicepersonalization.RequestToken p0) { return null; }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract android.adservices.ondevicepersonalization.IsolatedWorker onRequest(android.adservices.ondevicepersonalization.RequestToken p0);
}
