// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.speech;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class RecognitionService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String SERVICE_INTERFACE = "android.speech.RecognitionService";
    public static final java.lang.String SERVICE_META_DATA = "android.speech";
    public RecognitionService() { super(); }
    public android.content.Context createContext(android.content.ContextParams p0) { return null; }
    public int getMaxConcurrentSessionsCount() { return (huskProps.get("MaxConcurrentSessionsCount") instanceof Integer ? (Integer) huskProps.get("MaxConcurrentSessionsCount") : 0); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onBindInternal() {}
    protected abstract void onCancel(android.speech.RecognitionService.Callback p0);
    public void onCheckRecognitionSupport(android.content.Intent p0, android.content.AttributionSource p1, android.speech.RecognitionService.SupportCallback p2) {}
    public void onCheckRecognitionSupport(android.content.Intent p0, android.speech.RecognitionService.SupportCallback p1) {}
    protected abstract void onStartListening(android.content.Intent p0, android.speech.RecognitionService.Callback p1);
    protected abstract void onStopListening(android.speech.RecognitionService.Callback p0);
    public void onTriggerModelDownload(android.content.Intent p0) {}
    public void onTriggerModelDownload(android.content.Intent p0, android.content.AttributionSource p1) {}
    public void onTriggerModelDownload(android.content.Intent p0, android.content.AttributionSource p1, android.speech.ModelDownloadListener p2) {}
    public static class Callback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public void beginningOfSpeech() {}
        public void bufferReceived(byte[] p0) {}
        public void endOfSegmentedSession() {}
        public void endOfSpeech() {}
        public void error(int p0) {}
        public android.content.AttributionSource getCallingAttributionSource() { return (android.content.AttributionSource) huskProps.get("CallingAttributionSource"); }
        public int getCallingUid() { return (huskProps.get("CallingUid") instanceof Integer ? (Integer) huskProps.get("CallingUid") : 0); }
        public void languageDetection(android.os.Bundle p0) {}
        public void partialResults(android.os.Bundle p0) {}
        public void readyForSpeech(android.os.Bundle p0) {}
        public void results(android.os.Bundle p0) {}
        public void rmsChanged(float p0) {}
        public void segmentResults(android.os.Bundle p0) {}
        protected Callback() {}
    }
    public static class SupportCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public void onError(int p0) {}
        public void onSupportResult(android.speech.RecognitionSupport p0) {}
        protected SupportCallback() {}
    }
}
