// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.quicksettings;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TileService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String ACTION_QS_TILE = "android.service.quicksettings.action.QS_TILE";
    public static final java.lang.String ACTION_QS_TILE_PREFERENCES = "android.service.quicksettings.action.QS_TILE_PREFERENCES";
    public static final java.lang.String CATEGORY_ACCESSIBILITY = "android.service.quicksettings.CATEGORY_ACCESSIBILITY";
    public static final java.lang.String CATEGORY_CONNECTIVITY = "android.service.quicksettings.CATEGORY_CONNECTIVITY";
    public static final java.lang.String CATEGORY_DISPLAY = "android.service.quicksettings.CATEGORY_DISPLAY";
    public static final java.lang.String CATEGORY_PRIVACY = "android.service.quicksettings.CATEGORY_PRIVACY";
    public static final java.lang.String CATEGORY_UTILITIES = "android.service.quicksettings.CATEGORY_UTILITIES";
    public static final java.lang.String EXTRA_SERVICE = "service";
    public static final java.lang.String EXTRA_STATE = "state";
    public static final java.lang.String EXTRA_TOKEN = "token";
    public static final java.lang.String META_DATA_ACTIVE_TILE = "android.service.quicksettings.ACTIVE_TILE";
    public static final java.lang.String META_DATA_TILE_CATEGORY = "android.service.quicksettings.TILE_CATEGORY";
    public static final java.lang.String META_DATA_TOGGLEABLE_TILE = "android.service.quicksettings.TOGGLEABLE_TILE";
    public static final long START_ACTIVITY_NEEDS_PENDING_INTENT = 241766793L;
    public TileService() { super(); }
    public static boolean isQuickSettingsSupported() { return false; }
    public static void requestListeningState(android.content.Context p0, android.content.ComponentName p1) {}
    public android.service.quicksettings.Tile getQsTile() { return (android.service.quicksettings.Tile) huskProps.get("QsTile"); }
    public boolean isLocked() { return (huskProps.get("Locked") instanceof Boolean ? (Boolean) huskProps.get("Locked") : false); }
    public boolean isSecure() { return (huskProps.get("Secure") instanceof Boolean ? (Boolean) huskProps.get("Secure") : false); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public void onClick() {}
    public void onStartListening() {}
    public void onStopListening() {}
    public void onTileAdded() {}
    public void onTileRemoved() {}
    public void setStatusIcon(android.graphics.drawable.Icon p0, java.lang.String p1) {}
    public void showDialog(android.app.Dialog p0) {}
    public void startActivityAndCollapse(android.app.PendingIntent p0) {}
    public void startActivityAndCollapse(android.content.Intent p0) {}
    public void unlockAndRun(java.lang.Runnable p0) {}
}
