// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.accessibilityservice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class AccessibilityService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int ACCESSIBILITY_TAKE_SCREENSHOT_REQUEST_INTERVAL_TIMES_MS = 333;
    public static final int ERROR_TAKE_SCREENSHOT_INTERNAL_ERROR = 1;
    public static final int ERROR_TAKE_SCREENSHOT_INTERVAL_TIME_SHORT = 3;
    public static final int ERROR_TAKE_SCREENSHOT_INVALID_DISPLAY = 4;
    public static final int ERROR_TAKE_SCREENSHOT_INVALID_WINDOW = 5;
    public static final int ERROR_TAKE_SCREENSHOT_NO_ACCESSIBILITY_ACCESS = 2;
    public static final int ERROR_TAKE_SCREENSHOT_SECURE_WINDOW = 6;
    public static final int GESTURE_2_FINGER_DOUBLE_TAP = 20;
    public static final int GESTURE_2_FINGER_DOUBLE_TAP_AND_HOLD = 40;
    public static final int GESTURE_2_FINGER_SINGLE_TAP = 19;
    public static final int GESTURE_2_FINGER_SWIPE_DOWN = 26;
    public static final int GESTURE_2_FINGER_SWIPE_LEFT = 27;
    public static final int GESTURE_2_FINGER_SWIPE_RIGHT = 28;
    public static final int GESTURE_2_FINGER_SWIPE_UP = 25;
    public static final int GESTURE_2_FINGER_TRIPLE_TAP = 21;
    public static final int GESTURE_2_FINGER_TRIPLE_TAP_AND_HOLD = 43;
    public static final int GESTURE_3_FINGER_DOUBLE_TAP = 23;
    public static final int GESTURE_3_FINGER_DOUBLE_TAP_AND_HOLD = 41;
    public static final int GESTURE_3_FINGER_SINGLE_TAP = 22;
    public static final int GESTURE_3_FINGER_SINGLE_TAP_AND_HOLD = 44;
    public static final int GESTURE_3_FINGER_SWIPE_DOWN = 30;
    public static final int GESTURE_3_FINGER_SWIPE_LEFT = 31;
    public static final int GESTURE_3_FINGER_SWIPE_RIGHT = 32;
    public static final int GESTURE_3_FINGER_SWIPE_UP = 29;
    public static final int GESTURE_3_FINGER_TRIPLE_TAP = 24;
    public static final int GESTURE_3_FINGER_TRIPLE_TAP_AND_HOLD = 45;
    public static final int GESTURE_4_FINGER_DOUBLE_TAP = 38;
    public static final int GESTURE_4_FINGER_DOUBLE_TAP_AND_HOLD = 42;
    public static final int GESTURE_4_FINGER_SINGLE_TAP = 37;
    public static final int GESTURE_4_FINGER_SWIPE_DOWN = 34;
    public static final int GESTURE_4_FINGER_SWIPE_LEFT = 35;
    public static final int GESTURE_4_FINGER_SWIPE_RIGHT = 36;
    public static final int GESTURE_4_FINGER_SWIPE_UP = 33;
    public static final int GESTURE_4_FINGER_TRIPLE_TAP = 39;
    public static final int GESTURE_DOUBLE_TAP = 17;
    public static final int GESTURE_DOUBLE_TAP_AND_HOLD = 18;
    public static final int GESTURE_PASSTHROUGH = -1;
    public static final int GESTURE_SWIPE_DOWN = 2;
    public static final int GESTURE_SWIPE_DOWN_AND_LEFT = 15;
    public static final int GESTURE_SWIPE_DOWN_AND_RIGHT = 16;
    public static final int GESTURE_SWIPE_DOWN_AND_UP = 8;
    public static final int GESTURE_SWIPE_LEFT = 3;
    public static final int GESTURE_SWIPE_LEFT_AND_DOWN = 10;
    public static final int GESTURE_SWIPE_LEFT_AND_RIGHT = 5;
    public static final int GESTURE_SWIPE_LEFT_AND_UP = 9;
    public static final int GESTURE_SWIPE_RIGHT = 4;
    public static final int GESTURE_SWIPE_RIGHT_AND_DOWN = 12;
    public static final int GESTURE_SWIPE_RIGHT_AND_LEFT = 6;
    public static final int GESTURE_SWIPE_RIGHT_AND_UP = 11;
    public static final int GESTURE_SWIPE_UP = 1;
    public static final int GESTURE_SWIPE_UP_AND_DOWN = 7;
    public static final int GESTURE_SWIPE_UP_AND_LEFT = 13;
    public static final int GESTURE_SWIPE_UP_AND_RIGHT = 14;
    public static final int GESTURE_TOUCH_EXPLORATION = -2;
    public static final int GESTURE_UNKNOWN = 0;
    public static final int GLOBAL_ACTION_ACCESSIBILITY_ALL_APPS = 14;
    public static final int GLOBAL_ACTION_ACCESSIBILITY_BUTTON = 11;
    public static final int GLOBAL_ACTION_ACCESSIBILITY_BUTTON_CHOOSER = 12;
    public static final int GLOBAL_ACTION_ACCESSIBILITY_SHORTCUT = 13;
    public static final int GLOBAL_ACTION_BACK = 1;
    public static final int GLOBAL_ACTION_DISMISS_NOTIFICATION_SHADE = 15;
    public static final int GLOBAL_ACTION_DPAD_CENTER = 20;
    public static final int GLOBAL_ACTION_DPAD_DOWN = 17;
    public static final int GLOBAL_ACTION_DPAD_LEFT = 18;
    public static final int GLOBAL_ACTION_DPAD_RIGHT = 19;
    public static final int GLOBAL_ACTION_DPAD_UP = 16;
    public static final int GLOBAL_ACTION_HOME = 2;
    public static final int GLOBAL_ACTION_KEYCODE_HEADSETHOOK = 10;
    public static final int GLOBAL_ACTION_LOCK_SCREEN = 8;
    public static final int GLOBAL_ACTION_MEDIA_PLAY_PAUSE = 22;
    public static final int GLOBAL_ACTION_MENU = 21;
    public static final int GLOBAL_ACTION_NOTIFICATIONS = 4;
    public static final int GLOBAL_ACTION_POWER_DIALOG = 6;
    public static final int GLOBAL_ACTION_QUICK_SETTINGS = 5;
    public static final int GLOBAL_ACTION_RECENTS = 3;
    public static final int GLOBAL_ACTION_TAKE_SCREENSHOT = 9;
    public static final int GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN = 7;
    public static final java.lang.String KEY_ACCESSIBILITY_SCREENSHOT_COLORSPACE = "screenshot_colorSpace";
    public static final java.lang.String KEY_ACCESSIBILITY_SCREENSHOT_HARDWAREBUFFER = "screenshot_hardwareBuffer";
    public static final java.lang.String KEY_ACCESSIBILITY_SCREENSHOT_STATUS = "screenshot_status";
    public static final java.lang.String KEY_ACCESSIBILITY_SCREENSHOT_TIMESTAMP = "screenshot_timestamp";
    public static final int OVERLAY_RESULT_INTERNAL_ERROR = 1;
    public static final int OVERLAY_RESULT_INVALID = 2;
    public static final int OVERLAY_RESULT_SUCCESS = 0;
    public static final java.lang.String SERVICE_INTERFACE = "android.accessibilityservice.AccessibilityService";
    public static final java.lang.String SERVICE_META_DATA = "android.accessibilityservice";
    public static final int SHOW_MODE_AUTO = 0;
    public static final int SHOW_MODE_HARD_KEYBOARD_ORIGINAL_VALUE = 536870912;
    public static final int SHOW_MODE_HARD_KEYBOARD_OVERRIDDEN = 1073741824;
    public static final int SHOW_MODE_HIDDEN = 1;
    public static final int SHOW_MODE_IGNORE_HARD_KEYBOARD = 2;
    public static final int SHOW_MODE_MASK = 3;
    public static int TAKE_SCREENSHOT_SUCCESS;
    public AccessibilityService() { super(); }
    public void attachAccessibilityOverlayToDisplay(int p0, android.view.SurfaceControl p1) {}
    public void attachAccessibilityOverlayToDisplay(int p0, android.view.SurfaceControl p1, java.util.concurrent.Executor p2, java.util.function.IntConsumer p3) {}
    public void attachAccessibilityOverlayToWindow(int p0, android.view.SurfaceControl p1) {}
    public void attachAccessibilityOverlayToWindow(int p0, android.view.SurfaceControl p1, java.util.concurrent.Executor p2, java.util.function.IntConsumer p3) {}
    public boolean clearCache() { return false; }
    public boolean clearCachedSubtree(android.view.accessibility.AccessibilityNodeInfo p0) { return false; }
    public android.content.Context createWindowContext(android.view.Display p0, int p1, android.os.Bundle p2) { return null; }
    public void disableSelf() {}
    public boolean dispatchGesture(android.accessibilityservice.GestureDescription p0, android.accessibilityservice.AccessibilityService.GestureResultCallback p1, android.os.Handler p2) { return false; }
    public android.view.accessibility.AccessibilityNodeInfo findFocus(int p0) { return null; }
    public android.accessibilityservice.AccessibilityButtonController getAccessibilityButtonController() { return (android.accessibilityservice.AccessibilityButtonController) huskProps.get("AccessibilityButtonController"); }
    public android.accessibilityservice.AccessibilityButtonController getAccessibilityButtonController(int p0) { return null; }
    public android.accessibilityservice.BrailleDisplayController getBrailleDisplayController() { return (android.accessibilityservice.BrailleDisplayController) huskProps.get("BrailleDisplayController"); }
    public int getConnectionId() { return (huskProps.get("ConnectionId") instanceof Integer ? (Integer) huskProps.get("ConnectionId") : 0); }
    public android.accessibilityservice.FingerprintGestureController getFingerprintGestureController() { return (android.accessibilityservice.FingerprintGestureController) huskProps.get("FingerprintGestureController"); }
    public android.accessibilityservice.InputMethod getInputMethod() { return (android.accessibilityservice.InputMethod) huskProps.get("InputMethod"); }
    public android.accessibilityservice.AccessibilityService.MagnificationController getMagnificationController() { return (android.accessibilityservice.AccessibilityService.MagnificationController) huskProps.get("MagnificationController"); }
    public android.accessibilityservice.AccessibilityService.MagnificationController getMagnificationController(int p0) { return null; }
    public android.view.accessibility.AccessibilityNodeInfo getRootInActiveWindow() { return (android.view.accessibility.AccessibilityNodeInfo) huskProps.get("RootInActiveWindow"); }
    public android.view.accessibility.AccessibilityNodeInfo getRootInActiveWindow(int p0) { return null; }
    public android.accessibilityservice.AccessibilityServiceInfo getServiceInfo() { return (android.accessibilityservice.AccessibilityServiceInfo) huskProps.get("ServiceInfo"); }
    public android.accessibilityservice.AccessibilityService.SoftKeyboardController getSoftKeyboardController() { return (android.accessibilityservice.AccessibilityService.SoftKeyboardController) huskProps.get("SoftKeyboardController"); }
    public java.util.List getSystemActions() { return (huskProps.get("SystemActions") != null ? (java.util.List) huskProps.get("SystemActions") : new java.util.ArrayList()); }
    public android.accessibilityservice.TouchInteractionController getTouchInteractionController(int p0) { return null; }
    public java.util.List getWindows() { return (huskProps.get("Windows") != null ? (java.util.List) huskProps.get("Windows") : new java.util.ArrayList()); }
    public android.util.SparseArray getWindowsOnAllDisplays() { return (android.util.SparseArray) huskProps.get("WindowsOnAllDisplays"); }
    public boolean isCacheEnabled() { return (huskProps.get("CacheEnabled") instanceof Boolean ? (Boolean) huskProps.get("CacheEnabled") : false); }
    public boolean isNodeInCache(android.view.accessibility.AccessibilityNodeInfo p0) { return false; }
    public abstract void onAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0);
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public android.accessibilityservice.InputMethod onCreateInputMethod() { return null; }
    protected boolean onGesture(int p0) { return false; }
    public boolean onGesture(android.accessibilityservice.AccessibilityGestureEvent p0) { return false; }
    public abstract void onInterrupt();
    protected boolean onKeyEvent(android.view.KeyEvent p0) { return false; }
    public void onMotionEvent(android.view.MotionEvent p0) {}
    protected void onServiceConnected() {}
    public void onSystemActionsChanged() {}
    public boolean performGlobalAction(int p0) { return false; }
    public void setAccessibilityFocusAppearance(int p0, int p1) {}
    public void setAnimationScale(float p0) { huskProps.put("AnimationScale", Float.valueOf(p0)); }
    public boolean setCacheEnabled(boolean p0) { return false; }
    public void setGestureDetectionPassthroughRegion(int p0, android.graphics.Region p1) {}
    public void setServiceInfo(android.accessibilityservice.AccessibilityServiceInfo p0) { huskProps.put("ServiceInfo", p0); }
    public void setTouchExplorationPassthroughRegion(int p0, android.graphics.Region p1) {}
    public void takeScreenshot(int p0, java.util.concurrent.Executor p1, android.accessibilityservice.AccessibilityService.TakeScreenshotCallback p2) {}
    public void takeScreenshotOfWindow(int p0, java.util.concurrent.Executor p1, android.accessibilityservice.AccessibilityService.TakeScreenshotCallback p2) {}
    public interface Callbacks {
        void init(int p0, android.os.IBinder p1);
        void onAccessibilityButtonAvailabilityChanged(boolean p0);
        void onAccessibilityButtonClicked(int p0);
        void onAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0);
        void onFingerprintCapturingGesturesChanged(boolean p0);
        void onFingerprintGesture(int p0);
        boolean onGesture(android.accessibilityservice.AccessibilityGestureEvent p0);
        void onInterrupt();
        boolean onKeyEvent(android.view.KeyEvent p0);
        void onMagnificationChanged(int p0, android.graphics.Region p1, android.accessibilityservice.MagnificationConfig p2);
        void onMotionEvent(android.view.MotionEvent p0);
        void onPerformGestureResult(int p0, boolean p1);
        void onServiceConnected();
        void onSoftKeyboardShowModeChanged(int p0);
        void onSystemActionsChanged();
        void onTouchStateChanged(int p0, int p1);
    }
    public static abstract class GestureResultCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public GestureResultCallback() {}
        public void onCancelled(android.accessibilityservice.GestureDescription p0) {}
        public void onCompleted(android.accessibilityservice.GestureDescription p0) {}
    }
    public static abstract class IAccessibilityServiceClientWrapper extends android.accessibilityservice.IAccessibilityServiceClient.Stub {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public IAccessibilityServiceClientWrapper(android.content.Context p0, android.os.Looper p1, android.accessibilityservice.AccessibilityService.Callbacks p2) { super(); }
        public IAccessibilityServiceClientWrapper(android.content.Context p0, java.util.concurrent.Executor p1, android.accessibilityservice.AccessibilityService.Callbacks p2) { super(); }
        public void bindInput() {}
        public void clearAccessibilityCache() {}
        public void init(android.accessibilityservice.IAccessibilityServiceConnection p0, int p1, android.os.IBinder p2) {}
        public void onAccessibilityButtonAvailabilityChanged(boolean p0) {}
        public void onAccessibilityButtonClicked(int p0) {}
        public void onAccessibilityEvent(android.view.accessibility.AccessibilityEvent p0, boolean p1) {}
        public void onFingerprintCapturingGesturesChanged(boolean p0) {}
        public void onFingerprintGesture(int p0) {}
        public void onGesture(android.accessibilityservice.AccessibilityGestureEvent p0) {}
        public void onInterrupt() {}
        public void onKeyEvent(android.view.KeyEvent p0, int p1) {}
        public void onMagnificationChanged(int p0, android.graphics.Region p1, android.accessibilityservice.MagnificationConfig p2) {}
        public void onMotionEvent(android.view.MotionEvent p0) {}
        public void onPerformGestureResult(int p0, boolean p1) {}
        public void onSoftKeyboardShowModeChanged(int p0) {}
        public void onSystemActionsChanged() {}
        public void onTouchStateChanged(int p0, int p1) {}
        public void unbindInput() {}
        IAccessibilityServiceClientWrapper() { this((android.content.Context) null, (android.os.Looper) null, (android.accessibilityservice.AccessibilityService.Callbacks) null); }
    }
    public static final class MagnificationController {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public void addListener(android.accessibilityservice.AccessibilityService.MagnificationController.OnMagnificationChangedListener p0) {}
        public void addListener(android.accessibilityservice.AccessibilityService.MagnificationController.OnMagnificationChangedListener p0, android.os.Handler p1) {}
        public float getCenterX() { return (huskProps.get("CenterX") instanceof Float ? (Float) huskProps.get("CenterX") : 0f); }
        public float getCenterY() { return (huskProps.get("CenterY") instanceof Float ? (Float) huskProps.get("CenterY") : 0f); }
        public android.graphics.Region getCurrentMagnificationRegion() { return (android.graphics.Region) huskProps.get("CurrentMagnificationRegion"); }
        public android.accessibilityservice.MagnificationConfig getMagnificationConfig() { return (android.accessibilityservice.MagnificationConfig) huskProps.get("MagnificationConfig"); }
        public android.graphics.Region getMagnificationRegion() { return (android.graphics.Region) huskProps.get("MagnificationRegion"); }
        public float getScale() { return (huskProps.get("Scale") instanceof Float ? (Float) huskProps.get("Scale") : 0f); }
        public boolean removeListener(android.accessibilityservice.AccessibilityService.MagnificationController.OnMagnificationChangedListener p0) { return false; }
        public boolean reset(boolean p0) { return false; }
        public boolean resetCurrentMagnification(boolean p0) { return false; }
        public boolean setCenter(float p0, float p1, boolean p2) { return false; }
        public boolean setMagnificationConfig(android.accessibilityservice.MagnificationConfig p0, boolean p1) { return false; }
        public boolean setScale(float p0, boolean p1) { return false; }
        protected MagnificationController() {}
        public interface OnMagnificationChangedListener {
            void onMagnificationChanged(android.accessibilityservice.AccessibilityService.MagnificationController p0, android.graphics.Region p1, float p2, float p3, float p4);
            default void onMagnificationChanged(android.accessibilityservice.AccessibilityService.MagnificationController p0, android.graphics.Region p1, android.accessibilityservice.MagnificationConfig p2) {}
        }
    }
    public static final class ScreenshotResult {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public ScreenshotResult(android.hardware.HardwareBuffer p0, android.graphics.ColorSpace p1, long p2) {}
        public android.graphics.ColorSpace getColorSpace() { return (android.graphics.ColorSpace) huskProps.get("ColorSpace"); }
        public android.hardware.HardwareBuffer getHardwareBuffer() { return (android.hardware.HardwareBuffer) huskProps.get("HardwareBuffer"); }
        public long getTimestamp() { return (huskProps.get("Timestamp") instanceof Long ? (Long) huskProps.get("Timestamp") : 0L); }
        ScreenshotResult() { this((android.hardware.HardwareBuffer) null, (android.graphics.ColorSpace) null, (long) 0L); }
    }
    public static final class SoftKeyboardController {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public static final int ENABLE_IME_FAIL_BY_ADMIN = 1;
        public static final int ENABLE_IME_FAIL_UNKNOWN = 2;
        public static int ENABLE_IME_SUCCESS;
        public void addOnShowModeChangedListener(android.accessibilityservice.AccessibilityService.SoftKeyboardController.OnShowModeChangedListener p0) {}
        public void addOnShowModeChangedListener(android.accessibilityservice.AccessibilityService.SoftKeyboardController.OnShowModeChangedListener p0, android.os.Handler p1) {}
        public int getShowMode() { return (huskProps.get("ShowMode") instanceof Integer ? (Integer) huskProps.get("ShowMode") : 0); }
        public boolean removeOnShowModeChangedListener(android.accessibilityservice.AccessibilityService.SoftKeyboardController.OnShowModeChangedListener p0) { return false; }
        public int setInputMethodEnabled(java.lang.String p0, boolean p1) { return 0; }
        public boolean setShowMode(int p0) { return false; }
        public boolean switchToInputMethod(java.lang.String p0) { return false; }
        protected SoftKeyboardController() {}
        public interface OnShowModeChangedListener {
            void onShowModeChanged(android.accessibilityservice.AccessibilityService.SoftKeyboardController p0, int p1);
        }
    }
    public interface TakeScreenshotCallback {
        void onFailure(int p0);
        void onSuccess(android.accessibilityservice.AccessibilityService.ScreenshotResult p0);
    }
}
