// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.accounts;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class AccountAuthenticatorActivity extends android.app.Activity {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public AccountAuthenticatorActivity() { super(); }
    public void setAccountAuthenticatorResult(android.os.Bundle p0) { huskProps.put("AccountAuthenticatorResult", p0); }
}
