// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ActivityGroup extends android.app.Activity {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    protected android.app.LocalActivityManager mLocalActivityManager;
    public ActivityGroup() { super(); }
    public ActivityGroup(boolean p0) { super(); }
    public android.app.Activity getCurrentActivity() { return (android.app.Activity) huskProps.get("CurrentActivity"); }
    public android.app.LocalActivityManager getLocalActivityManager() { return (android.app.LocalActivityManager) huskProps.get("LocalActivityManager"); }
    public java.util.HashMap onRetainNonConfigurationChildInstances() { return null; }
}
