// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class AliasActivity extends android.app.Activity {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public java.lang.String ALIAS_META_DATA;
    public AliasActivity() { super(); }
}
