// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DialogFragment extends android.app.Fragment implements android.content.DialogInterface.OnCancelListener, android.content.DialogInterface.OnDismissListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int STYLE_NORMAL = 0;
    public static final int STYLE_NO_FRAME = 2;
    public static final int STYLE_NO_INPUT = 3;
    public static final int STYLE_NO_TITLE = 1;
    public DialogFragment() { super(); }
    public void dismiss() {}
    public void dismissAllowingStateLoss() {}
    public android.app.Dialog getDialog() { return (android.app.Dialog) huskProps.get("Dialog"); }
    public boolean getShowsDialog() { return (huskProps.get("ShowsDialog") instanceof Boolean ? (Boolean) huskProps.get("ShowsDialog") : false); }
    public int getTheme() { return (huskProps.get("Theme") instanceof Integer ? (Integer) huskProps.get("Theme") : 0); }
    public boolean isCancelable() { return (huskProps.get("Cancelable") instanceof Boolean ? (Boolean) huskProps.get("Cancelable") : false); }
    public void onCancel(android.content.DialogInterface p0) {}
    public android.app.Dialog onCreateDialog(android.os.Bundle p0) { return null; }
    public void onDismiss(android.content.DialogInterface p0) {}
    public void setCancelable(boolean p0) { huskProps.put("Cancelable", Boolean.valueOf(p0)); }
    public void setShowsDialog(boolean p0) { huskProps.put("ShowsDialog", Boolean.valueOf(p0)); }
    public void setStyle(int p0, int p1) {}
    public int show(android.app.FragmentTransaction p0, java.lang.String p1) { return 0; }
    public void show(android.app.FragmentManager p0, java.lang.String p1) {}
    public void showAllowingStateLoss(android.app.FragmentManager p0, java.lang.String p1) {}
}
