// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ExpandableListActivity extends android.app.Activity implements android.view.View.OnCreateContextMenuListener, android.widget.ExpandableListView.OnChildClickListener, android.widget.ExpandableListView.OnGroupCollapseListener, android.widget.ExpandableListView.OnGroupExpandListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public ExpandableListActivity() { super(); }
    public android.widget.ExpandableListAdapter getExpandableListAdapter() { return (android.widget.ExpandableListAdapter) huskProps.get("ExpandableListAdapter"); }
    public android.widget.ExpandableListView getExpandableListView() { return (android.widget.ExpandableListView) huskProps.get("ExpandableListView"); }
    public long getSelectedId() { return (huskProps.get("SelectedId") instanceof Long ? (Long) huskProps.get("SelectedId") : 0L); }
    public long getSelectedPosition() { return (huskProps.get("SelectedPosition") instanceof Long ? (Long) huskProps.get("SelectedPosition") : 0L); }
    public boolean onChildClick(android.widget.ExpandableListView p0, android.view.View p1, int p2, int p3, long p4) { return false; }
    public void onGroupCollapse(int p0) {}
    public void onGroupExpand(int p0) {}
    public void setListAdapter(android.widget.ExpandableListAdapter p0) { huskProps.put("ListAdapter", p0); }
    public boolean setSelectedChild(int p0, int p1, boolean p2) { return false; }
    public void setSelectedGroup(int p0) { huskProps.put("SelectedGroup", Integer.valueOf(p0)); }
}
