// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class LauncherActivity extends android.app.ListActivity {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public LauncherActivity() { super(); }
    protected android.content.Intent getTargetIntent() { return (android.content.Intent) huskProps.get("TargetIntent"); }
    protected android.content.Intent intentForPosition(int p0) { return null; }
    protected android.app.LauncherActivity.ListItem itemForPosition(int p0) { return null; }
    public java.util.List makeListItems() { return new java.util.ArrayList(); }
    protected boolean onEvaluateShowIcons() { return false; }
    public void onListItemClick(android.widget.ListView p0, android.view.View p1, int p2, long p3) {}
    protected java.util.List onQueryPackageManager(android.content.Intent p0) { return new java.util.ArrayList(); }
    protected void onSetContentView() {}
    protected void onSortResultList(java.util.List p0) {}
    public static class IconResizer {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public IconResizer(android.app.LauncherActivity p0) {}
        public android.graphics.drawable.Drawable createIconThumbnail(android.graphics.drawable.Drawable p0) { return null; }
        IconResizer() { this((android.app.LauncherActivity) null); }
    }
    public static class ListItem {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public java.lang.String className;
        public android.os.Bundle extras;
        public android.graphics.drawable.Drawable icon;
        public java.lang.CharSequence label;
        public java.lang.String packageName;
        public android.content.pm.ResolveInfo resolveInfo;
        public ListItem() {}
    }
}
