// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ListFragment extends android.app.Fragment {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public ListFragment() { super(); }
    public android.widget.ListAdapter getListAdapter() { return (android.widget.ListAdapter) huskProps.get("ListAdapter"); }
    public android.widget.ListView getListView() { return (android.widget.ListView) huskProps.get("ListView"); }
    public long getSelectedItemId() { return (huskProps.get("SelectedItemId") instanceof Long ? (Long) huskProps.get("SelectedItemId") : 0L); }
    public int getSelectedItemPosition() { return (huskProps.get("SelectedItemPosition") instanceof Integer ? (Integer) huskProps.get("SelectedItemPosition") : 0); }
    public void onListItemClick(android.widget.ListView p0, android.view.View p1, int p2, long p3) {}
    public void setEmptyText(java.lang.CharSequence p0) { huskProps.put("EmptyText", p0); }
    public void setListAdapter(android.widget.ListAdapter p0) { huskProps.put("ListAdapter", p0); }
    public void setListShown(boolean p0) { huskProps.put("ListShown", Boolean.valueOf(p0)); }
    public void setListShownNoAnimation(boolean p0) { huskProps.put("ListShownNoAnimation", Boolean.valueOf(p0)); }
    public void setSelection(int p0) { huskProps.put("Selection", Integer.valueOf(p0)); }
}
