// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class MediaRouteActionProvider extends android.view.ActionProvider {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public MediaRouteActionProvider(android.content.Context p0) { super(p0); }
    public boolean isVisible() { return (huskProps.get("Visible") instanceof Boolean ? (Boolean) huskProps.get("Visible") : false); }
    public android.view.View onCreateActionView() { return null; }
    public void setExtendedSettingsClickListener(android.view.View.OnClickListener p0) { huskProps.put("ExtendedSettingsClickListener", p0); }
    public void setRouteTypes(int p0) { huskProps.put("RouteTypes", Integer.valueOf(p0)); }
    MediaRouteActionProvider() { this((android.content.Context) null); }
}
