// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class MediaRouteButton extends android.view.View {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public MediaRouteButton(android.content.Context p0) { super(p0); }
    public MediaRouteButton(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public MediaRouteButton(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public MediaRouteButton(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public int getRouteTypes() { return (huskProps.get("RouteTypes") instanceof Integer ? (Integer) huskProps.get("RouteTypes") : 0); }
    public void setExtendedSettingsClickListener(android.view.View.OnClickListener p0) { huskProps.put("ExtendedSettingsClickListener", p0); }
    public void setRouteTypes(int p0) { huskProps.put("RouteTypes", Integer.valueOf(p0)); }
    public void showDialog() {}
    MediaRouteButton() { this((android.content.Context) null); }
}
