// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.app;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TabActivity extends android.app.ActivityGroup {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public TabActivity() { super(); }
    public android.widget.TabHost getTabHost() { return (android.widget.TabHost) huskProps.get("TabHost"); }
    public android.widget.TabWidget getTabWidget() { return (android.widget.TabWidget) huskProps.get("TabWidget"); }
    public void setDefaultTab(int p0) { huskProps.put("DefaultTab", Integer.valueOf(p0)); }
    public void setDefaultTab(java.lang.String p0) { huskProps.put("DefaultTab", p0); }
}
