// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class MediaSession2Service extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String SERVICE_INTERFACE = "android.media.MediaSession2Service";
    public MediaSession2Service() { super(); }
    public void addSession(android.media.MediaSession2 p0) {}
    public java.util.List getSessions() { return (huskProps.get("Sessions") != null ? (java.util.List) huskProps.get("Sessions") : new java.util.ArrayList()); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract android.media.MediaSession2 onGetSession(android.media.MediaSession2.ControllerInfo p0);
    public abstract android.media.MediaSession2Service.MediaNotification onUpdateNotification(android.media.MediaSession2 p0);
    public void removeSession(android.media.MediaSession2 p0) {}
    public static class MediaNotification {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public MediaNotification(int p0, android.app.Notification p1) {}
        public android.app.Notification getNotification() { return (android.app.Notification) huskProps.get("Notification"); }
        public int getNotificationId() { return (huskProps.get("NotificationId") instanceof Integer ? (Integer) huskProps.get("NotificationId") : 0); }
        MediaNotification() { this((int) 0, (android.app.Notification) null); }
    }
}
