// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.text.method;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class CharacterPickerDialog extends android.app.Dialog implements android.widget.AdapterView.OnItemClickListener, android.view.View.OnClickListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public CharacterPickerDialog(android.content.Context p0, android.view.View p1, android.text.Editable p2, java.lang.String p3, boolean p4) { super((android.content.Context) null); }
    public void onClick(android.view.View p0) {}
    public void onItemClick(android.widget.AdapterView p0, android.view.View p1, int p2, long p3) {}
    CharacterPickerDialog() { this((android.content.Context) null, (android.view.View) null, (android.text.Editable) null, (java.lang.String) null, (boolean) false); }
}
