// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.audiofx;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class DynamicsProcessing extends android.media.audiofx.AudioEffect {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int VARIANT_FAVOR_FREQUENCY_RESOLUTION = 0;
    public static final int VARIANT_FAVOR_TIME_RESOLUTION = 1;
    public DynamicsProcessing(int p0) { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
    public DynamicsProcessing(int p0, int p1) { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
    public DynamicsProcessing(int p0, int p1, android.media.audiofx.DynamicsProcessing.Config p2) { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
    public android.media.audiofx.DynamicsProcessing.Channel getChannelByChannelIndex(int p0) { return null; }
    public int getChannelCount() { return (huskProps.get("ChannelCount") instanceof Integer ? (Integer) huskProps.get("ChannelCount") : 0); }
    public android.media.audiofx.DynamicsProcessing.Config getConfig() { return (android.media.audiofx.DynamicsProcessing.Config) huskProps.get("Config"); }
    public float getInputGainByChannelIndex(int p0) { return 0f; }
    public android.media.audiofx.DynamicsProcessing.Limiter getLimiterByChannelIndex(int p0) { return null; }
    public android.media.audiofx.DynamicsProcessing.MbcBand getMbcBandByChannelIndex(int p0, int p1) { return null; }
    public android.media.audiofx.DynamicsProcessing.Mbc getMbcByChannelIndex(int p0) { return null; }
    public android.media.audiofx.DynamicsProcessing.EqBand getPostEqBandByChannelIndex(int p0, int p1) { return null; }
    public android.media.audiofx.DynamicsProcessing.Eq getPostEqByChannelIndex(int p0) { return null; }
    public android.media.audiofx.DynamicsProcessing.EqBand getPreEqBandByChannelIndex(int p0, int p1) { return null; }
    public android.media.audiofx.DynamicsProcessing.Eq getPreEqByChannelIndex(int p0) { return null; }
    public android.media.audiofx.DynamicsProcessing.Settings getProperties() { return (android.media.audiofx.DynamicsProcessing.Settings) huskProps.get("Properties"); }
    public void setAllChannelsTo(android.media.audiofx.DynamicsProcessing.Channel p0) { huskProps.put("AllChannelsTo", p0); }
    public void setChannelTo(int p0, android.media.audiofx.DynamicsProcessing.Channel p1) {}
    public void setInputGainAllChannelsTo(float p0) { huskProps.put("InputGainAllChannelsTo", Float.valueOf(p0)); }
    public void setInputGainbyChannel(int p0, float p1) {}
    public void setLimiterAllChannelsTo(android.media.audiofx.DynamicsProcessing.Limiter p0) { huskProps.put("LimiterAllChannelsTo", p0); }
    public void setLimiterByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Limiter p1) {}
    public void setMbcAllChannelsTo(android.media.audiofx.DynamicsProcessing.Mbc p0) { huskProps.put("MbcAllChannelsTo", p0); }
    public void setMbcBandAllChannelsTo(int p0, android.media.audiofx.DynamicsProcessing.MbcBand p1) {}
    public void setMbcBandByChannelIndex(int p0, int p1, android.media.audiofx.DynamicsProcessing.MbcBand p2) {}
    public void setMbcByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Mbc p1) {}
    public void setPostEqAllChannelsTo(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PostEqAllChannelsTo", p0); }
    public void setPostEqBandAllChannelsTo(int p0, android.media.audiofx.DynamicsProcessing.EqBand p1) {}
    public void setPostEqBandByChannelIndex(int p0, int p1, android.media.audiofx.DynamicsProcessing.EqBand p2) {}
    public void setPostEqByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Eq p1) {}
    public void setPreEqAllChannelsTo(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PreEqAllChannelsTo", p0); }
    public void setPreEqBandAllChannelsTo(int p0, android.media.audiofx.DynamicsProcessing.EqBand p1) {}
    public void setPreEqBandByChannelIndex(int p0, int p1, android.media.audiofx.DynamicsProcessing.EqBand p2) {}
    public void setPreEqByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Eq p1) {}
    public void setProperties(android.media.audiofx.DynamicsProcessing.Settings p0) { huskProps.put("Properties", p0); }
    DynamicsProcessing() { this((int) 0); }
    public static class BandBase {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public BandBase(boolean p0, float p1) {}
        public float getCutoffFrequency() { return (huskProps.get("CutoffFrequency") instanceof Float ? (Float) huskProps.get("CutoffFrequency") : 0f); }
        public boolean isEnabled() { return (huskProps.get("Enabled") instanceof Boolean ? (Boolean) huskProps.get("Enabled") : false); }
        public void setCutoffFrequency(float p0) { huskProps.put("CutoffFrequency", Float.valueOf(p0)); }
        public void setEnabled(boolean p0) { huskProps.put("Enabled", Boolean.valueOf(p0)); }
        BandBase() { this((boolean) false, (float) 0f); }
    }
    public static class BandStage extends android.media.audiofx.DynamicsProcessing.Stage {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public BandStage(boolean p0, boolean p1, int p2) { super((boolean) false, (boolean) false); }
        public int getBandCount() { return (huskProps.get("BandCount") instanceof Integer ? (Integer) huskProps.get("BandCount") : 0); }
        BandStage() { this((boolean) false, (boolean) false, (int) 0); }
    }
    public static final class Channel {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Channel(float p0, boolean p1, int p2, boolean p3, int p4, boolean p5, int p6, boolean p7) {}
        public Channel(android.media.audiofx.DynamicsProcessing.Channel p0) {}
        public float getInputGain() { return (huskProps.get("InputGain") instanceof Float ? (Float) huskProps.get("InputGain") : 0f); }
        public android.media.audiofx.DynamicsProcessing.Limiter getLimiter() { return (android.media.audiofx.DynamicsProcessing.Limiter) huskProps.get("Limiter"); }
        public android.media.audiofx.DynamicsProcessing.Mbc getMbc() { return (android.media.audiofx.DynamicsProcessing.Mbc) huskProps.get("Mbc"); }
        public android.media.audiofx.DynamicsProcessing.MbcBand getMbcBand(int p0) { return null; }
        public android.media.audiofx.DynamicsProcessing.Eq getPostEq() { return (android.media.audiofx.DynamicsProcessing.Eq) huskProps.get("PostEq"); }
        public android.media.audiofx.DynamicsProcessing.EqBand getPostEqBand(int p0) { return null; }
        public android.media.audiofx.DynamicsProcessing.Eq getPreEq() { return (android.media.audiofx.DynamicsProcessing.Eq) huskProps.get("PreEq"); }
        public android.media.audiofx.DynamicsProcessing.EqBand getPreEqBand(int p0) { return null; }
        public void setInputGain(float p0) { huskProps.put("InputGain", Float.valueOf(p0)); }
        public void setLimiter(android.media.audiofx.DynamicsProcessing.Limiter p0) { huskProps.put("Limiter", p0); }
        public void setMbc(android.media.audiofx.DynamicsProcessing.Mbc p0) { huskProps.put("Mbc", p0); }
        public void setMbcBand(int p0, android.media.audiofx.DynamicsProcessing.MbcBand p1) {}
        public void setPostEq(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PostEq", p0); }
        public void setPostEqBand(int p0, android.media.audiofx.DynamicsProcessing.EqBand p1) {}
        public void setPreEq(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PreEq", p0); }
        public void setPreEqBand(int p0, android.media.audiofx.DynamicsProcessing.EqBand p1) {}
        Channel() { this((android.media.audiofx.DynamicsProcessing.Channel) null); }
    }
    public static final class Config {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Config(int p0, float p1, int p2, boolean p3, int p4, boolean p5, int p6, boolean p7, int p8, boolean p9, android.media.audiofx.DynamicsProcessing.Channel[] p10) {}
        public Config(int p0, android.media.audiofx.DynamicsProcessing.Config p1) {}
        public Config(android.media.audiofx.DynamicsProcessing.Config p0) {}
        public android.media.audiofx.DynamicsProcessing.Channel getChannelByChannelIndex(int p0) { return null; }
        public float getInputGainByChannelIndex(int p0) { return 0f; }
        public android.media.audiofx.DynamicsProcessing.Limiter getLimiterByChannelIndex(int p0) { return null; }
        public android.media.audiofx.DynamicsProcessing.MbcBand getMbcBandByChannelIndex(int p0, int p1) { return null; }
        public int getMbcBandCount() { return (huskProps.get("MbcBandCount") instanceof Integer ? (Integer) huskProps.get("MbcBandCount") : 0); }
        public android.media.audiofx.DynamicsProcessing.Mbc getMbcByChannelIndex(int p0) { return null; }
        public android.media.audiofx.DynamicsProcessing.EqBand getPostEqBandByChannelIndex(int p0, int p1) { return null; }
        public int getPostEqBandCount() { return (huskProps.get("PostEqBandCount") instanceof Integer ? (Integer) huskProps.get("PostEqBandCount") : 0); }
        public android.media.audiofx.DynamicsProcessing.Eq getPostEqByChannelIndex(int p0) { return null; }
        public android.media.audiofx.DynamicsProcessing.EqBand getPreEqBandByChannelIndex(int p0, int p1) { return null; }
        public int getPreEqBandCount() { return (huskProps.get("PreEqBandCount") instanceof Integer ? (Integer) huskProps.get("PreEqBandCount") : 0); }
        public android.media.audiofx.DynamicsProcessing.Eq getPreEqByChannelIndex(int p0) { return null; }
        public float getPreferredFrameDuration() { return (huskProps.get("PreferredFrameDuration") instanceof Float ? (Float) huskProps.get("PreferredFrameDuration") : 0f); }
        public int getVariant() { return (huskProps.get("Variant") instanceof Integer ? (Integer) huskProps.get("Variant") : 0); }
        public boolean isLimiterInUse() { return (huskProps.get("LimiterInUse") instanceof Boolean ? (Boolean) huskProps.get("LimiterInUse") : false); }
        public boolean isMbcInUse() { return (huskProps.get("MbcInUse") instanceof Boolean ? (Boolean) huskProps.get("MbcInUse") : false); }
        public boolean isPostEqInUse() { return (huskProps.get("PostEqInUse") instanceof Boolean ? (Boolean) huskProps.get("PostEqInUse") : false); }
        public boolean isPreEqInUse() { return (huskProps.get("PreEqInUse") instanceof Boolean ? (Boolean) huskProps.get("PreEqInUse") : false); }
        public void setAllChannelsTo(android.media.audiofx.DynamicsProcessing.Channel p0) { huskProps.put("AllChannelsTo", p0); }
        public void setChannelTo(int p0, android.media.audiofx.DynamicsProcessing.Channel p1) {}
        public void setInputGainAllChannelsTo(float p0) { huskProps.put("InputGainAllChannelsTo", Float.valueOf(p0)); }
        public void setInputGainByChannelIndex(int p0, float p1) {}
        public void setLimiterAllChannelsTo(android.media.audiofx.DynamicsProcessing.Limiter p0) { huskProps.put("LimiterAllChannelsTo", p0); }
        public void setLimiterByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Limiter p1) {}
        public void setMbcAllChannelsTo(android.media.audiofx.DynamicsProcessing.Mbc p0) { huskProps.put("MbcAllChannelsTo", p0); }
        public void setMbcBandAllChannelsTo(int p0, android.media.audiofx.DynamicsProcessing.MbcBand p1) {}
        public void setMbcBandByChannelIndex(int p0, int p1, android.media.audiofx.DynamicsProcessing.MbcBand p2) {}
        public void setMbcByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Mbc p1) {}
        public void setPostEqAllChannelsTo(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PostEqAllChannelsTo", p0); }
        public void setPostEqBandAllChannelsTo(int p0, android.media.audiofx.DynamicsProcessing.EqBand p1) {}
        public void setPostEqBandByChannelIndex(int p0, int p1, android.media.audiofx.DynamicsProcessing.EqBand p2) {}
        public void setPostEqByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Eq p1) {}
        public void setPreEqAllChannelsTo(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PreEqAllChannelsTo", p0); }
        public void setPreEqBandAllChannelsTo(int p0, android.media.audiofx.DynamicsProcessing.EqBand p1) {}
        public void setPreEqBandByChannelIndex(int p0, int p1, android.media.audiofx.DynamicsProcessing.EqBand p2) {}
        public void setPreEqByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Eq p1) {}
        Config() { this((android.media.audiofx.DynamicsProcessing.Config) null); }
        public static final class Builder {
            private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
            public Builder(int p0, int p1, boolean p2, int p3, boolean p4, int p5, boolean p6, int p7, boolean p8) {}
            public android.media.audiofx.DynamicsProcessing.Config build() { android.media.audiofx.DynamicsProcessing.Config x = new android.media.audiofx.DynamicsProcessing.Config(); x.huskProps.putAll(huskProps); return x; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setAllChannelsTo(android.media.audiofx.DynamicsProcessing.Channel p0) { huskProps.put("AllChannelsTo", p0); return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setChannelTo(int p0, android.media.audiofx.DynamicsProcessing.Channel p1) { return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setInputGainAllChannelsTo(float p0) { huskProps.put("InputGainAllChannelsTo", Float.valueOf(p0)); return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setInputGainByChannelIndex(int p0, float p1) { return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setLimiterAllChannelsTo(android.media.audiofx.DynamicsProcessing.Limiter p0) { huskProps.put("LimiterAllChannelsTo", p0); return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setLimiterByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Limiter p1) { return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setMbcAllChannelsTo(android.media.audiofx.DynamicsProcessing.Mbc p0) { huskProps.put("MbcAllChannelsTo", p0); return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setMbcByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Mbc p1) { return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setPostEqAllChannelsTo(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PostEqAllChannelsTo", p0); return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setPostEqByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Eq p1) { return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setPreEqAllChannelsTo(android.media.audiofx.DynamicsProcessing.Eq p0) { huskProps.put("PreEqAllChannelsTo", p0); return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setPreEqByChannelIndex(int p0, android.media.audiofx.DynamicsProcessing.Eq p1) { return this; }
            public android.media.audiofx.DynamicsProcessing.Config.Builder setPreferredFrameDuration(float p0) { huskProps.put("PreferredFrameDuration", Float.valueOf(p0)); return this; }
            Builder() { this((int) 0, (int) 0, (boolean) false, (int) 0, (boolean) false, (int) 0, (boolean) false, (int) 0, (boolean) false); }
        }
    }
    public static final class Eq extends android.media.audiofx.DynamicsProcessing.BandStage {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Eq(android.media.audiofx.DynamicsProcessing.Eq p0) { super((boolean) false, (boolean) false, (int) 0); }
        public Eq(boolean p0, boolean p1, int p2) { super(p0, p1, p2); }
        public android.media.audiofx.DynamicsProcessing.EqBand getBand(int p0) { return null; }
        public void setBand(int p0, android.media.audiofx.DynamicsProcessing.EqBand p1) {}
        Eq() { this((android.media.audiofx.DynamicsProcessing.Eq) null); }
    }
    public static final class EqBand extends android.media.audiofx.DynamicsProcessing.BandBase {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public EqBand(android.media.audiofx.DynamicsProcessing.EqBand p0) { super((boolean) false, (float) 0f); }
        public EqBand(boolean p0, float p1, float p2) { super((boolean) false, (float) 0f); }
        public float getGain() { return (huskProps.get("Gain") instanceof Float ? (Float) huskProps.get("Gain") : 0f); }
        public void setGain(float p0) { huskProps.put("Gain", Float.valueOf(p0)); }
        EqBand() { this((android.media.audiofx.DynamicsProcessing.EqBand) null); }
    }
    public static final class Limiter extends android.media.audiofx.DynamicsProcessing.Stage {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Limiter(android.media.audiofx.DynamicsProcessing.Limiter p0) { super((boolean) false, (boolean) false); }
        public Limiter(boolean p0, boolean p1, int p2, float p3, float p4, float p5, float p6, float p7) { super((boolean) false, (boolean) false); }
        public float getAttackTime() { return (huskProps.get("AttackTime") instanceof Float ? (Float) huskProps.get("AttackTime") : 0f); }
        public int getLinkGroup() { return (huskProps.get("LinkGroup") instanceof Integer ? (Integer) huskProps.get("LinkGroup") : 0); }
        public float getPostGain() { return (huskProps.get("PostGain") instanceof Float ? (Float) huskProps.get("PostGain") : 0f); }
        public float getRatio() { return (huskProps.get("Ratio") instanceof Float ? (Float) huskProps.get("Ratio") : 0f); }
        public float getReleaseTime() { return (huskProps.get("ReleaseTime") instanceof Float ? (Float) huskProps.get("ReleaseTime") : 0f); }
        public float getThreshold() { return (huskProps.get("Threshold") instanceof Float ? (Float) huskProps.get("Threshold") : 0f); }
        public void setAttackTime(float p0) { huskProps.put("AttackTime", Float.valueOf(p0)); }
        public void setLinkGroup(int p0) { huskProps.put("LinkGroup", Integer.valueOf(p0)); }
        public void setPostGain(float p0) { huskProps.put("PostGain", Float.valueOf(p0)); }
        public void setRatio(float p0) { huskProps.put("Ratio", Float.valueOf(p0)); }
        public void setReleaseTime(float p0) { huskProps.put("ReleaseTime", Float.valueOf(p0)); }
        public void setThreshold(float p0) { huskProps.put("Threshold", Float.valueOf(p0)); }
        Limiter() { this((android.media.audiofx.DynamicsProcessing.Limiter) null); }
    }
    public static final class Mbc extends android.media.audiofx.DynamicsProcessing.BandStage {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Mbc(android.media.audiofx.DynamicsProcessing.Mbc p0) { super((boolean) false, (boolean) false, (int) 0); }
        public Mbc(boolean p0, boolean p1, int p2) { super(p0, p1, p2); }
        public android.media.audiofx.DynamicsProcessing.MbcBand getBand(int p0) { return null; }
        public void setBand(int p0, android.media.audiofx.DynamicsProcessing.MbcBand p1) {}
        Mbc() { this((android.media.audiofx.DynamicsProcessing.Mbc) null); }
    }
    public static final class MbcBand extends android.media.audiofx.DynamicsProcessing.BandBase {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public MbcBand(android.media.audiofx.DynamicsProcessing.MbcBand p0) { super((boolean) false, (float) 0f); }
        public MbcBand(boolean p0, float p1, float p2, float p3, float p4, float p5, float p6, float p7, float p8, float p9, float p10) { super((boolean) false, (float) 0f); }
        public float getAttackTime() { return (huskProps.get("AttackTime") instanceof Float ? (Float) huskProps.get("AttackTime") : 0f); }
        public float getExpanderRatio() { return (huskProps.get("ExpanderRatio") instanceof Float ? (Float) huskProps.get("ExpanderRatio") : 0f); }
        public float getKneeWidth() { return (huskProps.get("KneeWidth") instanceof Float ? (Float) huskProps.get("KneeWidth") : 0f); }
        public float getNoiseGateThreshold() { return (huskProps.get("NoiseGateThreshold") instanceof Float ? (Float) huskProps.get("NoiseGateThreshold") : 0f); }
        public float getPostGain() { return (huskProps.get("PostGain") instanceof Float ? (Float) huskProps.get("PostGain") : 0f); }
        public float getPreGain() { return (huskProps.get("PreGain") instanceof Float ? (Float) huskProps.get("PreGain") : 0f); }
        public float getRatio() { return (huskProps.get("Ratio") instanceof Float ? (Float) huskProps.get("Ratio") : 0f); }
        public float getReleaseTime() { return (huskProps.get("ReleaseTime") instanceof Float ? (Float) huskProps.get("ReleaseTime") : 0f); }
        public float getThreshold() { return (huskProps.get("Threshold") instanceof Float ? (Float) huskProps.get("Threshold") : 0f); }
        public void setAttackTime(float p0) { huskProps.put("AttackTime", Float.valueOf(p0)); }
        public void setExpanderRatio(float p0) { huskProps.put("ExpanderRatio", Float.valueOf(p0)); }
        public void setKneeWidth(float p0) { huskProps.put("KneeWidth", Float.valueOf(p0)); }
        public void setNoiseGateThreshold(float p0) { huskProps.put("NoiseGateThreshold", Float.valueOf(p0)); }
        public void setPostGain(float p0) { huskProps.put("PostGain", Float.valueOf(p0)); }
        public void setPreGain(float p0) { huskProps.put("PreGain", Float.valueOf(p0)); }
        public void setRatio(float p0) { huskProps.put("Ratio", Float.valueOf(p0)); }
        public void setReleaseTime(float p0) { huskProps.put("ReleaseTime", Float.valueOf(p0)); }
        public void setThreshold(float p0) { huskProps.put("Threshold", Float.valueOf(p0)); }
        MbcBand() { this((android.media.audiofx.DynamicsProcessing.MbcBand) null); }
    }
    public interface OnParameterChangeListener {
        void onParameterChange(android.media.audiofx.DynamicsProcessing p0, int p1, int p2);
    }
    public static class Settings {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public int channelCount;
        public float[] inputGain;
        public Settings() {}
        public Settings(java.lang.String p0) {}
    }
    public static class Stage {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public Stage(boolean p0, boolean p1) {}
        public boolean isEnabled() { return (huskProps.get("Enabled") instanceof Boolean ? (Boolean) huskProps.get("Enabled") : false); }
        public boolean isInUse() { return (huskProps.get("InUse") instanceof Boolean ? (Boolean) huskProps.get("InUse") : false); }
        public void setEnabled(boolean p0) { huskProps.put("Enabled", Boolean.valueOf(p0)); }
        Stage() { this((boolean) false, (boolean) false); }
    }
}
