// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.audiofx;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class EnvironmentalReverb extends android.media.audiofx.AudioEffect {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int PARAM_DECAY_HF_RATIO = 3;
    public static final int PARAM_DECAY_TIME = 2;
    public static final int PARAM_DENSITY = 9;
    public static final int PARAM_DIFFUSION = 8;
    public static final int PARAM_REFLECTIONS_DELAY = 5;
    public static final int PARAM_REFLECTIONS_LEVEL = 4;
    public static final int PARAM_REVERB_DELAY = 7;
    public static final int PARAM_REVERB_LEVEL = 6;
    public static final int PARAM_ROOM_HF_LEVEL = 1;
    public static final int PARAM_ROOM_LEVEL = 0;
    public EnvironmentalReverb(int p0, int p1) { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
    public short getDecayHFRatio() { return (huskProps.get("DecayHFRatio") instanceof Short ? (Short) huskProps.get("DecayHFRatio") : (short) 0); }
    public int getDecayTime() { return (huskProps.get("DecayTime") instanceof Integer ? (Integer) huskProps.get("DecayTime") : 0); }
    public short getDensity() { return (huskProps.get("Density") instanceof Short ? (Short) huskProps.get("Density") : (short) 0); }
    public short getDiffusion() { return (huskProps.get("Diffusion") instanceof Short ? (Short) huskProps.get("Diffusion") : (short) 0); }
    public android.media.audiofx.EnvironmentalReverb.Settings getProperties() { return (android.media.audiofx.EnvironmentalReverb.Settings) huskProps.get("Properties"); }
    public int getReflectionsDelay() { return (huskProps.get("ReflectionsDelay") instanceof Integer ? (Integer) huskProps.get("ReflectionsDelay") : 0); }
    public short getReflectionsLevel() { return (huskProps.get("ReflectionsLevel") instanceof Short ? (Short) huskProps.get("ReflectionsLevel") : (short) 0); }
    public int getReverbDelay() { return (huskProps.get("ReverbDelay") instanceof Integer ? (Integer) huskProps.get("ReverbDelay") : 0); }
    public short getReverbLevel() { return (huskProps.get("ReverbLevel") instanceof Short ? (Short) huskProps.get("ReverbLevel") : (short) 0); }
    public short getRoomHFLevel() { return (huskProps.get("RoomHFLevel") instanceof Short ? (Short) huskProps.get("RoomHFLevel") : (short) 0); }
    public short getRoomLevel() { return (huskProps.get("RoomLevel") instanceof Short ? (Short) huskProps.get("RoomLevel") : (short) 0); }
    public void setDecayHFRatio(short p0) { huskProps.put("DecayHFRatio", Short.valueOf(p0)); }
    public void setDecayTime(int p0) { huskProps.put("DecayTime", Integer.valueOf(p0)); }
    public void setDensity(short p0) { huskProps.put("Density", Short.valueOf(p0)); }
    public void setDiffusion(short p0) { huskProps.put("Diffusion", Short.valueOf(p0)); }
    public void setProperties(android.media.audiofx.EnvironmentalReverb.Settings p0) { huskProps.put("Properties", p0); }
    public void setReflectionsDelay(int p0) { huskProps.put("ReflectionsDelay", Integer.valueOf(p0)); }
    public void setReflectionsLevel(short p0) { huskProps.put("ReflectionsLevel", Short.valueOf(p0)); }
    public void setReverbDelay(int p0) { huskProps.put("ReverbDelay", Integer.valueOf(p0)); }
    public void setReverbLevel(short p0) { huskProps.put("ReverbLevel", Short.valueOf(p0)); }
    public void setRoomHFLevel(short p0) { huskProps.put("RoomHFLevel", Short.valueOf(p0)); }
    public void setRoomLevel(short p0) { huskProps.put("RoomLevel", Short.valueOf(p0)); }
    EnvironmentalReverb() { this((int) 0, (int) 0); }
    public interface OnParameterChangeListener {
        void onParameterChange(android.media.audiofx.EnvironmentalReverb p0, int p1, int p2, int p3);
    }
    public static class Settings {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public short decayHFRatio;
        public int decayTime;
        public short density;
        public short diffusion;
        public int reflectionsDelay;
        public short reflectionsLevel;
        public int reverbDelay;
        public short reverbLevel;
        public short roomHFLevel;
        public short roomLevel;
        public Settings() {}
        public Settings(java.lang.String p0) {}
    }
}
