// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.audiofx;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Equalizer extends android.media.audiofx.AudioEffect {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int PARAM_BAND_FREQ_RANGE = 4;
    public static final int PARAM_BAND_LEVEL = 2;
    public static final int PARAM_CENTER_FREQ = 3;
    public static final int PARAM_CURRENT_PRESET = 6;
    public static final int PARAM_GET_BAND = 5;
    public static final int PARAM_GET_NUM_OF_PRESETS = 7;
    public static final int PARAM_GET_PRESET_NAME = 8;
    public static final int PARAM_LEVEL_RANGE = 1;
    public static final int PARAM_NUM_BANDS = 0;
    public static final int PARAM_STRING_SIZE_MAX = 32;
    public Equalizer(int p0, int p1) { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
    public short getBand(int p0) { return (short) 0; }
    public int[] getBandFreqRange(short p0) { return null; }
    public short getBandLevel(short p0) { return (short) 0; }
    public short[] getBandLevelRange() { return (short[]) huskProps.get("BandLevelRange"); }
    public int getCenterFreq(short p0) { return 0; }
    public short getCurrentPreset() { return (huskProps.get("CurrentPreset") instanceof Short ? (Short) huskProps.get("CurrentPreset") : (short) 0); }
    public short getNumberOfBands() { return (huskProps.get("NumberOfBands") instanceof Short ? (Short) huskProps.get("NumberOfBands") : (short) 0); }
    public short getNumberOfPresets() { return (huskProps.get("NumberOfPresets") instanceof Short ? (Short) huskProps.get("NumberOfPresets") : (short) 0); }
    public java.lang.String getPresetName(short p0) { return null; }
    public android.media.audiofx.Equalizer.Settings getProperties() { return (android.media.audiofx.Equalizer.Settings) huskProps.get("Properties"); }
    public void setBandLevel(short p0, short p1) {}
    public void setProperties(android.media.audiofx.Equalizer.Settings p0) { huskProps.put("Properties", p0); }
    public void usePreset(short p0) {}
    Equalizer() { this((int) 0, (int) 0); }
    public interface OnParameterChangeListener {
        void onParameterChange(android.media.audiofx.Equalizer p0, int p1, int p2, int p3, int p4);
    }
    public static class Settings {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public short[] bandLevels;
        public short curPreset;
        public short numBands;
        public Settings() {}
        public Settings(java.lang.String p0) {}
    }
}
