// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.audiofx;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class HapticGenerator extends android.media.audiofx.AudioEffect implements java.lang.AutoCloseable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static android.media.audiofx.HapticGenerator create(int p0) { return new HapticGenerator(); }
    public static boolean isAvailable() { return false; }
    public void close() {}
    protected HapticGenerator() { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
}
