// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.audiofx;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class PresetReverb extends android.media.audiofx.AudioEffect {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int PARAM_PRESET = 0;
    public static final short PRESET_LARGEHALL = (short) 5;
    public static final short PRESET_LARGEROOM = (short) 3;
    public static final short PRESET_MEDIUMHALL = (short) 4;
    public static final short PRESET_MEDIUMROOM = (short) 2;
    public static final short PRESET_NONE = (short) 0;
    public static final short PRESET_PLATE = (short) 6;
    public static final short PRESET_SMALLROOM = (short) 1;
    public PresetReverb(int p0, int p1) { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
    public short getPreset() { return (huskProps.get("Preset") instanceof Short ? (Short) huskProps.get("Preset") : (short) 0); }
    public android.media.audiofx.PresetReverb.Settings getProperties() { return (android.media.audiofx.PresetReverb.Settings) huskProps.get("Properties"); }
    public void setPreset(short p0) { huskProps.put("Preset", Short.valueOf(p0)); }
    public void setProperties(android.media.audiofx.PresetReverb.Settings p0) { huskProps.put("Properties", p0); }
    PresetReverb() { this((int) 0, (int) 0); }
    public interface OnParameterChangeListener {
        void onParameterChange(android.media.audiofx.PresetReverb p0, int p1, int p2, short p3);
    }
    public static class Settings {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public short preset;
        public Settings() {}
        public Settings(java.lang.String p0) {}
    }
}
