// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.audiofx;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Virtualizer extends android.media.audiofx.AudioEffect {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int PARAM_FORCE_VIRTUALIZATION_MODE = 3;
    public static final int PARAM_STRENGTH = 1;
    public static final int PARAM_STRENGTH_SUPPORTED = 0;
    public static final int PARAM_VIRTUALIZATION_MODE = 4;
    public static final int PARAM_VIRTUAL_SPEAKER_ANGLES = 2;
    public static final int VIRTUALIZATION_MODE_AUTO = 1;
    public static final int VIRTUALIZATION_MODE_BINAURAL = 2;
    public static final int VIRTUALIZATION_MODE_OFF = 0;
    public static final int VIRTUALIZATION_MODE_TRANSAURAL = 3;
    public Virtualizer(int p0, int p1) { super((java.util.UUID) null, (android.media.AudioDeviceAttributes) null); }
    public boolean canVirtualize(int p0, int p1) { return false; }
    public boolean forceVirtualizationMode(int p0) { return false; }
    public android.media.audiofx.Virtualizer.Settings getProperties() { return (android.media.audiofx.Virtualizer.Settings) huskProps.get("Properties"); }
    public short getRoundedStrength() { return (huskProps.get("RoundedStrength") instanceof Short ? (Short) huskProps.get("RoundedStrength") : (short) 0); }
    public boolean getSpeakerAngles(int p0, int p1, int[] p2) { return false; }
    public boolean getStrengthSupported() { return (huskProps.get("StrengthSupported") instanceof Boolean ? (Boolean) huskProps.get("StrengthSupported") : false); }
    public int getVirtualizationMode() { return (huskProps.get("VirtualizationMode") instanceof Integer ? (Integer) huskProps.get("VirtualizationMode") : 0); }
    public void setProperties(android.media.audiofx.Virtualizer.Settings p0) { huskProps.put("Properties", p0); }
    public void setStrength(short p0) { huskProps.put("Strength", Short.valueOf(p0)); }
    Virtualizer() { this((int) 0, (int) 0); }
    public interface OnParameterChangeListener {
        void onParameterChange(android.media.audiofx.Virtualizer p0, int p1, int p2, short p3);
    }
    public static class Settings {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public short strength;
        public Settings() {}
        public Settings(java.lang.String p0) {}
    }
}
