// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class AdapterViewAnimator extends android.widget.AdapterView implements android.widget.RemoteViewsAdapter.RemoteAdapterConnectionCallback, android.widget.Advanceable {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public AdapterViewAnimator(android.content.Context p0) { super(p0); }
    public AdapterViewAnimator(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public AdapterViewAnimator(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public AdapterViewAnimator(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public void advance() {}
    public void deferNotifyDataSetChanged() {}
    public void fyiWillBeAdvancedByHostKThx() {}
    public java.lang.CharSequence getAccessibilityClassName() { return (java.lang.CharSequence) huskProps.get("AccessibilityClassName"); }
    public android.widget.Adapter getAdapter() { return (android.widget.Adapter) huskProps.get("Adapter"); }
    public int getBaseline() { return (huskProps.get("Baseline") instanceof Integer ? (Integer) huskProps.get("Baseline") : 0); }
    public android.view.View getCurrentView() { return (android.view.View) huskProps.get("CurrentView"); }
    public int getDisplayedChild() { return (huskProps.get("DisplayedChild") instanceof Integer ? (Integer) huskProps.get("DisplayedChild") : 0); }
    public android.animation.ObjectAnimator getInAnimation() { return (android.animation.ObjectAnimator) huskProps.get("InAnimation"); }
    public android.animation.ObjectAnimator getOutAnimation() { return (android.animation.ObjectAnimator) huskProps.get("OutAnimation"); }
    public android.view.View getSelectedView() { return (android.view.View) huskProps.get("SelectedView"); }
    public void onMeasure(int p0, int p1) {}
    public boolean onRemoteAdapterConnected() { return false; }
    public void onRemoteAdapterDisconnected() {}
    public void onRestoreInstanceState(android.os.Parcelable p0) {}
    public android.os.Parcelable onSaveInstanceState() { return null; }
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public void setAdapter(android.widget.Adapter p0) { huskProps.put("Adapter", p0); }
    public void setAnimateFirstView(boolean p0) { huskProps.put("AnimateFirstView", Boolean.valueOf(p0)); }
    public void setDisplayedChild(int p0) { huskProps.put("DisplayedChild", Integer.valueOf(p0)); }
    public void setInAnimation(android.animation.ObjectAnimator p0) { huskProps.put("InAnimation", p0); }
    public void setInAnimation(android.content.Context p0, int p1) {}
    public void setOutAnimation(android.animation.ObjectAnimator p0) { huskProps.put("OutAnimation", p0); }
    public void setOutAnimation(android.content.Context p0, int p1) {}
    public void setRemoteViewsAdapter(android.content.Intent p0) { huskProps.put("RemoteViewsAdapter", p0); }
    public void setRemoteViewsAdapter(android.content.Intent p0, boolean p1) {}
    public java.lang.Runnable setRemoteViewsAdapterAsync(android.content.Intent p0) { return null; }
    public void setRemoteViewsOnClickHandler(android.widget.RemoteViews.InteractionHandler p0) { huskProps.put("RemoteViewsOnClickHandler", p0); }
    public void setSelection(int p0) { huskProps.put("Selection", Integer.valueOf(p0)); }
    public void showNext() {}
    public void showPrevious() {}
    AdapterViewAnimator() { this((android.content.Context) null); }
}
