// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class CursorTreeAdapter extends android.widget.BaseExpandableListAdapter implements android.widget.Filterable, android.widget.CursorFilter.CursorFilterClient {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public CursorTreeAdapter(android.database.Cursor p0, android.content.Context p1) { super(); }
    public CursorTreeAdapter(android.database.Cursor p0, android.content.Context p1, boolean p2) { super(); }
    protected abstract void bindChildView(android.view.View p0, android.content.Context p1, android.database.Cursor p2, boolean p3);
    protected abstract void bindGroupView(android.view.View p0, android.content.Context p1, android.database.Cursor p2, boolean p3);
    public void changeCursor(android.database.Cursor p0) {}
    public java.lang.String convertToString(android.database.Cursor p0) { return null; }
    public android.database.Cursor getChild(int p0, int p1) { return null; }
    public long getChildId(int p0, int p1) { return 0L; }
    public android.view.View getChildView(int p0, int p1, boolean p2, android.view.View p3, android.view.ViewGroup p4) { return null; }
    public int getChildrenCount(int p0) { return 0; }
    protected abstract android.database.Cursor getChildrenCursor(android.database.Cursor p0);
    public android.database.Cursor getCursor() { return (android.database.Cursor) huskProps.get("Cursor"); }
    public android.widget.Filter getFilter() { return (android.widget.Filter) huskProps.get("Filter"); }
    public android.widget.FilterQueryProvider getFilterQueryProvider() { return (android.widget.FilterQueryProvider) huskProps.get("FilterQueryProvider"); }
    public android.database.Cursor getGroup(int p0) { return null; }
    public int getGroupCount() { return (huskProps.get("GroupCount") instanceof Integer ? (Integer) huskProps.get("GroupCount") : 0); }
    public long getGroupId(int p0) { return 0L; }
    public android.view.View getGroupView(int p0, boolean p1, android.view.View p2, android.view.ViewGroup p3) { return null; }
    public boolean hasStableIds() { return false; }
    public boolean isChildSelectable(int p0, int p1) { return false; }
    protected abstract android.view.View newChildView(android.content.Context p0, android.database.Cursor p1, boolean p2, android.view.ViewGroup p3);
    protected abstract android.view.View newGroupView(android.content.Context p0, android.database.Cursor p1, boolean p2, android.view.ViewGroup p3);
    public void notifyDataSetChanged(boolean p0) {}
    public android.database.Cursor runQueryOnBackgroundThread(java.lang.CharSequence p0) { return null; }
    public void setChildrenCursor(int p0, android.database.Cursor p1) {}
    public void setFilterQueryProvider(android.widget.FilterQueryProvider p0) { huskProps.put("FilterQueryProvider", p0); }
    public void setGroupCursor(android.database.Cursor p0) { huskProps.put("GroupCursor", p0); }
    CursorTreeAdapter() { this((android.database.Cursor) null, (android.content.Context) null); }
}
