// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DigitalClock extends android.widget.TextView {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public DigitalClock(android.content.Context p0) { super(p0); }
    public DigitalClock(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public void onAttachedToWindow() {}
    public void onDetachedFromWindow() {}
    DigitalClock() { this((android.content.Context) null); }
}
