// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Gallery extends android.widget.AbsSpinner implements android.view.GestureDetector.OnGestureListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public Gallery(android.content.Context p0) { super(p0); }
    public Gallery(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public Gallery(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public Gallery(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public boolean checkLayoutParams(android.view.ViewGroup.LayoutParams p0) { return false; }
    public int computeHorizontalScrollExtent() { return 0; }
    public int computeHorizontalScrollOffset() { return 0; }
    public int computeHorizontalScrollRange() { return 0; }
    public boolean dispatchKeyEvent(android.view.KeyEvent p0) { return false; }
    public void dispatchSetPressed(boolean p0) {}
    public void dispatchSetSelected(boolean p0) {}
    public android.view.ViewGroup.LayoutParams generateDefaultLayoutParams() { return null; }
    public android.view.ViewGroup.LayoutParams generateLayoutParams(android.util.AttributeSet p0) { return null; }
    public android.view.ViewGroup.LayoutParams generateLayoutParams(android.view.ViewGroup.LayoutParams p0) { return null; }
    public java.lang.CharSequence getAccessibilityClassName() { return (java.lang.CharSequence) huskProps.get("AccessibilityClassName"); }
    public int getChildDrawingOrder(int p0, int p1) { return 0; }
    public boolean getChildStaticTransformation(android.view.View p0, android.view.animation.Transformation p1) { return false; }
    protected android.view.ContextMenu.ContextMenuInfo getContextMenuInfo() { return (android.view.ContextMenu.ContextMenuInfo) huskProps.get("ContextMenuInfo"); }
    public void onAttachedToWindow() {}
    public boolean onDown(android.view.MotionEvent p0) { return false; }
    public boolean onFling(android.view.MotionEvent p0, android.view.MotionEvent p1, float p2, float p3) { return false; }
    public void onFocusChanged(boolean p0, int p1, android.graphics.Rect p2) {}
    public void onInitializeAccessibilityNodeInfoInternal(android.view.accessibility.AccessibilityNodeInfo p0) {}
    public boolean onKeyDown(int p0, android.view.KeyEvent p1) { return false; }
    public boolean onKeyUp(int p0, android.view.KeyEvent p1) { return false; }
    public void onLongPress(android.view.MotionEvent p0) {}
    public boolean onScroll(android.view.MotionEvent p0, android.view.MotionEvent p1, float p2, float p3) { return false; }
    public void onShowPress(android.view.MotionEvent p0) {}
    public boolean onSingleTapUp(android.view.MotionEvent p0) { return false; }
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public boolean performAccessibilityActionInternal(int p0, android.os.Bundle p1) { return false; }
    public void setAnimationDuration(int p0) { huskProps.put("AnimationDuration", Integer.valueOf(p0)); }
    public void setCallbackDuringFling(boolean p0) { huskProps.put("CallbackDuringFling", Boolean.valueOf(p0)); }
    public void setCallbackOnUnselectedItemClick(boolean p0) { huskProps.put("CallbackOnUnselectedItemClick", Boolean.valueOf(p0)); }
    public void setGravity(int p0) { huskProps.put("Gravity", Integer.valueOf(p0)); }
    public void setSpacing(int p0) { huskProps.put("Spacing", Integer.valueOf(p0)); }
    public void setUnselectedAlpha(float p0) { huskProps.put("UnselectedAlpha", Float.valueOf(p0)); }
    public boolean showContextMenu() { return false; }
    public boolean showContextMenu(float p0, float p1) { return false; }
    public boolean showContextMenuForChild(android.view.View p0) { return false; }
    public boolean showContextMenuForChild(android.view.View p0, float p1, float p2) { return false; }
    Gallery() { this((android.content.Context) null); }
    public static class LayoutParams extends android.view.ViewGroup.LayoutParams {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public LayoutParams(int p0, int p1) { super(p0, p1); }
        public LayoutParams(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
        public LayoutParams(android.view.ViewGroup.LayoutParams p0) { super(p0); }
        LayoutParams() { this((android.view.ViewGroup.LayoutParams) null); }
    }
}
