// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class SlidingDrawer extends android.view.ViewGroup {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final int ORIENTATION_HORIZONTAL = 0;
    public static final int ORIENTATION_VERTICAL = 1;
    public SlidingDrawer(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public SlidingDrawer(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public SlidingDrawer(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public void animateClose() {}
    public void animateOpen() {}
    public void animateToggle() {}
    public void close() {}
    public android.view.View getContent() { return (android.view.View) huskProps.get("Content"); }
    public android.view.View getHandle() { return (android.view.View) huskProps.get("Handle"); }
    public boolean isMoving() { return (huskProps.get("Moving") instanceof Boolean ? (Boolean) huskProps.get("Moving") : false); }
    public boolean isOpened() { return (huskProps.get("Opened") instanceof Boolean ? (Boolean) huskProps.get("Opened") : false); }
    public void lock() {}
    public void onLayout(boolean p0, int p1, int p2, int p3, int p4) {}
    public void open() {}
    public void setOnDrawerCloseListener(android.widget.SlidingDrawer.OnDrawerCloseListener p0) { huskProps.put("OnDrawerCloseListener", p0); }
    public void setOnDrawerOpenListener(android.widget.SlidingDrawer.OnDrawerOpenListener p0) { huskProps.put("OnDrawerOpenListener", p0); }
    public void setOnDrawerScrollListener(android.widget.SlidingDrawer.OnDrawerScrollListener p0) { huskProps.put("OnDrawerScrollListener", p0); }
    public void toggle() {}
    public void unlock() {}
    SlidingDrawer() { this((android.content.Context) null, (android.util.AttributeSet) null); }
    public interface OnDrawerCloseListener {
        void onDrawerClosed();
    }
    public interface OnDrawerOpenListener {
        void onDrawerOpened();
    }
    public interface OnDrawerScrollListener {
        void onScrollEnded();
        void onScrollStarted();
    }
}
