// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class StackView extends android.widget.AdapterViewAnimator {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public StackView(android.content.Context p0) { super(p0); }
    public StackView(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public StackView(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public StackView(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public void advance() {}
    public void dispatchDraw(android.graphics.Canvas p0) {}
    public java.lang.CharSequence getAccessibilityClassName() { return (java.lang.CharSequence) huskProps.get("AccessibilityClassName"); }
    public boolean onGenericMotionEvent(android.view.MotionEvent p0) { return false; }
    public void onInitializeAccessibilityNodeInfoInternal(android.view.accessibility.AccessibilityNodeInfo p0) {}
    public boolean onInterceptTouchEvent(android.view.MotionEvent p0) { return false; }
    public void onMeasure(int p0, int p1) {}
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public boolean performAccessibilityActionInternal(int p0, android.os.Bundle p1) { return false; }
    public void showNext() {}
    public void showPrevious() {}
    StackView() { this((android.content.Context) null); }
}
