// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TabHost extends android.widget.FrameLayout implements android.view.ViewTreeObserver.OnTouchModeChangeListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    protected int mCurrentTab;
    protected android.app.LocalActivityManager mLocalActivityManager;
    public TabHost(android.content.Context p0) { super(p0); }
    public TabHost(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public TabHost(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public TabHost(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public void addTab(android.widget.TabHost.TabSpec p0) {}
    public void clearAllTabs() {}
    public boolean dispatchKeyEvent(android.view.KeyEvent p0) { return false; }
    public void dispatchWindowFocusChanged(boolean p0) {}
    public int getCurrentTab() { return (huskProps.get("CurrentTab") instanceof Integer ? (Integer) huskProps.get("CurrentTab") : 0); }
    public java.lang.String getCurrentTabTag() { return (java.lang.String) huskProps.get("CurrentTabTag"); }
    public android.view.View getCurrentTabView() { return (android.view.View) huskProps.get("CurrentTabView"); }
    public android.view.View getCurrentView() { return (android.view.View) huskProps.get("CurrentView"); }
    public android.widget.FrameLayout getTabContentView() { return (android.widget.FrameLayout) huskProps.get("TabContentView"); }
    public android.widget.TabWidget getTabWidget() { return (android.widget.TabWidget) huskProps.get("TabWidget"); }
    public android.widget.TabHost.TabSpec newTabSpec(java.lang.String p0) { return null; }
    public void onTouchModeChanged(boolean p0) {}
    public void sendAccessibilityEventInternal(int p0) {}
    public void setCurrentTab(int p0) { huskProps.put("CurrentTab", Integer.valueOf(p0)); }
    public void setCurrentTabByTag(java.lang.String p0) { huskProps.put("CurrentTabByTag", p0); }
    public void setOnTabChangedListener(android.widget.TabHost.OnTabChangeListener p0) { huskProps.put("OnTabChangedListener", p0); }
    public void setup() {}
    public void setup(android.app.LocalActivityManager p0) { huskProps.put("up", p0); }
    TabHost() { this((android.content.Context) null); }
    public interface OnTabChangeListener {
        void onTabChanged(java.lang.String p0);
    }
    public interface TabContentFactory {
        android.view.View createTabContent(java.lang.String p0);
    }
    public static class TabSpec {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public java.lang.String getTag() { return (java.lang.String) huskProps.get("Tag"); }
        public android.widget.TabHost.TabSpec setContent(int p0) { huskProps.put("Content", Integer.valueOf(p0)); return this; }
        public android.widget.TabHost.TabSpec setContent(android.content.Intent p0) { huskProps.put("Content", p0); return this; }
        public android.widget.TabHost.TabSpec setContent(android.widget.TabHost.TabContentFactory p0) { huskProps.put("Content", p0); return this; }
        public android.widget.TabHost.TabSpec setIndicator(android.view.View p0) { huskProps.put("Indicator", p0); return this; }
        public android.widget.TabHost.TabSpec setIndicator(java.lang.CharSequence p0) { huskProps.put("Indicator", p0); return this; }
        public android.widget.TabHost.TabSpec setIndicator(java.lang.CharSequence p0, android.graphics.drawable.Drawable p1) { return this; }
        protected TabSpec() {}
    }
}
