// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TabWidget extends android.widget.LinearLayout implements android.view.View.OnFocusChangeListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public TabWidget(android.content.Context p0) { super(p0); }
    public TabWidget(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public TabWidget(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public TabWidget(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public void addView(android.view.View p0) {}
    public void childDrawableStateChanged(android.view.View p0) {}
    public void dispatchDraw(android.graphics.Canvas p0) {}
    public void focusCurrentTab(int p0) {}
    public int getChildDrawingOrder(int p0, int p1) { return 0; }
    public android.view.View getChildTabViewAt(int p0) { return null; }
    public android.graphics.drawable.Drawable getLeftStripDrawable() { return (android.graphics.drawable.Drawable) huskProps.get("LeftStripDrawable"); }
    public android.graphics.drawable.Drawable getRightStripDrawable() { return (android.graphics.drawable.Drawable) huskProps.get("RightStripDrawable"); }
    public int getTabCount() { return (huskProps.get("TabCount") instanceof Integer ? (Integer) huskProps.get("TabCount") : 0); }
    public boolean isStripEnabled() { return (huskProps.get("StripEnabled") instanceof Boolean ? (Boolean) huskProps.get("StripEnabled") : false); }
    public void onFocusChange(android.view.View p0, boolean p1) {}
    public void onInitializeAccessibilityEventInternal(android.view.accessibility.AccessibilityEvent p0) {}
    public android.view.PointerIcon onResolvePointerIcon(android.view.MotionEvent p0, int p1) { return null; }
    public void onSizeChanged(int p0, int p1, int p2, int p3) {}
    public void removeAllViews() {}
    public void setCurrentTab(int p0) { huskProps.put("CurrentTab", Integer.valueOf(p0)); }
    public void setDividerDrawable(int p0) { huskProps.put("DividerDrawable", Integer.valueOf(p0)); }
    public void setEnabled(boolean p0) { huskProps.put("Enabled", Boolean.valueOf(p0)); }
    public void setLeftStripDrawable(int p0) { huskProps.put("LeftStripDrawable", Integer.valueOf(p0)); }
    public void setLeftStripDrawable(android.graphics.drawable.Drawable p0) { huskProps.put("LeftStripDrawable", p0); }
    public void setRightStripDrawable(int p0) { huskProps.put("RightStripDrawable", Integer.valueOf(p0)); }
    public void setRightStripDrawable(android.graphics.drawable.Drawable p0) { huskProps.put("RightStripDrawable", p0); }
    public void setStripEnabled(boolean p0) { huskProps.put("StripEnabled", Boolean.valueOf(p0)); }
    TabWidget() { this((android.content.Context) null); }
}
