// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.widget;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ZoomButton extends android.widget.ImageButton implements android.view.View.OnLongClickListener {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public ZoomButton(android.content.Context p0) { super(p0); }
    public ZoomButton(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public ZoomButton(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public ZoomButton(android.content.Context p0, android.util.AttributeSet p1, int p2, int p3) { super(p0, p1, p2, p3); }
    public boolean dispatchUnhandledMove(android.view.View p0, int p1) { return false; }
    public boolean onKeyUp(int p0, android.view.KeyEvent p1) { return false; }
    public boolean onLongClick(android.view.View p0) { return false; }
    public boolean onTouchEvent(android.view.MotionEvent p0) { return false; }
    public void setEnabled(boolean p0) { huskProps.put("Enabled", Boolean.valueOf(p0)); }
    public void setZoomSpeed(long p0) { huskProps.put("ZoomSpeed", Long.valueOf(p0)); }
    ZoomButton() { this((android.content.Context) null); }
}
