// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.media.tv;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TvView extends android.view.ViewGroup {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public TvView(android.content.Context p0) { super(p0); }
    public TvView(android.content.Context p0, android.util.AttributeSet p1) { super(p0, p1); }
    public TvView(android.content.Context p0, android.util.AttributeSet p1, int p2) { super(p0, p1, p2); }
    public boolean dispatchUnhandledInputEvent(android.view.InputEvent p0) { return false; }
    public java.util.List getAudioPresentations() { return (huskProps.get("AudioPresentations") != null ? (java.util.List) huskProps.get("AudioPresentations") : new java.util.ArrayList()); }
    public android.media.tv.TvInputManager.Session getInputSession() { return (android.media.tv.TvInputManager.Session) huskProps.get("InputSession"); }
    public java.lang.String getSelectedTrack(int p0) { return null; }
    public java.util.List getTracks(int p0) { return new java.util.ArrayList(); }
    public void notifyTvMessage(int p0, android.os.Bundle p1) {}
    public void onLayout(boolean p0, int p1, int p2, int p3, int p4) {}
    public boolean onUnhandledInputEvent(android.view.InputEvent p0) { return false; }
    public void overrideTvAppAttributionSource(android.content.AttributionSource p0) {}
    public void requestUnblockContent(android.media.tv.TvContentRating p0) {}
    public void reset() {}
    public void resumePlayback() {}
    public void selectAudioPresentation(int p0, int p1) {}
    public void selectTrack(int p0, java.lang.String p1) {}
    public void sendAppPrivateCommand(java.lang.String p0, android.os.Bundle p1) {}
    public void setCallback(android.media.tv.TvView.TvInputCallback p0) { huskProps.put("Callback", p0); }
    public void setCaptionEnabled(boolean p0) { huskProps.put("CaptionEnabled", Boolean.valueOf(p0)); }
    public void setHandler(android.os.Handler p0) { huskProps.put("Handler", p0); }
    public void setInteractiveAppNotificationEnabled(boolean p0) { huskProps.put("InteractiveAppNotificationEnabled", Boolean.valueOf(p0)); }
    public void setMain() {}
    public void setOnUnhandledInputEventListener(android.media.tv.TvView.OnUnhandledInputEventListener p0) { huskProps.put("OnUnhandledInputEventListener", p0); }
    public void setStreamVolume(float p0) { huskProps.put("StreamVolume", Float.valueOf(p0)); }
    public void setTimeShiftPositionCallback(android.media.tv.TvView.TimeShiftPositionCallback p0) { huskProps.put("TimeShiftPositionCallback", p0); }
    public void setTvMessageEnabled(int p0, boolean p1) {}
    public void setVideoFrozen(boolean p0) { huskProps.put("VideoFrozen", Boolean.valueOf(p0)); }
    public void setZOrderMediaOverlay(boolean p0) { huskProps.put("ZOrderMediaOverlay", Boolean.valueOf(p0)); }
    public void setZOrderOnTop(boolean p0) { huskProps.put("ZOrderOnTop", Boolean.valueOf(p0)); }
    public void stopPlayback(int p0) {}
    public void timeShiftPause() {}
    public void timeShiftPlay(java.lang.String p0, android.net.Uri p1) {}
    public void timeShiftResume() {}
    public void timeShiftSeekTo(long p0) {}
    public void timeShiftSetMode(int p0) {}
    public void timeShiftSetPlaybackParams(android.media.PlaybackParams p0) {}
    public void tune(java.lang.String p0, android.net.Uri p1) {}
    public void tune(java.lang.String p0, android.net.Uri p1, android.os.Bundle p2) {}
    public void unblockContent(android.media.tv.TvContentRating p0) {}
    TvView() { this((android.content.Context) null); }
    public interface OnUnhandledInputEventListener {
        boolean onUnhandledInputEvent(android.view.InputEvent p0);
    }
    public static abstract class TimeShiftPositionCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public TimeShiftPositionCallback() {}
        public void onTimeShiftCurrentPositionChanged(java.lang.String p0, long p1) {}
        public void onTimeShiftStartPositionChanged(java.lang.String p0, long p1) {}
    }
    public static abstract class TvInputCallback {
        private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
        public TvInputCallback() {}
        public void onAitInfoUpdated(java.lang.String p0, android.media.tv.AitInfo p1) {}
        public void onAudioPresentationSelected(java.lang.String p0, int p1, int p2) {}
        public void onAudioPresentationsChanged(java.lang.String p0, java.util.List p1) {}
        public void onAvailableSpeeds(java.lang.String p0, float[] p1) {}
        public void onChannelRetuned(java.lang.String p0, android.net.Uri p1) {}
        public void onConnectionFailed(java.lang.String p0) {}
        public void onContentAllowed(java.lang.String p0) {}
        public void onContentBlocked(java.lang.String p0, android.media.tv.TvContentRating p1) {}
        public void onCueingMessageAvailability(java.lang.String p0, boolean p1) {}
        public void onDisconnected(java.lang.String p0) {}
        public void onEvent(java.lang.String p0, java.lang.String p1, android.os.Bundle p2) {}
        public void onSignalStrengthUpdated(java.lang.String p0, int p1) {}
        public void onTimeShiftMode(java.lang.String p0, int p1) {}
        public void onTimeShiftStatusChanged(java.lang.String p0, int p1) {}
        public void onTrackSelected(java.lang.String p0, int p1, java.lang.String p2) {}
        public void onTracksChanged(java.lang.String p0, java.util.List p1) {}
        public void onTuned(java.lang.String p0, android.net.Uri p1) {}
        public void onTvMessage(java.lang.String p0, int p1, android.os.Bundle p2) {}
        public void onVideoAvailable(java.lang.String p0) {}
        public void onVideoFreezeUpdated(java.lang.String p0, boolean p1) {}
        public void onVideoSizeChanged(java.lang.String p0, int p1, int p2) {}
        public void onVideoUnavailable(java.lang.String p0, int p1) {}
    }
}
