// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.voice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class VoiceInteractionService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String SERVICE_INTERFACE = "android.service.voice.VoiceInteractionService";
    public static final java.lang.String SERVICE_META_DATA = "android.voice_interaction";
    public VoiceInteractionService() { super(); }
    public static boolean isActiveService(android.content.Context p0, android.content.ComponentName p1) { return false; }
    public android.service.voice.AlwaysOnHotwordDetector createAlwaysOnHotwordDetector(java.lang.String p0, java.util.Locale p1, android.os.PersistableBundle p2, android.os.SharedMemory p3, android.service.voice.AlwaysOnHotwordDetector.Callback p4) { return null; }
    public android.service.voice.AlwaysOnHotwordDetector createAlwaysOnHotwordDetector(java.lang.String p0, java.util.Locale p1, android.os.PersistableBundle p2, android.os.SharedMemory p3, java.util.concurrent.Executor p4, android.service.voice.AlwaysOnHotwordDetector.Callback p5) { return null; }
    public android.service.voice.AlwaysOnHotwordDetector createAlwaysOnHotwordDetector(java.lang.String p0, java.util.Locale p1, android.service.voice.AlwaysOnHotwordDetector.Callback p2) { return null; }
    public android.service.voice.AlwaysOnHotwordDetector createAlwaysOnHotwordDetector(java.lang.String p0, java.util.Locale p1, java.util.concurrent.Executor p2, android.service.voice.AlwaysOnHotwordDetector.Callback p3) { return null; }
    public android.service.voice.AlwaysOnHotwordDetector createAlwaysOnHotwordDetectorForTest(java.lang.String p0, java.util.Locale p1, android.hardware.soundtrigger.SoundTrigger.ModuleProperties p2, java.util.concurrent.Executor p3, android.service.voice.AlwaysOnHotwordDetector.Callback p4) { return null; }
    public android.service.voice.AlwaysOnHotwordDetector createAlwaysOnHotwordDetectorForTest(java.lang.String p0, java.util.Locale p1, android.os.PersistableBundle p2, android.os.SharedMemory p3, android.hardware.soundtrigger.SoundTrigger.ModuleProperties p4, java.util.concurrent.Executor p5, android.service.voice.AlwaysOnHotwordDetector.Callback p6) { return null; }
    public android.service.voice.HotwordDetector createHotwordDetector(android.os.PersistableBundle p0, android.os.SharedMemory p1, android.service.voice.HotwordDetector.Callback p2) { return null; }
    public android.service.voice.HotwordDetector createHotwordDetector(android.os.PersistableBundle p0, android.os.SharedMemory p1, java.util.concurrent.Executor p2, android.service.voice.HotwordDetector.Callback p3) { return null; }
    public android.media.voice.KeyphraseModelManager createKeyphraseModelManager() { return null; }
    public android.service.voice.VisualQueryDetector createVisualQueryDetector(android.os.PersistableBundle p0, android.os.SharedMemory p1, java.util.concurrent.Executor p2, android.service.voice.VisualQueryDetector.Callback p3) { return null; }
    public int getDisabledShowContext() { return (huskProps.get("DisabledShowContext") instanceof Integer ? (Integer) huskProps.get("DisabledShowContext") : 0); }
    protected android.hardware.soundtrigger.KeyphraseEnrollmentInfo getKeyphraseEnrollmentInfo() { return (android.hardware.soundtrigger.KeyphraseEnrollmentInfo) huskProps.get("KeyphraseEnrollmentInfo"); }
    public boolean isKeyphraseAndLocaleSupportedForHotword(java.lang.String p0, java.util.Locale p1) { return false; }
    public java.util.List listModuleProperties() { return new java.util.ArrayList(); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public java.util.Set onGetSupportedVoiceActions(java.util.Set p0) { return new java.util.HashSet(); }
    public void onLaunchVoiceAssistFromKeyguard() {}
    public void onPrepareToShowSession(android.os.Bundle p0, int p1) {}
    public void onReady() {}
    public void onShowSessionFailed(android.os.Bundle p0) {}
    public void onShutdown() {}
    public void setDisabledShowContext(int p0) { huskProps.put("DisabledShowContext", Integer.valueOf(p0)); }
    public void setInvocationEffectEnabled(boolean p0) { huskProps.put("InvocationEffectEnabled", Boolean.valueOf(p0)); }
    public void setTestModuleForAlwaysOnHotwordDetectorEnabled(boolean p0) { huskProps.put("TestModuleForAlwaysOnHotwordDetectorEnabled", Boolean.valueOf(p0)); }
    public void setUiHints(android.os.Bundle p0) { huskProps.put("UiHints", p0); }
    public void showSession(android.os.Bundle p0, int p1) {}
}
