// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.voice;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class VoiceInteractionSessionService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public VoiceInteractionSessionService() { super(); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract android.service.voice.VoiceInteractionSession onNewSession(android.os.Bundle p0);
}
