// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.service.media;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class CameraPrewarmService extends android.app.Service {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public static final java.lang.String ACTION_PREWARM = "android.service.media.CameraPrewarmService.ACTION_PREWARM";
    public static final int MSG_CAMERA_FIRED = 1;
    public CameraPrewarmService() { super(); }
    public android.os.IBinder onBind(android.content.Intent p0) { return null; }
    public abstract void onCooldown(boolean p0);
    public abstract void onPrewarm();
}
