// Generated by tools/compat/genstubs.py from the platform's framework.jar: signatures and constants only.
package android.provider;

@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public abstract class DocumentsProvider extends android.content.ContentProvider {
    private final java.util.HashMap<String, Object> huskProps = new java.util.HashMap<>();
    public DocumentsProvider() { super(); }
    public void attachInfoForTesting(android.content.Context p0, android.content.pm.ProviderInfo p1) {}
    public java.lang.String copyDocument(java.lang.String p0, java.lang.String p1) { return null; }
    public java.lang.String createDocument(java.lang.String p0, java.lang.String p1, java.lang.String p2) { return null; }
    public android.content.IntentSender createWebLinkIntent(java.lang.String p0, android.os.Bundle p1) { return null; }
    public int delete(android.net.Uri p0, java.lang.String p1, java.lang.String[] p2) { return 0; }
    public void deleteDocument(java.lang.String p0) {}
    public void ejectRoot(java.lang.String p0) {}
    public android.provider.DocumentsContract.Path findDocumentPath(java.lang.String p0, java.lang.String p1) { return null; }
    public android.os.Bundle getDocumentMetadata(java.lang.String p0) { return null; }
    public java.lang.String[] getDocumentStreamTypes(java.lang.String p0, java.lang.String p1) { return null; }
    public java.lang.String getDocumentType(java.lang.String p0) { return null; }
    public java.lang.String getType(android.net.Uri p0) { return null; }
    public java.lang.String getTypeAnonymous(android.net.Uri p0) { return null; }
    public android.net.Uri insert(android.net.Uri p0, android.content.ContentValues p1) { return null; }
    public boolean isChildDocument(java.lang.String p0, java.lang.String p1) { return false; }
    public java.lang.String moveDocument(java.lang.String p0, java.lang.String p1, java.lang.String p2) { return null; }
    public abstract android.os.ParcelFileDescriptor openDocument(java.lang.String p0, java.lang.String p1, android.os.CancellationSignal p2);
    public android.content.res.AssetFileDescriptor openDocumentThumbnail(java.lang.String p0, android.graphics.Point p1, android.os.CancellationSignal p2) { return null; }
    public android.content.res.AssetFileDescriptor openTypedAssetFile(android.net.Uri p0, java.lang.String p1, android.os.Bundle p2, android.os.CancellationSignal p3) { return null; }
    public android.content.res.AssetFileDescriptor openTypedDocument(java.lang.String p0, java.lang.String p1, android.os.Bundle p2, android.os.CancellationSignal p3) { return null; }
    public android.database.Cursor query(android.net.Uri p0, java.lang.String[] p1, java.lang.String p2, java.lang.String[] p3, java.lang.String p4) { return null; }
    public android.database.Cursor queryChildDocuments(java.lang.String p0, java.lang.String[] p1, android.os.Bundle p2) { return null; }
    public abstract android.database.Cursor queryChildDocuments(java.lang.String p0, java.lang.String[] p1, java.lang.String p2);
    public android.database.Cursor queryChildDocumentsForManage(java.lang.String p0, java.lang.String[] p1, java.lang.String p2) { return null; }
    public abstract android.database.Cursor queryDocument(java.lang.String p0, java.lang.String[] p1);
    public android.database.Cursor queryRecentDocuments(java.lang.String p0, java.lang.String[] p1) { return null; }
    public android.database.Cursor queryRecentDocuments(java.lang.String p0, java.lang.String[] p1, android.os.Bundle p2, android.os.CancellationSignal p3) { return null; }
    public abstract android.database.Cursor queryRoots(java.lang.String[] p0);
    public android.database.Cursor querySearchDocuments(java.lang.String p0, java.lang.String p1, java.lang.String[] p2) { return null; }
    public android.database.Cursor querySearchDocuments(java.lang.String p0, java.lang.String[] p1, android.os.Bundle p2) { return null; }
    public android.database.Cursor queryTrashDocuments(java.lang.String[] p0) { return null; }
    public void removeDocument(java.lang.String p0, java.lang.String p1) {}
    public java.lang.String renameDocument(java.lang.String p0, java.lang.String p1) { return null; }
    public java.lang.String restoreDocumentFromTrash(java.lang.String p0, java.lang.String p1) { return null; }
    public void revokeDocumentPermission(java.lang.String p0) {}
    public java.lang.String trashDocument(java.lang.String p0) { return null; }
    public int update(android.net.Uri p0, android.content.ContentValues p1, java.lang.String p2, java.lang.String[] p3) { return 0; }
}
